expression: r0()
id: dede-cms-radminpass-disclosure
info:
    author: jijue
    description: |
        radminpass.php文件是一个用于修改管理员密码的PHP脚本工具
        多出现在新手站长用过这个工具以后忘记删了
        app="DedeCMS"
    name: 织梦CMS radminpass.php文件暴露
    severity: high
    tags:
        - DedeCMS
    verified: true
rules:
    r0:
        expression: response.body.bcontains(b'http://yousite/radminpass.php')
        request:
            method: GET
            path: /radminpass.php
