id: Airflow-unauthorized
info:
    author: Str1am
    name: Airflow未授权访问
    reference: http://www.str1am.top
    severity: high
    tags:
        - Airflow
        - unauthorized
http:
    - matchers:
        - condition: and
          type: word
          words:
            - Airflow - DAGs
      matchers-condition: and
      method: GET
      path:
        - '{{BaseURL}}/admin/'
