http:
    - matchers:
        - case-insensitive: true
          type: word
          words:
            - /converter/vmware-converter-client.exe
            - /vmw_nsx_logo-black-triangle-500w.png
            - content="vmware vcenter
      method: GET
      path:
        - '{{BaseURL}}/'
id: vmware-vcenter
info:
    author: cn-kali-team
    metadata:
        product: vmware-vcenter
        vendor: 00_unknown
        verified: false
    name: vmware-vcenter
    severity: info
    tags:
        - detect
        - tech
        - vmware-vcenter
        - VMware-vCenter
