http:
    - matchers:
        - case-insensitive: true
          type: word
          words:
            - /js/ecology8/lang/weaver_lang_7_wev8.js
            - /js/jquery/plugins/client/jquery.client_wev8.js
      method: GET
      path:
        - '{{BaseURL}}/'
id: fan-wei-oa-e-cology8
info:
    author: cn-kali-team
    metadata:
        product: 泛微-oa e-cology8
        vendor: 00_unknown
        verified: false
    name: 泛微-oa e-cology8
    severity: info
    tags:
        - detect
        - tech
        - jQuery
