http:
    - matchers:
        - type: word
          words:
            - JFIF
        - status:
            - 200
          type: status
      matchers-condition: and
      method: GET
      path:
        - '{{BaseURL}}/weaver/weaver.docs.docs.ShowDocsImageServlet?docId=1'
id: fanwei-eweaver-showdocsimageservlet-sqli
info:
    author: heiye798
    classification:
        cve-id: null
        cvss-metrics: null
        cvss-score: 9.1
        cwe-id: null
    description: 泛微 ShowDocsImageServlet处存在sql注入漏洞，攻击者可利用该漏洞获取数据库敏感信息。
    metadata:
        fofa: app="泛微-E-Weaver"
        verified: "true"
    name: 泛微 ShowDocsImageServlet sql注入漏洞
    reference:
        - none
    severity: critical
    tags:
        - weaver
        - fanwei
        - Eserv
        - showdoc
        - Servlet
        - ShowDoc
        - eserv
