id: Apache-solr-unauth
info:
    author: Str1am
    name: Apache solr 未授权访问
    reference: https://www.tuicool.com/articles/n2iuq2v
    severity: high
    tags:
        - solr
        - unauth
        - APACHE-Solr
        - Angular
http:
    - matchers:
        - status:
            - 200
          type: status
        - condition: and
          part: body
          type: word
          words:
            - Solr Admin
            - js/angular/controllers/core-overview.js
            - js/angular/controllers/dataimport.js
      matchers-condition: and
      method: GET
      path:
        - '{{BaseURL}}/solr/'
