http:
    - extractors:
        - json:
            - ."mixed-port"
          part: body
          type: json
      matchers:
        - condition: and
          type: word
          words:
            - '"allow-lan": true'
      method: GET
      path:
        - '{{RootURL}}/configs'
id: clash_proxy_unauthorized
info:
    author: Xc1Ym
    description: Clash 代理未授权访问
    metadata:
        fofa-query: body="{\"hello\":\"clash\"}"
        max-request: 1
        verified: true
    name: Clash 代理未授权访问
    severity: medium
    tags:
        - unauthorized
        - clash
        - network
        - others
