http:
    - matchers:
        - dsl:
            - status_code_1 == 200 && contains((body_1), '用户不存在')
          type: dsl
      method: GET
      path:
        - '{{RootURL}}/ispirit/retrieve_pwd.php?username={{rand_base(5)}}'
id: tongda-oa-retrieve-pwd-username-find
info:
    author: xy
    description: 通达OA /ispirit/retrieve_pwd.php 用户名遍历
    metadata:
        fofa-query: app="TDXK-通达OA"
        veified: true
    name: tongda-oa-retrieve-pwd-username-find
    reference:
        - https://zhuanlan.zhihu.com/p/346513138
    severity: low
    tags:
        - tongda
        - 通达oa
        - TDXK-通达OA
