http:
    - matchers:
        - status:
            - 200
          type: status
      matchers-condition: and
      method: GET
      path:
        - '{{BaseURL}}/general/management_center/portal/oa_engine/engine_manage_bulletin_number/query.php'
id: tongda_sqli2022
info:
    author: Str1am
    name: 通达oa sql注入
    severity: high
    tags:
        - tongda
        - 通达oa
