http:
    - matchers:
        - dsl:
            - status_code == 302
          type: dsl
        - part: header
          type: word
          words:
            - /seeyon/management/status.jsp
      matchers-condition: and
      raw:
        - |
          POST /seeyon/management/index.jsp HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/x-www-form-urlencoded

          password=WLCCYBD@SEEYON
id: seeyon-oa-a8-management-default-password
info:
    author: pphua
    description: 默认弱口令，存在信息泄露
    name: seeyon-oa-a8-management-default-password
    severity: medium
    tags:
        - seeyon
        - default-password
