http:
    - headers:
        Authorization: Basic YWRtaW46YWRtaW4=
      matchers:
        - status:
            - 200
          type: status
        - part: body
          type: word
          words:
            - /menu_admin.html
      method: GET
      path:
        - '{{BaseURL}}/index_main.html'
id: aolynk-br304-default-password
info:
    author: zan8in
    description: |
        fofa: Aolynk BR304
    name: 华为Aolynk BR304+ 智能安全路由器默认口令
    severity: high
    tags:
        - Aolynk BR304
