http:
    - matchers:
        - type: word
          words:
            - Do not remove this line
        - part: header
          type: word
          words:
            - application/x-perl
        - status:
            - 200
          type: status
      matchers-condition: and
      method: GET
      path:
        - '{{BaseURL}}/awstats.pl'
        - '{{BaseURL}}/logs/awstats.pl'
        - '{{BaseURL}}/webstats/awstats.pl'
id: awstats-script
info:
    author: sheikhrishad
    classification:
        cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
        cvss-score: 0
        cwe-id: CWE-200
    description: AWStats configuration information was detected.
    metadata:
        max-request: 3
    name: AWStats Script Config - Detect
    reference: https://www.awstats.org/docs/awstats_setup.html
    severity: info
    tags:
        - config
        - exposure
        - awstats
        - Perl
