http:
    - matchers:
        - condition: and
          part: header
          type: word
          words:
            - CouchDB/
            - Erlang OTP/
        - status:
            - 200
          type: status
      matchers-condition: and
      method: GET
      path:
        - '{{BaseURL}}/_all_dbs'
id: couchdb-exposure
info:
    author: organiccrap
    classification:
        cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
        cvss-score: 0
        cwe-id: CWE-200
    description: Apache CouchDB panel was detected.
    metadata:
        max-request: 1
    name: Apache CouchDB Panel - Detect
    severity: info
    tags:
        - panel
        - couchdb
