http:
    - extractors:
        - group: 1
          name: version
          part: body
          regex:
            - \"version\"\:\"([0-9.]+)\"}
            - \"subTitle\":\"Grafana v([0-9.]+)
          type: regex
        - kval:
            - version
          type: kval
      matchers:
        - part: body
          type: word
          words:
            - <title>Grafana</title>
      method: GET
      path:
        - '{{BaseURL}}/login'
id: grafana-detect
info:
    author: organiccrap,AdamCrosser,bhutch
    classification:
        cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
        cvss-score: 0
        cwe-id: CWE-200
    description: Grafana login panel was detected.
    metadata:
        category: devops
        max-request: 1
        product: grafana
        shodan-query: title:"Grafana"
        vendor: grafana
    name: Grafana Login Panel - Detect
    severity: info
    tags:
        - panel
        - grafana
        - detect
