http:
    - matchers:
        - condition: and
          dsl:
            - status_code_1 == 500 && contains(body_1,'code')
            - contains(body_1,"0x26e11001")
          type: dsl
      matchers-condition: and
      raw:
        - |
          GET /svm/api/external/report HTTP/1.1
          Host: {{Hostname}}
id: hikvision-isecure-center-report-upload
info:
    author: SleepingBag945
    description: 海康威视综合安防管理平台任意文件上传
    name: hikvision-isecure-center-report-upload
    reference:
        - https://github.com/zan8in/afrog/commit/641785d38b84ff3ea4c554e1c0620b3670358591
    severity: critical
    tags:
        - hikvision
        - ivms
        - HIKVISION-iSecure-Center
