http:
    - matchers:
        - status:
            - 200
          type: status
        - part: body
          type: word
          words:
            - Swagger-Bootstrap-UI
      matchers-condition: and
      raw:
        - |
          GET /jeecg-boot/ HTTP/1.1
          Host: {{Hostname}}
id: jeecg-boot-unauth
info:
    author: SleepingBag945
    description: Jeecg Boot 未授权访问
    name: Jeecg Boot Unauth
    reference:
        - https://github.com/zan8in/afrog/blob/main/v2/pocs/afrog-pocs/unauthorized/jeecg-boot-unauth.yaml
    severity: high
    tags:
        - JEECG
        - Bootstrap
        - Jeecg-Boot
        - Swagger
