http:
    - matchers:
        - type: word
          words:
            - user-picker
      method: GET
      path:
        - '{{BaseURL}}/secure/popups/UserPickerBrowser.jspa'
id: jira-unauthenticated-user-picker
info:
    author: TechbrunchFR
    metadata:
        max-request: 1
        shodan-query: http.component:"Atlassian Jira"
    name: Jira Unauthenticated User Picker
    severity: info
    tags:
        - atlassian
        - jira
        - authenticate
