http:
    - matchers:
        - status:
            - 200
          type: status
        - part: body
          type: word
          words:
            - type=MBeanFactory
        - part: body
          type: word
          words:
            - createJNDIRealm
      matchers-condition: and
      method: GET
      path:
        - '{{BaseURL}}/jolokia/list'
        - '{{BaseURL}}/actuator/jolokia/list'
      stop-at-first-match: true
id: jolokia-realm-jndi-rce
info:
    author: SleepingBag945
    name: jolokia Realm JNDI RCE
    reference:
        - https://thinkloveshare.com/hacking/ssrf_to_rce_with_jolokia_and_mbeans/
        - https://github.com/laluka/jolokia-exploitation-toolkit
        - https://github.com/LandGrey/SpringBootVulExploit#0x05jolokia-realm-jndi-rce
    severity: high
    tags:
        - jolokia
        - springboot
        - tomcat
        - Spring
        - Jolokia
        - thin
