http:
    - matchers:
        - part: body
          type: word
          words:
            - '"username": "admin",'
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /web/session/authenticate HTTP/1.1
          Host: {{Hostname}}
          Accept: application/json, text/javascript, */*; q=0.01
          Content-Type: application/json
          X-Requested-With: XMLHttpRequest
          Accept-Encoding: gzip, deflate
          Referer: {{BaseURL}}
          Origin: {{BaseURL}}

          {"jsonrpc":"2.0","method":"call","params":{"db":"OPENERP7","login":"admin","password":"admin","base_location":"{{BaseURL}}","session_id":"E10ADC3949BA59ABBE56E057F20F883E","context":{}},"id":"r7"}
id: openerp-default-password
info:
    author: SleepingBag945
    description: app="OpenERP"
    name: Openerp Default Password
    severity: high
    tags:
        - authenticate
        - OpenERP
        - openerp
