http:
    - attack: clusterbomb
      matchers:
        - condition: and
          part: header
          type: word
          words:
            - 'ocation:'
            - /index.jsp
        - status:
            - 302
          type: status
      matchers-condition: and
      payloads:
        password:
            - admin
            - admin888
            - 123456
            - 12345678
            - openfire
        username:
            - admin
      raw:
        - |
          POST /login.jsp HTTP/1.1
          Host: {{Hostname}}

          url=%2Findex.jsp&login=true&username=admin&password=admin
      stop-at-first-match: true
id: openfire-default-password
info:
    author: SleepingBag945
    description: |
        openfire允许后台上传未经校验的恶意插件，可导致直接getshell和控制服务器。
    name: OpenFire Default Password
    reference:
        - https://mp.weixin.qq.com/s/PGaCY-GbWyx8z2nLErNlUg
    severity: high
    tags:
        - openfire
        - default-login
        - Cluster
        - Openfire
