http:
    - extractors:
        - group: 1
          part: body
          regex:
            - v=([a-z0-9-._]+)
          type: regex
      matchers:
        - type: word
          words:
            - <title>phpMyAdmin
            - pmahomme
      method: GET
      path:
        - '{{BaseURL}}/phpmyadmin/'
        - '{{BaseURL}}/admin/phpmyadmin/'
        - '{{BaseURL}}/_phpmyadmin/'
        - '{{BaseURL}}/administrator/components/com_joommyadmin/phpmyadmin/'
        - '{{BaseURL}}/apache-default/phpmyadmin/'
        - '{{BaseURL}}/blog/phpmyadmin/'
        - '{{BaseURL}}/forum/phpmyadmin/'
        - '{{BaseURL}}/php/phpmyadmin/'
        - '{{BaseURL}}/typo3/phpmyadmin/'
        - '{{BaseURL}}/web/phpmyadmin/'
        - '{{BaseURL}}/xampp/phpmyadmin/'
        - '{{BaseURL}}/phpMyAdmin/'
      stop-at-first-match: true
id: phpmyadmin-panel
info:
    author: pdteam
    classification:
        cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
        cvss-score: 0
        cwe-id: CWE-200
    description: phpMyAdmin panel was detected.
    metadata:
        max-request: 12
        shodan-query: http.title:phpMyAdmin
    name: phpMyAdmin Panel - Detect
    severity: info
    tags:
        - panel
        - phpmyadmin
        - xampp
        - PHPM
        - typo3
        - TYPO3
        - XAMPP
        - phpMyAdmin
