http:
    - matchers:
        - condition: and
          dsl:
            - contains(header_1, "Set-Cookie") && (contains(header_1, "rememberMe=") || contains(header_1, "=deleteMe"))
            - '!contains(header_2, "rememberMe=") && !contains(header_2, "=deleteMe")'
          type: dsl
      raw:
        - |
          GET / HTTP/1.1
          Host: {{Hostname}}
          Cookie: JSESSIONID={{randstr}};rememberMe=123;
        - |
          GET / HTTP/1.1
          Host: {{Hostname}}
          Cookie: JSESSIONID={{randstr}};rememberMe=r5R1vjRtaXaaHbMnnO01hjOvZqrdk0KpdvoiI35zqOII1fQ/Iv5osD/ucTagj2uptg9IjZffTO3eGka9/EKWY8+YjwD2O4MaNsfs9R9245QM7TPo2TvVAl8nduVZZ8ygRGqxv1iWFLxC1Sl74EJrlGErq1/Ykgb3i/zcmk26MS/R7VKpFA9Qulb+n5o/GiYN;
      req-condition: true
id: ruoyi-shiro-default-key-gcm
info:
    author: SleepingBag945
    description: Ruoyi-shiro框架默认key fCq+/xW488hMTCD+cmJ3aQ== ,可尝试寻找利用链进行命令执行。
    name: Detect RuoYi CMS Shiro Default Key
    severity: critical
    tags:
        - shiro
        - ruoyi
