http:
    - matchers:
        - part: body
          type: word
          words:
            - WebLogic UDDI Explorer
        - status:
            - 200
          type: status
      matchers-condition: and
      method: GET
      path:
        - '{{BaseURL}}/uddiexplorer/'
id: weblogic-uddiexplorer
info:
    author: pdteam
    classification:
        cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
        cvss-score: 0
        cwe-id: CWE-200
    description: |
        Oracle WebLogic UDDI Explorer panel was detected.
    metadata:
        max-request: 1
    name: Oracle WebLogic UDDI Explorer Panel - Detect
    reference:
        - https://www.tenable.com/plugins/was/112421
    severity: info
    tags:
        - panel
        - oracle
        - weblogic
        - tenable
        - WebLogic
