http:
    - matchers:
        - condition: and
          type: word
          words:
            - id
            - permissions
            - checkstate
      raw:
        - |
          GET /C6/Jhsoft.Web.users/GetTreeDate.aspx/?id=1 HTTP/1.1
          Host: {{Hostname}}
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0
          Content-Type: application/x-www-form-urlencoded
id: jinher-oa-c6-gettreedate-sqli
info:
    author: again,pphua
    metadata:
        fofa-query: app="金和网络-金和OA"
    name: 金和OA GetTreeDate.aspx SQL注入
    severity: critical
    tags:
        - jinher
        - 金和oa
        - 金和网络-金和OA
